open-craft/opencraft

README.md
At the moment the README doesn't have info on how to get set up with a user for an instance.
This PR adds brief instructions to the README on how to create a user and then log in with that account.
=> Add information on how to create a dev user

instance/github.py, instance/migrations/0031_openedxinstance_github_pr_url.py, instance/models/instance.py, instance/tasks.py, instance/tests/models/test_instance.py, instance/tests/test_tasks.py
Stores the full URL of a pull request in the instance model instead of just the number.
Also tweaks the makefile to fix issues I ran into when trying to use it.
=> Full branch url

Vagrantfile
@Kelketek To fix an out of memory error I had while reviewing https://github.com/open-craft/opencraft/pull/8 locally - it's a one-liner. Good for you?
=> Vagrant - Increase VM memory to 1GB to avoid OOM process kills

Makefile, Procfile, instance/tasks.py, instance/tests/base.py, instance/tests/integration/base.py, instance/tests/test_ansible.py, instance/tests/test_gandi.py, instance/tests/test_openstack.py, instance/tests/test_tasks.py
This ensure connections are closed when no task is executing, and ensure no stale connection remains active across task runs.
See http://huey.readthedocs.org/en/latest/django.html#tasks-that-execute-queries
Also prevents sharing the periodic scheduler process with a worker, to avoid using multiple threads, and keep the logs clean. `periodic.1` then only get periodic scheduling log items, instead of mixing worker and scheduler log lines)
=> Close DB connection upon task completion

instance/github.py, instance/tests/test_github.py, instance/tests/test_tasks.py
@antoviaque This should fix the outstanding issue with the fork name.
=> Mark PR repos on the upstream repo, not the fork.

README.md, Vagrantfile, bin/bootstrap, debian_packages.lst
This allows it to be used for setting up development environments without vagrant, on a vanilla ubuntu install or on an EC2 instance for example.
This PR is a result of my attempts to set up an EC2 instance to run integration tests.
=> Move vagrant provisioning script into separate file

instance/models/instance.py, instance/tests/models/test_instance.py, instance/tests/test_utils.py, instance/utils.py, opencraft/settings.py, pylintrc
This PR introduces two new settings:
* `ANSIBLE_LINE_TIMEOUT`: The time in seconds to wait for the next log line when running an Ansible playbook.
* `ANSIBLE_GLOBAL_TIMEOUT`: The timeout in seconds for an entire Ansible playbook.
These settings make sure playbook runs don't hang indefintely.
=> Allow to set timeouts for playbook runs.

opencraft/settings.py
This typo was introduced when addressing review comments in #29.
cc @antoviaque
=> Fix misnamed env variable.

README.md, debian_packages.lst
This package is needed since recently to install the Ansible prerequisites, see
https://github.com/edx/configuration/pull/2537.
Also remove a redundant command from the README file.
=> Add libmysqlclient-dev to the system dependencies.

.env.test, Makefile, README.md, bin/bootstrap, circle.yml, debian_db_packages.lst, debian_packages.lst, instance/github.py, instance/migrations/0036_external_databases.py, instance/migrations/0037_merge.py, instance/migrations/0038_merge.py, instance/models/instance.py, instance/tasks.py, instance/templates/instance/ansible/mongo.yml, instance/templates/instance/ansible/mysql.yml, instance/tests/factories/pr.py, instance/tests/integration/factories/instance.py, instance/tests/integration/integration_instance.py, instance/tests/models/test_instance.py, instance/tests/test_github.py, instance/tests/test_tasks.py, opencraft/settings.py, opencraft/tests/utils.py, requirements.txt
This pull request adds support for instances to use external mysql and mongo databases. The goal is to [preserve databases during sandbox reprovisioning](http://opencraft.uservoice.com/forums/280754-opencraft/suggestions/9541143-preserve-databases-during-sandbox-reprovisioning).
Default databases for new instances can be set through the `INSTANCE_MYSQL_URL` and `INSTANCE_MONGO_URL` settings.
If the default is to use external databases but the PR submitter would like to use local databases, she can include `(ephemeral databases)` in the pull request body on the same line as the sandbox url to override the default.
See also: https://github.com/edx/configuration/pull/2310
=> Persistent sandbox databases

Makefile, debian_packages.lst, requirements.txt
**Before**:
```
Traceback (most recent call last):
File "/home/vagrant/.virtualenvs/opencraft/bin/jasmine-ci", line 11, in <module>
sys.exit(continuous_integration())
File "/home/vagrant/.virtualenvs/opencraft/lib/python3.4/site-packages/jasmine/entry_points.py", line 44, in continuous_integration
app=jasmine_app.app
File "/home/vagrant/.virtualenvs/opencraft/lib/python3.4/site-packages/jasmine/ci.py", line 72, in run
test_server = self._start_test_server(app, browser)
File "/home/vagrant/.virtualenvs/opencraft/lib/python3.4/site-packages/jasmine/ci.py", line 115, in _start_test_server
self.browser = webdriver.WebDriver()
File "/home/vagrant/.virtualenvs/opencraft/lib/python3.4/site-packages/selenium/webdriver/firefox/webdriver.py", line 78, in __init__
self.binary, timeout)
File …
```
=> Add xvfb for running selenium tests in vagrant VM

instance/models/log_entry.py, instance/tests/models/test_log_entry.py
Lowercase 'info' is not a valid choice, and will trigger a ValidationError:
```
ValidationError: {'level': ["Value 'info' is not a valid choice."]}
```
=> Set default log level to valid 'INFO' value

instance/api/instance.py, instance/models/instance.py, instance/serializers/instance.py, instance/static/html/instance/index.html, instance/static/js/src/instance.js, instance/tests/api/test_instance.py, instance/tests/fixtures/api/instance_detail.json, instance/tests/fixtures/api/instances_list.json, instance/tests/js/instance_app_spec.js, instance/tests/models/test_log_entry.py, opencraft/settings.py
See [OC-1035](https://tasks.opencraft.com/browse/OC-1035).
The interface takes a very long time to load, as it tries to fetch all log entries for all instances and there can be a lot of data sent over the wire.
This pull request adds a configurable limit on the number of log entries returned in the initial request. You can set the limit using the `LOG_LIMIT` environment variable (default: 10000).
In addition, loading log entries from the server is deferred until the user actually selects an instance.
To run the js tests in your development environment, see https://github.com/open-craft/opencraft/pull/39.
To test manually, create a server and instance with some log entries. We can use the test factories for this:
```python
from instance.tests.models.factories.server import …
```
=> Limit the number of log lines displayed

instance/tests/models/test_server.py, instance/utils.py
The nova client currently only retries failed DNS lookups, socket connections and connection timeouts, as per the [requests defaults](http://docs.python-requests.org/en/master/api/#requests.adapters.HTTPAdapter). This pull request extends the retry policy to include server errors (5XX responses).
=> The nova client should retry in case of server errors

instance/api/instance.py, instance/github.py, instance/models/instance.py, instance/static/html/instance/index.html, instance/static/js/src/instance.js, instance/static/scss/instance.scss, instance/tests/api/test_instance.py, instance/tests/js/instance_app_spec.js, instance/tests/test_github.py
If a PR's branch has been deleted from GitHub and the user clicks "Provision", the provisioning fails silently, without any relevant error appearing in the web console error log (also the status says "provisioning" even though it is not).
- Return a client error response with a useful error message when the user attempts to provision an instance for a branch that does not exist
- Display that error message as a notification to the user
=> Display error when provisioning instance for deleted branch

instance/openstack.py
It doesn't like it and prints a warning:
UserWarning: 'novaclient.v2.client.Client' is not designed to be initialized directly. It is inner class of novaclient. Please, use 'novaclient.client.Client' instead. Related lp bug-report: 1493576
=> Don't instantiate novaclient V2 directly

instance/ansible.py, instance/tests/test_ansible.py
1. Install IM and setup environment settings
2. Go to `/localhost/admin` and create an instance. 
3. Wait until provisioning is started
4. Log in to shell account to you vagrant instance ``vagrant ssh`` and go to ``/tmp`` dir. Note that quite a lot of folders was created. 
5. Run ``ps -aef | grep python``, and kill the ansible process (killing step is not-neccessary, as venv's are not deleted at all, but it makes it faster)
6. Due to the fact provisioning is restarted you might need to kill it three times. 
7. Note that some of the folders in ``/tmp`` are not deleted. There should be as many folders left as many propositioning runs you started, these folders contain virtualenvs created during provisioning runs. 
8. (For bonus points) If you kill ansible in a "proper" moment it will left a …
=> Clean temporary directories left from previous provisioning runs.

README.md, opencraft/settings.py
Switch the logging file handler in the Django configuration to `RotatingFileHandler`, to avoid letting log files grow too large. 
Two new configuration variables:
* `LOGGING_ROTATE_MAX_KBYTES`: The max size of each log file (in KB)
* `LOGGING_ROTATE_MAX_FILES`: The max number of log files to keep
How to test:
1. Set `LOGGING_ROTATE_MAX_KBYTES=1` in your local OpenCraft IM `.env` file - this is to trigger log rotation without needing to generate huge logs
2. Generate some logs, for example by provisioning a new instance
3. Check `log/main.*` - you should see lots of small log files, a few KB each (it seem to still log a full message even if it exceeds slightly the max size, which is a desired behavior).
Note: No unit test since this is only a configuration change, but if you see a …
=> Logrotate - Set logging to use `RotatingFileHandler`

instance/models/instance.py, instance/models/mixins/__init__.py, instance/models/mixins/ansible.py, instance/models/mixins/database.py, instance/models/mixins/utilities.py, instance/models/mixins/version_control.py, instance/tests/models/test_instance.py, instance/tests/test_tasks.py
**Description:** Sends email notifications to server admins if provisioning fails
1. Provide email settings in .env file:
1.1. `ADMINS='[["you", "you@opencraft.com"]]'`
1.2. `SERVER_EMAIL = 'you@opencraft.com'`  # SMTP Server refuses connections from unknown hosts
1.3. EMAIL_HOST, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD - from opencraft/secrets repository
2. Patch `instance.provision` so that it is guaranteed to fail, or otherwise ensure provisioning will fail.
3. Provision an instance.
You should receive an email with details on what went wrong:
Note there are two flavors of "failure":
1. Unhandled exception
2. `deploy` returned non-zero exit code.
Emails are slightly different, example screenshot is for `deploy` returned non-zero exit code failure.
=> Alert admins by email if provisioning fails

.prospector/opencraft.yml, instance/api/instance.py, instance/models/instance.py, instance/models/mixins/ansible.py, instance/models/server.py, instance/models/utils.py, instance/serializers/instance.py, instance/serializers/server.py, instance/tests/api/test_instance.py, instance/tests/integration/integration_instance.py, instance/tests/models/factories/server.py, instance/tests/models/test_instance.py, instance/tests/models/test_server.py, instance/tests/models/test_utils.py
This replaces the `status` and `progress` attributes of the `Server` class with a finite state machine implementation.
The immediate benefits are:
* Strong guarantee that the `Server` instance is always in one of the specified states.
* Transitions between states are clearly defined. One cannot use public methods to change from "New" to "Provisioning" for example.
* Removed states that weren't being used
The future benefits are much greater, but this is just "a step in the right direction". See below for next steps to help give context.
* Any "resource" (such as a server) can have finite state machines attached to it
* Each state machine is always in one of a pre-defined number of states
* The value of the state can optionally be saved to the database if the resource is a django model
* …
=> State machine (OC-906)

instance/models/instance.py, instance/models/server.py, instance/models/utils.py, instance/serializers/server.py, instance/static/html/instance/index.html, instance/tests/models/test_server.py
... and use new `name` and `description` properties when displaying information about current state of an instance to a user.
Follows up on https://github.com/open-craft/opencraft/pull/51.
cf. [OC-1535](https://tasks.opencraft.com/browse/OC-1535)
**Update**: As of https://github.com/open-craft/opencraft/pull/52/commits/0378c167170e18c55fe87a18a6201d6e7a0898d6, also addresses [this request](https://github.com/open-craft/opencraft/pull/52#discussion_r59595130) from @bradenmacdonald.
=> Make code agnostic to specific server states

instance/models/server.py, instance/tests/models/test_server.py
cf. [OC-1547](https://tasks.opencraft.com/browse/OC-1547)
1. Run unit tests via `make test_unit` on current `master` (https://github.com/open-craft/opencraft/commit/14f1eeb46da78303bc836a431e289c920f0f305c). Observe that the process takes about two minutes, with the majority of time being spent on a single test.
2. Check out `speed-up-tests`.
3. Run unit tests again. Observe that the process takes about 5-7 seconds.
=> Speed up unit test for "provisioned" to "rebooting" status update

Makefile, bin/run-circleci-tests, circle.yml, instance/migrations/0039_auto_20160416_1729.py, instance/models/utils.py
These are migrations currently missing on the master branch.  I also needed to normalise the order of choices for the progress and status fields, since with the randomised order we had before we would get a new migration everytime you run `makemigrations`.
cc @bradenmacdonald
(Shouldn't the tests be able to catch missing migrations?)
=> Add pending migrations.

.env.test, Makefile, bin/run-circleci-tests, circle.yml, instance/migrations/0035_reset_ansible_settings.py, instance/migrations/0039_auto_20160416_1729.py, instance/migrations/0040_auto_20160416_1735.py, instance/models/instance.py, instance/models/mixins/database.py, instance/models/utils.py, instance/openstack.py, instance/templates/instance/ansible/swift.yml, instance/templates/instance/ansible/vars.yml, instance/tests/base.py, instance/tests/integration/integration_instance.py, instance/tests/models/test_instance.py, opencraft/settings.py, pylintrc, requirements.txt
Add support to provision Swift containers.  This is implemented analogously to MySQL and MongoDB provisioning (see #11).  Swift containers are only provisioned for instances with persistent databases, but I also added a separate flag to disable Swift provisioning if it's unwanted for some reason.
Unlike MySQL and MongoDB provisioning, Swift provisioning can't be tested locally with reasonable effort (see the [Swift All-In-One documentation](http://docs.openstack.org/developer/swift/development_saio.html) to get an idea of the complexity of setting up a local Swift cluster.), so the unit tests only test whether the API call to the Swift API is made.  The integration test will provision Swift containers though.  They aren't cleaned up when the instance is terminated (which is kind of the …
=> Support provisioning Swift containers.

instance/models/mixins/database.py, instance/openstack.py, instance/tests/integration/base.py, instance/tests/integration/integration_instance.py, instance/tests/models/test_instance.py
This change introduces `deprovision_*()` methods for deprovisioning storage backends, and calls these functions in the `tearDown()` methods for applicable unit and integration tests.
The unit tests already did a clean-up, but not in `tearDown()`, so they would leak the databases if they errored out earlier.
This is implemented on top of #54.  Only the last two commits need to be reviewed here.
=> Improve storage backend clean up after running the unit and integration tests.

instance/templates/instance/ansible/vars.yml
**Dependencies:** https://github.com/edx/configuration/pull/2993
=> Shorter timeout for celery workers

betatest/forms.py, instance/admin.py, instance/logging.py, instance/migrations/0045_generic_logging1.py, instance/migrations/0046_generic_logging2.py, instance/migrations/0047_generic_logging3.py, instance/models/instance.py, instance/models/log_entry.py, instance/tests/factories/pr.py, instance/tests/integration/factories/instance.py, instance/tests/models/factories/instance.py, instance/tests/models/factories/server.py, instance/tests/models/test_log_entry.py, pylintrc
This change combines `GeneralLogEntry`, `InstanceLogEntry`, `ServerLogEntry` into a single `LogEntry` class that uses [the contenttypes framework](https://docs.djangoproject.com/en/1.9/ref/contrib/contenttypes/) to hold a reference to the object that "owns" each log entry.
This change is required in order to accommodate the refactoring in #63. Specifically, there is a new intermediate class, `AppServer`, which would need a new table to hold its logs. And `AppServer` is abstract (since multi-table inheritance in django gets very messy), so there are potentially a number of concrete `AppServer` subclasses that we may have, and we can't expect to create a separate logging table for each one. Luckily, django already has a wonderful and longstanding solution to this problem, which is the …
=> Combine log entries (Prereq for OC-1541)

Procfile
This was preivously a no-op option (since this is the default), but kept in the command-line for clarity. The latest version of Huey removed the command altogether, so we do too.
@bradenmacdonald @smarnach
=> Remove `--periodic` option from Huey (unavailable in the latest version)

betatest/tests/test_views.py
I am getting flaky pylint warnings with the django mail `.outbox` property. I'm not sure why it sometimes is a warning and sometimes not, but I think because Django creates that attribute dynamically, it sometimes exists and sometimes doesn't.
What I see ([example build](https://circleci.com/gh/open-craft/opencraft/713)):
```
betatest/tests/test_views.py
Line: 112
pylint: no-member / Module 'django.core.mail' has no 'outbox' member (col 29)
Line: 113
pylint: no-member / Module 'django.core.mail' has no 'outbox' member (col 34)
Line: 133
pylint: no-member / Module 'django.core.mail' has no 'outbox' member (col 29)`
```
But if I put a `disable=no-member`, then it sometimes works but sometimes I get:
```
Line: 112
pylint: useless-suppression / Useless suppression of 'no-member'
Line: 113 …
```
=> Fix flaky pylint warning

circle.yml, instance/models/mixins/database.py, instance/tests/base.py, instance/tests/models/test_instance_mixins.py, instance/tests/test_tasks.py, requirements.txt
Removes the following warnings:
**djangular_tags deprecation** (`make test_unit` or `make rundev`)
```
/home/vagrant/.virtualenvs/opencraft/lib/python3.5/site-packages/djng/templatetags/djangular_tags.py:4: UserWarning: Templatetags `djangular_tags` have been renamed to `djng_tags`.
"Templatetags `djangular_tags` have been renamed to `djng_tags`."
```
**MySQL auth warnings** (`make test_unit`):
```
/home/vagrant/opencraft/instance/models/mixins/database.py:68: Warning: Using GRANT for creating new user is deprecated and will be removed in future release. Create new user with CREATE USER statement.
(self.mysql_user, self.mysql_pass))
mysql: [Warning] Using a password on the command line interface can be insecure.
.mysql: [Warning] Using a password on the command line interface can be …
```
=> Eliminate warnings

Makefile, bin/run-circleci-tests, circle.yml, instance/tests/models/test_instance.py, instance/tests/models/test_instance_mixins.py, instance/tests/models/test_server.py
The integration tests are currently only run if a `.env.integration` file is present. We run integration tests on CircleCI by copying this file over from the stage server before running the tests. We would like to store credentials on CircleCI directly, but for that to work the integration tests must be able to run without a `.env.integration` file. This pull request updates the Makefile to allow the integration tests to run with credentials from the environment, if the `OPENSTACK_USER` environment variable is set.
=> Run integration tests with credentials from environment

instance/static/html/instance/details.html, pr_watch/api.py, pr_watch/models.py, pr_watch/serializers.py, pr_watch/tests/test_api.py, pr_watch/tests/test_models.py
I noticed on our stage server that this button wasn't working:
It seems that I confused the PR source fork with the PR target fork at some point, which caused this bug when using the API to update an instance based on its PR settings. (This did not affect the automatic creation of instances when a new PR was detected.)
I have in mind a nicer way to refactor this code, but for now this is a quick fix.
=> Fix "Update Instance from PR" button when PR source and target forks are different (OC-1541)

README.md, instance/models/instance.py, instance/models/openedx_instance.py, instance/tests/models/test_openedx_instance.py
I noticed that after my refactor in #63, it's possible to delete an `OpenEdXInstance` but leave behind an `InstanceReference`, or vice versa. The syntax for deleting all of an instance's VMs was also more complicated.
With this changeset, deleting either an `Instance` or an `InstanceReference` always deletes the other object (unless using bulk deletion through the ORM). Also, calling `instance.delete()` will delete the instance as well as the VMs of all of its appservers.
**Author Concerns**
Is it too dangerous that one method can delete an instance and terminate all of its VMs?
=> Make instance deletion more robust (part of OC-1541)

pr_watch/models.py, pr_watch/tasks.py, pr_watch/tests/factories.py, pr_watch/tests/test_models.py
I noticed on our stage server that whenever the GitHub watcher checks the status of a PR, the "Loading..." indicator appears in the web UI and the instance list is refreshed. This is because after #63, the PR watcher ends up updating instance properties and calling `.save()` on each time it checks a PR.
With this change, the periodic PR watcher only updates the instance when the PR is new. To update an instance from an existing PR, you have to do it manually by clicking the "Update instance settings from PR" button in the web UI.
This should reduce load on the server slightly and eliminate the "Loading..." flicker, while also making behavior more predictable.
Alternative: The alternative would be to keep the current behavior of automatically updating instance settings from the PR every …
=> Don't trigger an instance list update in the UI for each PR every minute (OC-1541)

README.md, instance/factories.py, instance/models/mixins/openedx_database.py, instance/models/mixins/openedx_storage.py, instance/models/openedx_instance.py, instance/templates/instance/ansible/prod-vars.yml, instance/tests/models/test_openedx_instance.py, instance/tests/test_factories.py, opencraft/settings.py
cf. [OC-1554](https://tasks.opencraft.com/browse/OC-1554).
**Changes**
Adds two factory functions for creating instances from the shell:
- `instance_factory` creates instances with settings that are appropriate for sandboxes.
- `production_instance_factory` creates instances with settings that are appropriate for production instances.
The only mandatory argument for each function is `sub_domain`. Defaults for other fields can be overridden by passing additional keyword arguments to the functions. If necessary it is also possible to modify instances after they have been created by the functions (before starting the provisioning process).
1. Start the shell via `make shell`.
2. Import the new functions via:
```python
from instance.factories import instance_factory, …
```
=> Add factory functions for creating sandbox and production instances

Makefile
Because the way that Firefox pops up and steals focus for each test is really annoying.
=> Run browser tests headlessly

instance/models/openedx_instance.py, instance/tests/models/test_openedx_instance.py, requirements.txt
Sandboxes provisioned on stage.console.opencraft.com cannot be accessed by url, only by ip address. On investigation, it turns out that the dns records are being set incorrectly, as they ignore any part of the subdomain that has been set as part of the instance's base domain. For example:
The `INSTANCES_BASE_DOMAIN` setting is set to `stage.opencraft.com`. When a new instance is created with a subdomain of `pr12338-2.sandbox`, 3 gandi DNS records are added:
- A: `pr12338-2.sandbox.opencraft.com` -> public IP
- CNAME: `preview-pr12338-2.sandbox.opencraft.com` -> `pr12338-2.sandbox.opencraft.com`
- CNAME: `studio-pr12338-2.sandbox.opencraft.com` -> `pr12338-2.sandbox.opencraft.com`
However, the instance expects to be reached at pr12338-2.sandbox.**stage.**opencraft.com.
This pull request …
=> Don't break dns if an instance's base domain includes a subdomain part

instance/templates/instance/index.html, registration/api.py, registration/forms.py, registration/tests/browser/browser_registration.py, registration/tests/test_views.py, registration/views.py
I noticed a bug in the beta registration after I deployed it to stage. If you are already logged in, but have not yet registered, the form will not allow you to register ('username is already taken'). This pull request fixes the bug by ignoring the logged in user when checking for existing usernames and emails.
1. Create a new user in the admin or the shell
2. Log in as that user
3. Go to `/registration/`. The username and email fields should be prepopulated and read only, and the password fields should not appear.
4. Fill in and submit the form
=> Fix registration for existing users

registration/templates/registration/registration.html, registration/tests/test_views.py
The message "Your application for the OpenCraft beta has been successfully sent! We will contact you after reviewing it." still shows even when the user application is in the "accepted" or "refused" status. This should only display while the application is pending.
This pull request adds different messages for the 'pending', 'accepted' and 'refused' statuses.
=> Show different message for each application status

registration/forms.py
So that we can deny access to users by setting it to False later.
=> Set is_active=True for beta testers

instance/static/js/src/instance.js, instance/templates/instance/index.html, instance/urls.py, templates/base.html
The instance manager django app now lives at `/instance/`, which means that we end up with routes like `/instance/#/instances/50`. This pull request removes the `/instances/` prefix from the angular routes and turns on the html5 pushState mode, turning that url into the less redundant `/instance/50`.
=> Don't prefix IM angular routes with /instances/

instance/models/mixins/database.py, instance/models/mixins/openedx_database.py, instance/models/mixins/utilities.py, instance/models/openedx_instance.py, instance/templates/instance/ansible/mysql.yml, instance/tests/models/test_openedx_database_mixins.py, instance/tests/models/test_openedx_instance.py, registration/tests/browser/browser_registration.py
cf. [OC-1610](https://tasks.opencraft.com/browse/OC-1610)
**Dependencies**
* https://github.com/edx/configuration/pull/3052 (fixes issue where `edxlocal` role would fail due to missing dependencies when using non-local databases)
* https://github.com/open-craft/configuration/pull/5 (fixes issue affecting creation of user for ecommerce database in integration tests; *should merge before this PR* so we can go back to using [open-craft:integration](https://github.com/open-craft/configuration/tree/integration) branch for integration tests)
1. Prepare your `.env` by setting `INSTANCE_MYSQL_URL` and `INSTANCE_MONGO_URL` to values from corresponding settings from stage.console.opencraft.com `.env` file. Make sure your `.env` sets `SWIFT_ENABLE=true` (if it doesn't contain …
=> Set up databases for different services when using persistent databases

instance/templates/instance/ansible/vars.yml
The setting was uppercased in edx/configuration#2993 after #65 was merged, and never corrected here.
=> Correct case of Ansible setting for Celery worker timeout.

.env.test, backup_swift/__init__.py, backup_swift/apps.py, backup_swift/management/commands/backup_swift.py, backup_swift/tarsnap.py, backup_swift/tasks.py, backup_swift/tests.py, backup_swift/utils.py, deploy/README.md, deploy/install_tarsnap.yml, deploy/requirements.yml, instance/openstack.py, instance/tests/integration/integration_instance.py, instance/tests/models/test_openedx_storage_mixins.py, instance/tests/test_openstack.py, opencraft/settings.py
I will prepare Ansible scripts that deploy backup functionalities on a production environment, however for manual tests it might be easier to use devstack/IM vagrant VMV. Setting up devstack is somewhat cumbersome, if this turns out to be taking a lot of your time, please wait until I prepare a IM sandbox for this feature. 
1. [Optional step] Take a snapshot, or install atop a fresh VM. 
2. Pull this branch.
3. Download roles ``cd deploy && ansible-galaxy install -r requirements.yml``. 
3. Install tarsnap on the devstack. To install tarsnap you'll need to run ansible scripts on the VM. First get connection details ``vagrant ssh-config``, cd to deploy folder and `ansible-playbook install_tarsnap.yml -i localhost, -e "ansible_port=2222" --ssh-common-args "-o UserKnownHostsFile=/dev/null -o …
=> OC-1532 Added support for backing up swift containers.

instance/factories.py, instance/tests/test_factories.py, opencraft/settings.py
We want to be able to set different default forks for production instances than for sandboxes.  For the sandboxes, the upstream forks should be used by default, while we want to use the modified named release branches for production instances by default.
This PR introduces two new settings to allow this.
=> Introduce repository fork settings to be used for production instances.

registration/forms.py, registration/static/js/src/registration.js, registration/templates/registration/registration.html, registration/templates/registration/registration_form.html, registration/tests/js/registration_app_spec.js, registration/tests/test_views.py, registration/tests/utils.py, requirements.txt, static/external/js/Makefile
... to improve quality of user-visible feedback from password validation.
cf. [OC-1587](https://tasks.opencraft.com/browse/OC-1587)
The form now behaves like this w/r/t password validation: When user enters password it is validated on the client, and the form displays feedback (suggestions and warnings) from `zxcvbn`. If a user goes ahead and submits the form while password strength is still too low, the server rejects the submission based on the password strength computed on the client, and the form displays a generic error message: "Please use a stronger password: avoid common patterns and make it long enough to be difficult to crack.". At this point, the input field for "password" is empty (since `django-angular` clears contents of password fields by default), so it wouldn't make sense …
=> Use js version of zxcvbn

static/scss/layout/_footer.scss, static/scss/pages/_page.scss
@pomegranited noticed that there is no footer spacing on smaller displays:
This pull request fixes the spacing.
=> Fix footer spacing on smaller displays

bin/run-circleci-tests, registration/tests/browser/browser_registration.py, registration/tests/test_views.py, registration/tests/utils.py
cf. [OC-1651](https://tasks.opencraft.com/browse/OC-1651)
Fixes the following issues affecting CircleCI builds:
* `ConnectionRefusedError` affecting unit tests (not possible to reproduce locally):
```
======================================================================
ERROR: test_get_authenticated (instance.tests.api.test_instance.InstanceAPITestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/ubuntu/virtualenvs/venv-3.5.1/lib/python3.5/site-packages/redis/connection.py", line 439, in connect
sock = self._connect()
File "/home/ubuntu/virtualenvs/venv-3.5.1/lib/python3.5/site-packages/redis/connection.py", line 494, in _connect
raise err
File "/home/ubuntu/virtualenvs/venv-3.5.1/lib/python3.5/site-packages/redis/c …
```
=> Fix intermittent errors affecting CircleCI builds

instance/models/openedx_instance.py, instance/templates/instance/ansible/vars.yml, instance/tests/models/test_openedx_instance.py
This Ansible variable is used as the `server_name` for nginx, so it must match the Studio domain name.
=> Set CMS_HOSTNAME Ansible variable to the Studio domain.

instance/templates/instance/ansible/s3.yml, instance/templates/instance/ansible/vars.yml
This adds some ansible vars to the yaml template mainly for documentation purposes (they are set to  default values, so they should have no effect).
This commit also enables some extra feature flags, which are often useful and don't have any negative side effects (s3 grade downloads, third party auth...).
=> Update ansible vars and enable some features.

README.md, instance/models/openedx_appserver.py, instance/templates/instance/ansible/vars.yml, instance/tests/models/test_openedx_appserver.py, opencraft/settings.py
When external SMTP host is defined in settings, populate `POSTFIX_QUEUE_*` ansible vars when  provisioning app servers.
In addition to merely passing the SMTP server settings to postfix, we also set it up to rewrite the sender address to use a fixed domain defined in the settings, that has been pre-validated and authorized as
a sending domain in AuthSMTP.
The local part of the rewritten address (part before @) is the instance domain, so the rewritten From address looks something like:
```
pr123.opencraft.hosting@opencraft.hosting
```
or when using external LMS domain:
```
courses.mydomain.com@opencraft.hosting
```
The original sender address is copied into the `Reply-To` header.
**Testing**
Add the following settings to your `.env` file (replace username and password with valid values): …
=> Set ansible variables for postfix_queue role.

opencraft/settings.py, requirements.txt
Child processes managed by honcho (web, websocket, worker, periodic) were all logging to the same (log/main.log) file using `logging.handlers.RotatingFileHandler`, which does not work correctly when shared by multiple processes.
We use the `HONCHO_PROCESS_NAME` environment variable exposed by honcho to subprocess environments to log output of each process to its own file:
log/im.web.1.log
log/im.web.2.log
log/im.websocket.1.log
...
There is also `log/im.main.log` which is used to log output from the main (parent) honcho process.
*Testing*
1. Checkout this PR and do `pip install -r requirements.txt`.
2. Remove existing main.log files from the log folder: `rm log/main.log*`. The log folder should now be empty.
3. Start the IM: `make rundev`.
4. Look at the `log/` folder which should now …
=> Make each child process log to its own file

opencraft/settings.py
The toolbar mostly disables itself when Django is not in debugging mode, but it still leaks some memory in that case.  In particular, the LoggingCollector collects all log messages in memory unconditionally, leading to a small but continuous memory leak.  The debug_toolbar app is also installed on all Huey workers, where it is essentially useless even when in debug mode.
=> Only install Django Debug Toolbar when in debugging mode.

instance/models/openedx_appserver.py, instance/templates/instance/ansible/lms_users.yml, instance/tests/integration/base.py, instance/tests/integration/factories/instance.py, instance/tests/integration/integration_instance.py, instance/tests/models/test_openedx_appserver.py
Make use of the user management playbook updated in edx/configuration#3274 and edx/edx-platform#13124.
From the Django shell of an instance manager installation, run these commands (replacing the subdomain and the user name with appropriate values):
```
instance = production_instance_factory(
sub_domain='user-creation-test',
edx_platform_repository_url='https://github.com/edx/edx-platform.git',
configuration_source_repo_url='https://github.com/edx/configuration.git',
configuration_version='master',
openedx_release='master',
)
instance.lms_users.add(User.objects.get(username='some_existing_user'))
instance.spawn_appserver()
```
This will deploy a new instance and create a user on it.  Test that the user can log into the LMS and …
=> Use new version of the user management playbook.

instance/tests/integration/factories/instance.py
This configures the integration tests to use the current Eucalyptus release candidate instead of the Cypress release.
For edx-platform and configuration, custom branches are used with some extra commits on top of the release candidate:
* [Additional commits for configuration](https://github.com/edx/configuration/compare/open-release/eucalyptus.1rc2...open-craft:integration)
* [Additional commits for edx-platform](https://github.com/edx/edx-platform/compare/open-release/eucalyptus.1rc2...open-craft:integration)
Manual testing isn't necessary for this PR; all we need is the integration tests pass.
=> Configure integration tests to use the Eucalyptus release candidate.

circle.yml, instance/models/mixins/openedx_storage.py, instance/templates/instance/ansible/swift.yml, instance/templates/instance/ansible/vars.yml
_PR edits by @haikuginger_
We found that we weren't providing sufficient information to fully enable Swift support for OpenCraft IM instances. This PR updates our logic and playbooks to pass necessary information through appropriately. This code is deployed on our [staging instance manager.](https://stage.console.opencraft.com)
**Dependencies**: https://github.com/open-craft/configuration/commit/33a085b9d5fbcebc560e3ce5c4062f2f7a87b3e2
1. Deploy a new instance on Stage IM; be sure to provide necessary OpenStack settings during initialization.
2. Start a new appserver for that instance.
3. Test that instructor report CSVs can be created and downloaded on that appserver.
**Reviewers**
=> Enable full Swift support for OpenCraft IM instances

README.md, instance/factories.py, instance/tests/test_factories.py, opencraft/settings.py
Currently, we only have one setting `OPENEDX_RELEASE_STABLE_REF` to set the stable release ref used by production instances.  This setting is used as `openedx_release` and `configuration_version` for production instances, which means it needs to be a valid ref for edx-platform, configuration, notifier, certs, forum, xqueue and possibly others, so usually only official release names will work.  However, we often want to commit custom changes to the edx-platform and configuration repos.  So far, we managed to do this by having a branch with the same name as an official release tag in the open-craft forks of configuration and edx-platform.  This solution is a confusing hack, so this PR introduces proper settings to set the stable versions of edx-platform and configuration explicitly.  The …
=> Allow to set separate stable versions for edx-platform and configuration.

instance/eucalyptus_upgrade.py
These functions automate selecting the instances that need an upgrade to Eucalyptus, performing the upgrade and cleaning up the settings after the upgrade.
During the upgrade, the oauth2_provider migration is performed by Ansible using the custom code in [this commit](https://github.com/open-craft/configuration/commit/6c2967d3d6e191806d2628dcfa722cbe6e647cb2).
Here are the custom modifications we use on top of the Eucalyptus.1 release:
* https://github.com/edx/configuration/compare/open-release/eucalyptus.1...open-craft:opencraft-release/eucalyptus.1
* https://github.com/edx/edx-platform/compare/open-release/eucalyptus.1...open-craft:opencraft-release/eucalyptus.1
I've tested the process for [this instance](https://console.opencraft.com/instance/1190/edx-appserver/316/), and the upgrade …
=> Add helper functions to upgrade production instances to Eucalyptus.

opencraft/logging.py, opencraft/settings.py, opencraft/tests/test_logging.py
Adds `opencraft.logging.GzipRotatingFileHandler`, which gzips the instance manager's rotated log files.
*Testing Instructions*
1. Set `LOGGING_ROTATE_MAX_KBYTES=1` in your local OpenCraft IM .env file - this is to trigger log rotation without needing to generate huge logs.
1. Run `make rundev`, and refresh http://localhost:5000/ several times.
1. Ensure that `.gz` log files are created in under `logs/`
1. Ensure that you can `gunzip` and read them.
=> Compress application log files

instance/templates/instance/ansible/vars.yml
Set the Insights and Analytics API versions to `openedx_release`.  The default value for these versions is `master`, which means that these services won't get pinned to the selected release, but follow master instead.  This is clearly not intended (and probably won't work in many cases).
=> Pin the Insights and Analytics API versions for instances.

instance/templates/instance/ansible/vars.yml, instance/tests/models/test_openedx_appserver.py
Default for the `EDXAPP_YOUTUBE_API_KEY` variable in edx/configuration repository is `"PUT_YOUR_API_KEY_HERE"` rather than empty/null.
Set it to null in default vars to prevent failing YouTube XHR requests when loading course units containing videos in the Studio or LMS.
A valid YouTube API key can still be set via extra settings.
1. Spawn a new VM.
2. SSH into the new VM.
3. Make sure `YOUTUBE_API_KEY` is set to null in `/edx/app/edxapp/lms.auth.json` and `/edx/app/edxapp/cms.auth.json`.
4. In the Studio, open a unit that contains at least one YouTube video.
5. Make sure no error is show.
6. Check the browser console to make sure there are no failed YouTube API XHR requests.
**Reviewers**:
=> Make sure YouTube API key is unset by default.

requirements.txt
This makes sure we get a fix for a race condition that caused the scheduler thread to silently die every now and then, resulting in no periodic tasks being scheduled anymore.
The new version of Huey is installed on stage, and everything looks fine.  For testing, take a look at the stage instance manager, in particular the log files of the periodic scheduler and the workers, to see if you notice any issues.
Huey releases don't include any release notes, so I went through all commits between the 1.1.2 and 1.2.1 releases to check for backwards-incompatible changes.  There were a few, but none that would affect us.
=> Upgrade Huey to the latest release.

requirements.txt
Upstream already merged the fix and released a new version.
=> Use the new Huey release that includes the fix.

Makefile, README.md, bin/integration-cleanup, circle.yml, instance/models/openedx_appserver.py, instance/tests/integration/integration_instance.py
This PR implements [OC-1590](https://tasks.opencraft.com/browse/OC-1590).
A new make target `integration_test_cleanup` is added, which is called after tests (failure or not) run on CircleCI via the `post` test hook.
The script (`bin/integration-cleanup`) is fed the environment variables placed by CircleCI into `.env.integration` by `honcho`. It queries nova for the list of active instances and filters out anything instances not using the `circleci` keypair. From there, new instances are filtered out by a configurable time threshold.
The time threshold is in seconds and can be overridden by supplying a `INSTANCE_AGE_THRESHOLD` variable to the `.env.integration` environment through CircleCI if we choose to do so in the future.
1. Checkout this branch in an …
=> Add integration test post cleanup to run on CircleCI

instance/models/openedx_instance.py, instance/serializers/openedx_instance.py, instance/static/html/instance/index.html, instance/tasks.py, instance/tests/api/test_openedx_instance.py, instance/tests/fixtures/api/instance_detail.json, instance/tests/fixtures/api/instances_list.json, instance/tests/models/test_openedx_instance.py, instance/tests/test_tasks.py, instance/tests/test_utils.py, instance/utils.py, pr_watch/github.py, pr_watch/tests/test_github.py
This PR adds a task to the scheduler which runs every day and (1) shuts down instances whose PRs were merged (more than) 7 days ago and (2) terminates app servers that were created (more than) two days prior to the active app server of the parent instance. It also makes sure that shut-down instances are hidden from the GUI.
cf. [OC-1998](https://tasks.opencraft.com/browse/OC-1998)
1. Create an instance that is not associated with a PR:
* Run `make shell`.
* Create instance via:
```python
from instance.factories import instance_factory
regular_instance = instance_factory(name="Regular instance, no PR", sub_domain="regular-instance-zohoRek6")
```
* Spawn four app servers for the instance (to speed this up you can use separate terminal windows):
```python …
```
=> Add task for cleaning up VMs

instance/management/commands/activity_csv.py, instance/tests/integration/integration_instance.py
The output of the command now looks like this:
```
"Appserver IP","Internal LMS Domain","Name","Contact Email","Unique Hits","Total Users","Total Courses","Age (Days)"
"213.32.77.49","test.example.com","This, name, ""is, crazy""","x@bdero.me","9","6","1",0
```
Note that it lists the "Internal DNS Domain" and the "Name" of the instance reference. The email is taken from the beta test user's OCIM account email. If there is no "Beta test application" associated with the instance, "N/A" is placed in the email field instead.
FYI @antoviaque, can you take a look to see if this is the appropriate behavior for the email?
**JIRA tickets**: Improves output of [OC-1999](https://tasks.opencraft.com/browse/OC-1999).
Get OCIM setup to manage at least one instance ***with a …
=> Add domain/name to CSV and use betatest user email

debian_packages.lst
Because otherwise you can't run `manage.py dbshell`.
=> Add postgresql-client

instance/tests/integration/integration_instance.py, registration/provision.py, registration/tests/browser/browser_login.py, registration/tests/test_views.py
This pull request adds tests to verify that, when provisioning an instance with non-ephemeral databases, the expected MySQL and Mongo databases are correctly created. 
1. Read code.
2. Run tests.
1. We were hoping to do more than this for this particular task, but I ran into some confusing Mongo behavior that took some time to figure out, and didn't have time to research what other tests might be useful in the context of this task.
**Reviewers**
=> Integration test improvements

instance/api/openedx_appserver.py, instance/models/load_balancer.py, instance/models/openedx_instance.py, instance/tasks.py, instance/tests/api/test_openedx_appserver.py
This PR includes three fixes:
1. Don't include appservers that have been turned down in the LB configuration.  This has caused `None` appearing as an IP address in the configuration, resulting in haproxy refusing to reload the config.
2. Convert all domain names to lower case for the LB configuration.  I've already manually patched this up on the LB server, but we should do it in the IM as well.  Actually, all domain names should be converted to lower case when entered, and only stored in lower case, but this fix makes sure we at least never send upper-case names to the load balancer.
3. Add a new Huey task for activating an appserver.  This takes much longer than it used to, since it now has to run a playbook to reconfigure the LB server, so we can't do it as part of a normal request …
=> Fixes for load balancer issues

instance/admin.py, instance/migrations/0065_create_description.py, instance/migrations/0066_populate_name.py, instance/migrations/0067_remove_blank_name.py, instance/models/database_server.py, instance/tests/models/factories/database_server.py
This PR adds a human readable name and description field to database entries. The name fields are bootstrapped with the hostname field values by the migrations.
1. Checkout master on a local OCIM vagrant instance.
1. Login to the admin panel and create a new MySQL and MongoDB database entry. Fill in whatever hostnames you want, it doesn't have to be real for the purpose of testing this change.
1. Navigate to the [Open edX instance "add" page](https://console.opencraft.com/admin/instance/openedxinstance/add/).
1. Check the `Mysql server` and `Mongodb server` dropdowns and confirm that the `hostname` is used as the display for both.
1. Checkout this PR's branch and run `make migrate`.
1. Navigate to the [Open edX instance "add" …
=> Added human readable description and name fields for DBs

debian_packages.lst, instance/admin.py, instance/models/load_balancer.py, instance/models/mixins/load_balanced.py, instance/models/openedx_instance.py, instance/tests/models/test_load_balanced_mixin.py, instance/tests/models/test_load_balancer.py, instance/tests/models/test_openedx_instance.py
This PR addresses the open comments in #154.  See that PR for discussions.
The PR also contains a further fix:
* Install the libffi-dev library, which for some reason is needed to install Ansible version 2.1.2.0 as of today.  (Yesterday it was still possible to install it without that lib being available.)  This lib has already been installed on stage and prod.  See also the mail from Matjaz.
=> Some further load balancer fixes.

Procfile
This PR configures gunicorn to spawn 4 workers in production mode.
=> Use multiple gunicorn workers in production

instance/models/mixins/load_balanced.py, instance/models/openedx_instance.py, instance/tests/models/test_openedx_instance.py
This bug was encountered by @bdero when shutting down unused beta test instances.
The bug occurs when an instance without any active appserver is shut down.  This case triggered a special code path, which was not covered by the tests.  I added a test to cover it.
I also removed the `if` clause that triggered that special code path, since it's not needed anymore in the current version.  (It was needed at some point.)  I leave the test in anyway.
For testing, create an instance, spawn an appserver, and shut the instance down without activating the appserver.
=> Fix bug occurring when shutting down instance with no active appserver.

instance/models/database_server.py, instance/tests/models/test_database_server.py
cf. [OC-2175](https://tasks.opencraft.com/browse/OC-2175)
1. If you don't have default MySQL and MongoDB database server objects in your local installation of OC IM, create them via:
```python
MySQLServer.objects._create_default()
MongoDBServer.objects._create_default()
```
2. Change the `name` field of the default MySQL and MongoDB database servers:
```python
default_mysql_server = MySQLServer.objects.get()
default_mongodb_server = MongoDBServer.objects.get()
default_mysql_server.name = "Default MySQL server"
default_mongodb_server.name = "Default MongoDB server"
default_mysql_server.save()
default_mongodb_server.save()
```
3. Try creating new (sandbox and production) instances on `master`:
```
from instance.factories import instance_factory, …
```
=> Fix database server creation logic

instance/gandi.py, instance/models/mixins/load_balanced.py, instance/tests/api/test_openedx_appserver.py, instance/tests/fake_gandi_client.py, instance/tests/models/test_load_balanced_mixin.py, instance/tests/models/test_openedx_instance.py, instance/tests/test_gandi.py, instance/tests/utils.py, requirements.txt
This PR removes the dependency on the `tldextract` library and uses information from the Gandi API instead to determine the registered domain name.  This is necessary since `tldextract` depends on the Public Suffix List, so it will return incorrect results for `opencraft.hosting`, which is now on the Public Suffix List.
The new version requests the list of all domains registered with the Gandi account when first needed, and builds a dictionary of all zone IDs.  For setting a DNS record, we now pass in the fully qualified domain name and search the dictionary for a matching suffix.  If none is found, we raise an exception, since this means the domain name can't be set using the configured Gandi account.
This PR also introduces a fake implementation of the Gandi API which behaves similar to …
=> Use the Gandi API to determine the registered domain.

instance/models/openedx_instance.py, instance/models/server.py, instance/models/utils.py, instance/tasks.py, instance/tests/api/test_openedx_appserver.py, instance/tests/models/test_log_entry.py, instance/tests/models/test_openedx_instance.py, instance/tests/test_tasks.py, instance/tests/utils.py
Adds `instance.auto_deprovision_monitoring`, and uses it to decide whether to disable New Relic monitoring when terminating an active appserver.
Also improves logging to help diagnose major server events:
* Adds the server ID to all server log messages
* Logs all state transitions
* Logs automated task events `terminate_obsolete_appservers_all_instances` and `shut_down_obsolete_pr_sandboxes`.
1. Run migrations for this branch in your devstack.
1. Create a new instance.  Ensure that the instance's `auto_deprovision_monitoring` flag is set to True by default.
1. Provision a new appserver for that instance.  
1. Ensure that one of the following messages is logged:
* "Skipping monitoring setup," if you don't have a valid `NEWRELIC_ADMIN_USER_API_KEY` key configured. …
=> Deprovision NewRelic monitoring on instance.shut_down, and improve logging

instance/models/openedx_instance.py, instance/tests/models/test_openedx_instance.py
This fixes a small bug in OCIM where instances with only terminated appservers will still show up in the OCIM instance menu if there are any "Errored" appservers associated with the instance.
A simple way to test this is to make it live on OCIM and verify that the [Edraak](https://console.opencraft.com/instance/670/) instance stops showing up on the left menu.
=> Treat Errored appservers the same as ones with ConfigurationFailed when determining if an instance is shut down

circle.yml, instance/models/mixins/database.py, instance/models/mixins/openedx_database.py, instance/models/mixins/storage.py, instance/templates/instance/ansible/mysql.yml, instance/tests/models/test_openedx_database_mixins.py, instance/tests/models/test_openedx_storage_mixins.py
The `programs` app has been added to `open-release/ficus.master`'s [`edx_sandbox.yml`](https://github.com/edx/configuration/blob/open-release/ficus.master/playbooks/edx_sandbox.yml#L49).  To support this role, we need to add the programs database and user, and set the corresponding ansible variables.
1. Create a new instance with settings similar to [ficus-xenial AppServer 7](https://console.opencraft.com/instance/2420/edx-appserver/782/):
```
configuration_source_repo_url:	https://github.com/open-craft/configuration 
configuration_version:	jill/ficus.master
edx_platform_repository_url:	https://github.com/open-craft/edx-platform
edx_platform_commit:	jill/ficus.master
openedx_release:	open-release/ficus.master
configuration_extra_settings: | …
```
=> Adds the programs database and ansible template vars

instance/tests/models/test_openedx_database_mixins.py, instance/tests/utils.py
On top of mocking `provision_rabbitmq`, I also went ahead and removed the `test_rabbitmq_access` test since it has no purpose if the API is mocked. 
1. Checkout this branch
1. Run the [previously failing tests](https://github.com/open-craft/opencraft/pull/152#issuecomment-274225119) to verify that they're passing now:
```
honcho -e .env.test run coverage run --source='.' --omit='*/tests/*' ./manage.py test instance.tests.models.test_openedx_instance.OpenEdXInstanceTestCase.test_spawn_appserver_with_external_databases --noinput
honcho -e .env.test run coverage run --source='.' --omit='*/tests/*' ./manage.py test instance.tests.models.test_openedx_database_mixins.RabbitMQInstanceTestCase --noinput
```
**Reviewers:**
=> Mock interactions with the RabbitMQ API in tests

instance/templates/instance/ansible/vars.yml
This change allows a single user to maintain sessions in Django Admin, LMS, and CMS from different browsers at the same time.
1. Using this branch, spawn a new appserver.
1. Ensure that `PREVENT_CONCURRENT_LOGINS: false` in the generated configuration files.
1. Once the appserver is running, activate it, and ensure that you can maintain a session between two different browsers, using the same username.
1. [By default](http://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/feature_flags/feature_flag_index.html), `PREVENT_CONCURRENT_LOGINS: true` for [security reasons](https://groups.google.com/forum/#!topic/edx-code/kqCS2tuvTk4).  But it's inconvenient for us and our users, and so we're choosing to unset …
=> Sets the feature flag PREVENT_CONCURRENT_LOGINS to false

instance/openstack_utils.py, instance/tests/models/factories/server.py, instance/tests/test_openstack_utils.py
OVH have recently started providing IPV6 addresses along with their IPV4 addresses for new VMs.
ref: http://travaux.ovh.net/?do=details&id=23185
Unfortunately, our logic for determining the public IP of a new VM was too simplistic, and so it broke when this change was rolled out.
This PR updates `openstack_utils.get_server_public_address()` and related tests to:
* Adds an optional `ip_version` parameter, default `4`.
* Returns the first address found which matches the requested `ip_version`.
*Reviewer*
=> Return IPV4 openstack VM addresses

opencraft/settings.py
This pull request ensures that appservers are members of a security group that allow ICMP ingress on IPv6 and IPv4. This is useful as a diagnostic measure, as some health checks require ICMP pings.
1. In a development environment, ensure that `OPENEDX_APPSERVER_SECURITY_GROUP_NAME` points to a security group that either does not exist, or that does not contain any ICMP rules.
2. In a shell, create a new instance, or retrieve an existing instance, and spawn an appserver on that instance.
3. In your OpenStack control panel, verify that the security group pointed to by `OPENEDX_APPSERVER_SECURITY_GROUP_NAME` contains the existing rules, as well as allowing inbound ICMP requests on IPv4 and IPv6.
=> Add ICMP ingress for IPv4 and IPv6

Makefile, Procfile, Procfile.dev, README.md, instance/tasks.py, opencraft/settings.py
In order to be able to run bulk deployments of appservers from the Django shell without congesting the Huey queue for periodic tasks and deployments triggered from the UI, this PR introduces a separate Huey queue for tasks started from the Django shell.  This makes it possible to redeploy instances in bulk using simple loops in the shell.
Eventually we would like to be able to trigger bulk deployments from the GUI.  Currently, the Django integration of Huey only supports a single queue to be configured per process, but it would be rather easy to change this.
To be able to mark the instances that failed or succeeded, the `spawn_appserver()` task got additional arguments for tags to apply in either case.
With these small changes applied, the redeployment of all instances tagged by `tag` …
=> Facilitate bulk redeployments from the Django shell.

instance/models/mixins/openedx_database.py, instance/templates/instance/ansible/mysql.yml, instance/tests/models/test_openedx_database_mixins.py
Configures notifier to use MySQL database (and creates it if it doesn't already exist).
Notifier uses a local sqlite database by default to be able to benefit from https://github.com/edx/notifier/pull/43.
1. Checkout this branch and start deploying a new instance.
2. Verify that the `notifier` database is created and that these ansible variables are correctly set:
```
NOTIFIER_DATABASE_ENGINE
NOTIFIER_DATABASE_NAME
NOTIFIER_DATABASE_USER
NOTIFIER_DATABASE_PASSWORD
NOTIFIER_DATABASE_HOST
NOTIFIER_DATABASE_PORT
```
Alternatively wait for me to deploy a sandbox that combines https://github.com/edx/configuration/pull/3695,  https://github.com/edx/notifier/pull/42, and https://github.com/edx/notifier/pull/43.
**Reviewers**:
=> Configure notifier database.

instance/templates/instance/ansible/vars.yml, opencraft/settings.py
This was only required for the Eucalyptus release to include [this commit](https://github.com/open-craft/xqueue/commit/7fbb72461b2f9c88f787ddc5ca51dda855735dd4).  Since this is included in the upstream Ficus release, we don't need to pin this anymore.
=> Remove XQueue version pinning.

requirements.txt
Cf https://github.com/open-craft/opencraft/blob/master/requirements.txt#L18
@bradenmacdonald FYI since you are the backup reviewer this week, want to have a look? Note that I haven't tested this, only bumped the version number to get the PR started.
FYI Django 1.11 has also just been released, so we will also need to create a task to upgrade it. https://docs.djangoproject.com/en/1.11/releases/1.11/
=> Security update - Django 1.10.7

instance/templates/instance/haproxy/openedx.conf
This allows passing OAuth bearer tokens to API endpoints via HAProxy.  The API endpoints are not protected by HTTP basic auth, so we don't need the basic auth credentials for these requests.
It's easiest to test this on existing instances to save the time of deploying a new one.  I suggest testing this on stage.
1. Reconfigure the load balancer from the Django shell:
lb = LoadBalancingServer.objects.get(accepts_new_backends=True)
lb.reconfigure()
1. Verify that instances can still be accessed via HAProxy (i.e. by just navigating to the main URL in the browser).  This verifies that the Authorization header is still added in this case.
1. Log in as the staff user on some test instance, navigate to `/admin/oauth2/client` on tha instance and create a new OAuth client.  For the required fields …
=> Make HAProxy only add the Authorization header if it is not present yet.

bin/bootstrap
See this issue for more information: https://github.com/pypa/setuptools/issues/951
To test this, checkout this branch and run `vagrant provision` to make sure the pip dependencies are installed without throwing a `FileNotFoundError`.
CC @itsjeyd @bradenmacdonald
=> Install setuptools to 32 to fix deployment failing

README.md
Explain that in production `archive()` should be used instead of `destroy()`.
=> Mention archive() method in README.

instance/tests/integration/factories/instance.py, opencraft/settings.py
The `opencraft-release/ficus.3` branch includes a fix for the mathplotlib bug which prevents instances from building successfully.
/cc @haikuginger
=> Update integration tests to use ficus.3.

deploy/requirements.yml, opencraft/wsgi.py, requirements.txt
Since we will start serving static files through NGINX, we can drop dj-static.
I'm still working on this, just sending the PR upfront in case there is anything that should be considered too.
This change is tied to open-craft/ansible-opencraft#7
When we are good to go, I believe we should merge `ansible-opencraft` PR
and then update this PR to make `deploy/requirements.yml` point to the correct version of `ansible-opencraft`.
=> Remove dj-static

instance/templates/instance/ansible/vars.yml
This PR adds additional variables that were missed in the first pass of #202.
Testing: On the `courses.pearsonx.com` instance (where these variables had to be set manually), verify that when selecting the edX Demo Course and the Verified course mode, you're successfully redirected to the ecommerce stack.
=> Add ecommerce URL variables

bin/bootstrap
This reverts commit 694c7cc15bd6fd943bbd4b10ea854141ffbd5b65.
This should be merged when the source issue discussed in https://github.com/open-craft/opencraft/pull/205 is resolved.
=> Revert "Pin setuptools to 32 as a bug workaround."

instance/gandi.py, instance/tests/test_gandi.py
This small PR improved the domain matching error message to include the actual domain name. This makes it easy to see specifically which domains are not in the record list whenever this exception is thrown.
CC @smarnach
=> Improve Gandi domain error message

instance/tasks.py, instance/tests/test_tasks.py
... when cleaning up obsolete instances.
This is to avoid unnecessarily creating and activating new versions of the Gandi zone file that we are using for opencraft.hosting.
Cf. [OC-2954](https://tasks.opencraft.com/browse/OC-2954)
**Reviewers**
=> Don't shut down instances more than once

pr_watch/github.py
... to satisfy https://developer.github.com/v3/#user-agent-required.
Also add some logging to make debugging easier in the future.
Follows up on https://github.com/open-craft/opencraft/pull/216.
The need for this change surfaced while deploying changes for [OC-2954](https://tasks.opencraft.com/browse/OC-2954) (https://github.com/open-craft/opencraft/pull/217) to stage. (Changes from https://github.com/open-craft/opencraft/pull/216) hadn't been deployed, and so were included in the deployment for OC-2954.) After restarting the workers we were getting a bunch of errors that looked like this:
```
10/Aug/2017 07:37:42 |    ERROR | process=29752 | huey.consumer.Worker      | Unhandled exception in worker thread
Traceback (most recent call last):
File …
```
=> Include User-Agent header in requests to GitHub API

Makefile, deploy/README.md, deploy/requirements.txt
This allows to configure the number of workers in the environment, so we can set fixed values for them that don't need to be passed on the `make run` command line.
This PR also adds documentation how to diff the `.env` file on the live server against the version currently in Ansible.  This is useful to make sure that any updates we manually applied to the live server are also in Ansible.  I used this technique to make update the config in Ansible, see open-craft/deployment-secrets-services#26.
The `--start-at-task` flag to `ansible-playbook` is broken in the Ansible version we have been using, so I also updated the Ansible version.  The new version seems to work without any problems.
=> Allow to set WORKERS(_LOW_PRIORITY)? from environment.

instance/templates/instance/ansible/vars.yml
These are used to determine the "issuer" fields for OAuth and JWT authentication, and the "audience" field for JWT.
Noticed this error reported by the Ginkgo Insights deployments listed below, when trying to authenticate via their Gingko edxapp instances: 
```
Sep 24 11:37:24 ip-172-31-93-161 [service_variant=insights][django.request][env:no_env] ERROR [ip-172-31-93-161  2474] [exception.py:135] - Internal Server Error: /complete/edx-oidc/
Traceback (most recent call last):
File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
response = get_response(request)
File "/edx/app/insights/venvs/insights/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
response = …
```
=> Adds variables required for OAuth2 and JWT

instance/templates/instance/ansible/lms_users.yml, instance/tests/integration/integration_instance.py
Fixes LMS superuser creation by setting the `EDXAPP_SETTINGS` ansible variable, which must now be overridden when running the [edx-east/manage_edxapp_users_and_groups.yml](https://github.com/edx/configuration/blob/master/playbooks/edx-east/manage_edxapp_users_and_groups.yml#L80) playbook.
LMS user creation stopped when we shifted to `open-release/ginkgo.1` as our base stable branch, which caused new beta appservers to fail on creation.
**JIRA tickets**: OC-3150
1. Ensure your .env file contains:
```
DEFAULT_CONFIGURATION_REPO_URL='https://github.com/open-craft/configuration' 
DEFAULT_OPENEDX_RELEASE='open-release/ginkgo.1'
DEFAULT_CONFIGURATION_VERSION='opencraft-release/ginkgo.1'
OPENEDX_RELEASE_STABLE_REF='open-release/ginkgo.1' …
```
=> Fix lms user creation

instance/api/instance.py, instance/models/instance.py, instance/serializers/instance.py, instance/static/html/instance/details.html, instance/static/js/src/instance.js, instance/tests/api/test_instance.py
This pull request references OC-2877. It removes log entry information from the `instance/:id` endpoint and moves it into a new `instance/:id/logs` endpoint instead. 
This means that log data will not be loaded by default when viewing an instance detail, thus saving unnecessary data being streamed to the frontend. When a user clicks on the "Logs" tab, the data is loaded at that point from the new endpoint.
**To Test:**
* Set up an OCIM and create some instances
* Verify that all tabs except Logs work as normal
* Click on Logs tab with a browser inspector open to verify that a new network request is made, and that the log data is loaded and displayed in the Logs tab (and a "Loading logs" placeholder message is there until log data arrives).
* See also the API end point for verification …
=> Move instance log data to new API endpoint

opencraft/settings.py, opencraft/urls.py
There's already code to add django-debug-toolbar when `DEBUG==True`, but it's not working (it doesn't show).
- I had to add the setting `SHOW_TOOLBAR_CALLBACK` to force always showing it.
- Then it failed because the URL isn't added, so I added it to urls.py too. Tip from https://github.com/django-debug-toolbar/django-debug-toolbar/issues/529
It's disabled by default, and you can enable it by changing one setting as explained in settings.py
=> Enable debug toolbar in DEBUG at all pages including admin and api

instance/templates/instance/ansible/swift.yml, instance/templates/instance/ansible/vars.yml
The Ansible variable templates get rendered by two different template engines with similar syntax.  First the whole file is rendered by the Django template engine before being passed on to Ansible.  Ansible then renders the values with the Jinja2 template engine.  The syntax for variable references in both template engines is identical, so all variable references that are meant to be rendered by Jinja2 are already rendered by Django.  Django ignores unknown variables and replaces them by empty strings.
This fix protects all variables that should actually be rendered by Jinja2 with verbatim blocks.
=> Protect references to Ansible variables from the Django template engine.

instance/templates/instance/ansible/mongo.yml
Because we're currently using localhost ElasticSearch for Ocim instances, we need to rebuild the forum index when creating new appservers.
This setting can be removed when we have shared, persistent ElasticSearch storage, but will not harm anything by remaining.
**JIRA tickets**: OC-3205
**Sandbox URL**:
LMS: https://oc3205.sandbox.stage.opencraft.hosting
CMS: https://studio-oc3205.sandbox.stage.opencraft.hosting
1. Spawn a new appserver with `use_ephemeral_storage: False`.
1. Ensure that the `[forum : rebuild elasticsearch indexes]` is run (not skipped).
To verify that the rebuilt index task actually does the job (see [DemoX course on sandbox instance](https://oc3205.sandbox.stage.opencraft.hosting/courses/course-v1:edX+DemoX+Demo_Course/ …
=> Rebuild the forum index from persistent mongo storage

instance/templates/instance/ansible/vars.yml
We've noted some memory issues that can be solved by reducing the number of LMS/CMS workers.
**Sandbox URL**: TBD - sandbox is being provisioned.
1. See stage for a new instance (TBD).
1. See its configuration setup and make sure you see:
```yaml
EDXAPP_WORKERS:
lms: 3
cms: 2
```
=> To deal with memory issues, default to less edxapp workers.

instance/admin.py, instance/tests/test_widgets.py, instance/widgets.py
This pull request fixes a double quotes json bug that occurs when adding a new application instance on OCIM. This fixes an issue with deserializing the django_extensions library's JSONField where invalid json would be created.
**JIRA tickets**: OC-3036
**Sandbox URL**: TBD - sandbox is being provisioned.
**Merge deadline**: "None" 
1. Open up a running version of OCIM with this pull request. 
2. Go to the django admin.
3. Attempt to add a new "Open edX Instances"
4. Scrolling down "Openstack server flavor" and "Openstack server base image" contain valid json where all string values are encased in double quotes rather than single quotes.
5. Put in valid values for all required fields.
6. Save. There should be no exceptions that occur. …
=> [OC-3036] Fixed double quotes issue in OCIM's JSON fields

instance/models/load_balancer.py, instance/tasks.py
This PR makes the version updates for LB reconfigurations atomic.
The most important change is to refresh the LB object from the database after the LB reconfiguration.  The current version of the code still has the old version of `configuration_version` stored on `self`, so if `configuration_version` was increased by a different process while the reconfiguration was running this increase will simply be overwritten by the final `self.save()` call.
=> Fix locking around the LB configuration version updates.

instance/models/server.py, instance/tests/models/test_server.py
This fixes the message logged when VM creation times out.
The timeout counter was used to generate the error message and would always read 0, since it was decremented until 0 to check for the timeout.
**JIRA tickets**: OC-3354
1. I've added a unit test to check this error message, not sure if there's a way to trigger a build to timeout.
**Reviewers**
=> Fix error message when VM creation times out

instance/static/js/src/instance.js, instance/tests/js/instance_app_spec.js
This fixes a bug where the button was left disabled.
1. I suggest you apply this patch to disable the spawning of appservers and to make testing faster 
```
modified   instance/models/openedx_instance.py
@@ -172,7 +172,7 @@ class OpenEdXInstance(DomainNameInstance, LoadBalancedInstance, OpenEdXAppConfig
Returns the ID of the new AppServer on success or None on failure.
"""
-        if not self.load_balancing_server:
+        if False and not self.load_balancing_server:
self.load_balancing_server = LoadBalancingServer.objects.select_random()
self.save()
self.reconfigure_load_balancer()
@@ -180,10 +180,11 @@ class OpenEdXInstance(DomainNameInstance, LoadBalancedInstance, OpenEdXAppConfig
-        self.set_dns_records()
+        if False:
+            self.set_dns_records()
-        if not …
```
=> Fix the "Launch new app server" button

pr_watch/tasks.py, pr_watch/tests/test_tasks.py
Small fix to honour the `WatchedFork.enabled` attribute.
=> Don't watch forks marked as disabled

instance/models/server.py, instance/tests/models/test_openedx_storage_mixins.py
While testing the new region in OVH, we're having to use a new project with new creds that Ocim uses for both spawning new appservers and getting appserver information for currently running appservers. Since the currently running appservers are in the old region and project that require a different set of credentials, we get errors when attempting to access their detail view. This is a tiny patch to catch that error and log it to handle the case gracefully, until we improve Ocim with the ability to handle multi-OpenStack-project deployments.
*Testing instructions:*
1. On stage, don't be on this branch, and make sure the `.env` file contains the new OpenStack credentials for all `OPENSTACK_X` variables (i.e. user/pass/tenant/region).
2. See an instance that is setup to use the new region …
=> Catch `EndpointNotFound` error for getting server status update.

instance/models/mixins/openedx_config.py
Steps taken to alleviate memory-related performance issues and errors occurring since the Ginkgo upgrade.
Note that 80000 is an arbitrary number that should restart workers every few days. With 3 LMS this gives 240k requests, +10% static 260k, this means that only after 260k requests will a worker restart, this can be 6 days if 40k requests/day, 12 days if 20k requests/day, etc.
An alternative solution would be to do this change in the `configuration` branch instead of Ocim.
- deploy an appserver in an instance that has already appservers 
- check that the new setting has been correctly applied to the new appserver (but not changed in the old ones)
=> Add setting to avoid memory leak, and add comment about number of workers

opencraft/settings.py
Enable sending e-mail to ADMINS on failure. This includes exceptions in huey tasks.
Done as part of https://tasks.opencraft.com/browse/OC-2044
**JIRA tickets**: None
**Discussions**: None
**Screenshots**: None
**Sandbox URL**: None
1. Add ADMINS to settings.py, e.g. `ADMINS=[("You","aaaaa@example.com")]`, or the equivalent syntax in `.env` (with lists instead of tuples, and everything surrounded by single quotes)
2. Add to your `.env`:
```
DEBUG=false
ADMINS='["something@example.com"]'
ALLOWED_HOSTS='["localhost"]'
SERVER_EMAIL='something@example.com'
DEFAULT_FROM_EMAIL='something@example.com'
EMAIL_HOST='localhost'
``` 
3. (You don't really need a mail server because Django will show the message in the console)
4. …
=> Mail admins when exceptions occur

pr_watch/github.py, pr_watch/tests/test_github.py
When invoked with an empty username list, the function would construct the Github API query as `is:open is:pr  repo:edx/edx-platform`, which returns all PRs from the requested fork, instead of no PRs.
1. Without this patch, start the django shell. Invoke `pr_watch.github.get_pr_list_from_usernames([], 'edx/edx-platform')` and observe it fetches a page of *all* PRs from the Github API.
1. Install the patch & restart the shell.
1. Invoke the function again, verify it returns an empty list.
**Reviewers**:
- @pomegranited
=> Fix an edge case in get_pr_list_from_usernames.

Makefile, README.md, bin/bootstrap, bin/run-circleci-tests, circle.yml
The `make all` target had rundev on a new line, which attempts to run it as a command, rather than making the 'all' target dependent on the 'rundev' target.
**Console Logs**:
Before fix:
```
$ make
rundev
/bin/bash: rundev: command not found
Makefile:40: recipe for target 'all' failed
make: *** [all] Error 127
```
1. Run `make all` and ensure the `run.dev` target is run, instead of an error.
=> Update make targets to fit better with what's currently in Accounting

instance/models/mixins/openedx_config.py
Switch to using ``django.contrib.sessions.backends.cached_db``  for sessions so redeploying an Instance doesn't lead to expired sessions. 
1. Deploy an instance using an Ocim with this path
2. Sessions running on that AppServer for that instance should persist as a new AppServer is launched, or if the running AppServer is restarted.
=> Use `cached_db` session engine to persist sessions

backup_swift/tasks.py, backup_swift/tests.py, instance/openstack_utils.py, instance/tests/test_openstack_utils.py
This PR introduces enhanced logging of errors on the failure of swift container download.
**JIRA tickets**: This PR is a first step in investigation for the issue in [OC-3611](https://tasks.opencraft.com/browse/OC-3611). Another PR might be needed, once the source of the issue is found.
**Screenshots**: None
**Sandbox URL**: None
**Merge deadline**: If possible, very soon so that further investigation of issue from [OC-3611](https://tasks.opencraft.com/browse/OC-3611) can be made.
1. Run the existing tests.
1. It would be great to test it with the connection to OpenStack configured - I haven't done it yet as I don't have one.
**Reviewers**
CC: @smarnach 
Squashed and rebased from …
=> Log more information on the failure of swift container download.

README.md
In #260 we switched from the bootstrap script to Ansible for provisioning Vagrant. This relies on the Ansible roles being present in the ``deploy/roles`` directory, however that is not the case by default. 
This pull request updates the readme to include instructions to install the Ansible roles for deployment and provisioning Vagrant.
**Reviewers**
=> Update readme to add missing Ansible provision step

instance/models/mixins/openedx_database.py, instance/tests/models/test_openedx_database_mixins.py
The Ansible variables for ecommerce database configuration have changed such that Ocim can no longer deploy an instance based on the standard edx/configuration repo. 
This change adds variables to support the new variables for configuring ecommerce. 
**Sandboxes**:
`edx:master`:
* LMS: https://ocpr268.sandbox.stage.opencraft.hosting/
* Studio: https://studio-ocpr268.sandbox.stage.opencraft.hosting/
* Ecommerce: https://ecommerce-ocpr268.sandbox.stage.opencraft.hosting/
`open-craft:opencraft-release/ginkgo.1`
* LMS: https://ocpr268-ginkgo.sandbox.stage.opencraft.hosting/
* Studio: https://studio-ocpr268-ginkgo.sandbox.stage.opencraft.hosting/
* Ecommerce: https://ecommerce-ocpr268-ginkgo.sandbox.stage.opencraft.hosting/
1. Set up an Ocim …
=> Update ecommerce database configuration

instance/models/mixins/openedx_config.py
The setting change might have had unforeseen consequences and is being reverted until its impact can be better analysed.
=> Revert #258 use `cached_db` session engine to persist sessions

README.md
This pull request updates the readme to provide more context for running bulk redeployments and the issues it can cause. It recommends using the low priority worker queue and has instructions for using that. 
**Reviewers**
=> Improve documentation for bulk redeployment command

instance/templates/instance/haproxy/openedx.conf
Also use /heartbeat for health checking; the current version only verifies the
server accepts TCP connections.
I'm going to try and expedite this fix by @smarnach on [OC-3169](https://tasks.opencraft.com/browse/OC-3169) through this week. See the ticket for details. In a nutshell, our method of populating the sticky map (hashing by the session cookie) broke for Ginkgo, which causes requests from the same client/session to be uniformly distributed between all servers in the backend. Of course, this causes all kinds of problems for any instance with more than one appserver, including:
* Static asset 404s if, for any reason, static assets happen to not be hashed the same during collection between different appservers (we saw this happen on an ecommerce deployment recently).
* Issues starting …
=> Fix LB stickiness by inserting a dedicated cookie.

instance/templates/instance/haproxy/openedx.conf
The health checks have proven problematic, since they will completely disable a backend even if we only have intermittent connection failures to MongoDB.  Since the health cheks are only useful in a multi-appserver setting we completely disable them for now, and plan to implement a fix for enabling them only for multi-appserver instances next week.
=> Completely disable health checks in the haproxy config.

circle.yml
Updates the version of python used by CircleCI to address issues noticed with the gandi client library.
**JIRA issues**
OC-3949
Since this change only affects the circle.yml file used by CircleCI, passing tests should be enough to verify it.
**Reviewer**
=> Bump python version used by CircleCI

instance/models/openedx_instance.py, instance/templates/instance/haproxy/openedx.conf
We have disabled the load balancer health checks in #277 since they proved to cause more harm than good for single-VM instances.  We still need them for multi-VM instances, though – otherwise the load balancer would keep sending traffic to a server that is down, so this PR re-enables them if more than one app server is active.
For testing, activate two app servers for an instance and verify that health checks in the generated config are only configured for the instance with two active app servers.  Log into the instance with two active app servers and check the stickiness cookie to learn what app server you are routed to.  Then stop the LMS on that app server, and verify that you can still successfully access the instance.
=> Enable LB health checks if more than one app server is active.

deploy/vagrant_vars.yml
This disables installing {{nrsysmond}} when creating the Vagrant build, because the Vagrant build is for development only and we don't want reporting. There's no license key either.
Testing instructions in your Ocim:
1. create a virtualenv and install Ocim's `deploy/requirements.txt`
2. download the roles (`ansible-galaxy install -r requirements.yml -f`)
3. replace the `common-server` role folder with the branch from this PR
3. `vagrant provision`, this will run the ansible script
4. the script should run correctly instead of crashing
5. check that the New Relic tasks were skipped, and the agent wasn't installed. You should see this
```
TASK [common-server : Copy security update check script] ***********************
changed: [default]
TASK [common-server : Schedule cron job to track …
```
=> Disable New Relic agent in Vagrant build

instance/models/mixins/openedx_config.py
This PR sets variables which will be used by the task introduced at https://github.com/open-craft/configuration/pull/38
Untested in local because my VirtualBox refuses to work. I'll fix tests here later.
=> Set up a cron job to clear sessions

instance/gandi.py, instance/tests/fake_gandi_client.py, instance/tests/test_gandi.py
Adds catch for Gandi timeouts and tests
JIRA Ticket: OC-4149
=> Add catch for gandi timeouts

.env.test, .prospector/opencraft.yml, Makefile, bin/run-circleci-tests, circle.yml, debian_packages.lst, instance/tests/models/test_openedx_database_mixins.py
Migrating to CircleCI version 2.
JIRA Ticket: OC-4053
Check that tests are passing.
Notes to reviewer:
- Had to upgrade to python version 3.5.4, since 3.5.3 is not in the list of docker images: https://github.com/CircleCI-Public/circleci-dockerfiles/tree/master/python/images.
- Using browsers image, so that it comes with firefox already installed
- Had to add hosts to mysql commands and also update links from localhost to 127.0.0.1, so that mysql connects using tcp (required when using docker images for dbs)
- Added cache for python requirements
Reviewers:
[Sven]
=> Migrate config to CircleCI 2

instance/management/commands/instance_redeploy.py
Adds an option to skip the activation of an appserver after successful instance redeployment. Useful for pre-provisioning instances en masse.
Go on stage, checkout this branch, restart, run the mass redeployment command for a single server (use a tag that selects a single server somehow) with this flag set, and notice the resulting server is not activated, whereas it normally would have been.
=> Add option to skip activation of instance in redeployment.

instance/api/openedx_appserver.py, instance/models/openedx_instance.py, instance/models/server.py, instance/serializers/server.py, instance/tasks.py, instance/tests/api/test_openedx_appserver.py, instance/tests/models/factories/openedx_appserver.py, instance/tests/models/test_openedx_instance.py, instance/tests/test_tasks.py
Added a called to update_status() if an active server was found without IP address. If the IP is still missing after the call, allow the load balancer configuration to fail.
**JIRA tickets**: OC-4205
1. Spawn an appserver. but before making it active, terminate the OpenStack VM server. If we then try to make the appserver active. It should not be allowed to be made active. The VM server should be in the Ready state before making the appserver active.
2. When reconfiguring the loadbalancer, the VM server should have a public IP address, otherwise it will throw an exception. 
**Reviewers**
=> Safer load balancer reconfigurations

README.md, instance/factories.py, instance/models/mixins/openedx_storage.py, instance/models/mixins/storage.py, instance/models/openedx_instance.py, instance/tests/models/factories/openedx_appserver.py, instance/tests/models/test_openedx_storage_mixins.py, instance/tests/test_factories.py, opencraft/settings.py, requirements.txt
Adds s3 as default storage for new instances.
JIRA Ticket: OC-3841
- Add AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY global credentials to your .env file, this credentials should have permission to create other IAM users.
- Setup an instance on the admin (fill all the required values). When saving the instance the system will use your global credentials to create an IAM user with permissions to create and update the bucket. Verify that the fields "s3_bucket_name", "s3_access_key" and "s3_secret_access_key" have been populated.
- Launch a new appserver from the interface. Check that a bucket was created with the instance domain name.
Permissions needed for the AWS Global account are:
iam:PutUserPolicy
iam:CreateUser
iam:CreateAccessKey
iam:DeleteUser …
=> S3 as default storage

deploy/opencraft.yml, deploy/requirements.yml, deploy/vagrant_vars.yml
Since we install nginx in the common-server role now, the geerlingguy.nginx role is no longer needed.
Further changes in this PR:
* Only install Python 2 if it's not already installed.
* Remove `pmbauer.tarsnap` from the playbook, since the role is a dependency of the `opencraft` role anyway.
* Consolidate role versions with the version in ansible-playbooks.
* Do not install Certbot on the Vagrant installation.
I tested these change on Vagrant only, by building a new Vagrant VM from scratch.
=> Remove the geerlingguy.nginx role.

deploy/opencraft.yml
The node-exporter role needs the SSL certificates already in place, so we can only run it after the opencraft role.
=> Run node-exporter role after opencraft-role.

instance/ansible.py
Follow-up to #300.
The [Ansible configuration in edx/configuration disables SSH host key checking](https://github.com/edx/configuration/blob/837308626ff278a39303f8b987313d7e38c36ef3/playbooks/ansible.cfg#L8).  The first time a playbook runs for a given IP, SSH will accept the host key unconditionally 
and add it to `~/.ssh/known_hosts`.  The `ansible.cfg` in ansible-playbooks, by contrast, does not disable host key checking.  Most of the time this isn't a problem, since by the time the playbook runs the host key is already in `known_hosts`.  If we by chance get assigned an IP that we already had for an earlier app server, we will have a different host key in `known_hosts`.  Ansible will ignore the discrepancy for the upstream playbook, since host key checking is disabled, but SSH won't …
=> Disable SSH host key checking for Ansible.

instance/management/commands/instance_redeploy.py, instance/tests/management/test_instance_redeploy.py
We will be running a mass redeployment, and want to make sure to only include those successfully provisioned. This PR inverts the logic a bit to `filter` out those not archived rather than call `exclude` for those that are, and then also to filter those that are only successfully provisioned.
Testing not explicitly needed due to the simplicity of the change and because the tests should build plenty of confidence. And because we'll be running the command right now anyway.
=> Get only archived and successfully deployed instances for redeploy.

opencraft/settings.py
We're getting absolutely spammed with useless DEBUG logs on ELK.
(Note I made this by editing on GitHub and have not tested it just yet).
=> Change from `DEBUG` to `INFO` log level.

instance/tasks.py
Otherwise workers will completely drop the task and the instance redeployment management command will not be able to recognize if an ongoing instance has actually failed, since the ongoing tag will remain.
Test instructions:
Bring this to prod where we're currently facing issues with provisioning S3 on the first try, run the instance redeployment command, and notice that now the low prio workers no longer completely drop all work after failing to provision S3.
=> Catch any exception if an appserver fails to spawn.

instance/models/mixins/storage.py
Currently, it is not possible to save an instance with an empty bucket name since Ocim will try to provision an empty bucket name and fail. This fixes that issue.
=> Fix: don't try to provision a bucket if bucket name is empty

instance/tasks.py, instance/tests/api/test_openedx_appserver.py, instance/tests/test_tasks.py
This PR addresses a bug pointed out in [OC-4205's comment](https://tasks.opencraft.com/browse/OC-4205?focusedCommentId=70999&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-70999)
JIRA tickets: OC-4205
Since the API call [/api/v1/openedx_appserver/] does not call the spawn_appserver without num_count, the way to test it is  probably via the management command instance_redeploy.py It should break on success even if num_attempts >1.
Reviewers
@UmanShahzad
@xitij2000
=> Fixed the logic to prevent multiple instances from being spawned

bin/integration-cleanup, circle.yml
This fixes ~3~ 2 problems when cleaning integrations tests:
1. `nova` not found:
```
Running integration test cleanup script with credentials from environment variables...
bin/integration-cleanup
Querying Nova for list of running integration test instances...
bin/integration-cleanup: line 21: nova: command not found
No active instances returned, nothing to clean up. Quitting.
```
The solution is to run the script inside the virtualenv.
2. The OpenStack region name wasn't specified and `nova` didn't use GRA3. Original vs. fixed behaviour:
```
(venv) circleci@a384d791b3f0:~/project$ export OS_USERNAME=$OPENSTACK_USER
(venv) circleci@a384d791b3f0:~/project$ export OS_PASSWORD=$OPENSTACK_PASSWORD
(venv) circleci@a384d791b3f0:~/project$ export OS_TENANT_NAME=$OPENSTACK_TENANT
(venv) …
```
=> Fix CircleCI cleanup

instance/models/openedx_appserver.py, instance/tests/integration/integration_instance.py, instance/tests/utils.py
There are issues where an appserver is very quickly made active behind the load balancer before it has a steady heartbeat. In that case, HAProxy takes it off the map because it assumes the server is down. Do not put a server in a healthy state on our side unless the heartbeat is functioning.
=> Check that the heartbeat is functioning before activating.

instance/models/openedx_appserver.py, instance/tests/integration/integration_instance.py, instance/tests/utils.py
Reverts open-craft/opencraft#316
I too quickly merged this before testing it on stage. After testing it with https://stage.console.opencraft.com/instance/2110/edx-appserver/611/, the server failed to configure for seemingly a related reason, so I've made this revert PR. Will merge as soon as tests pass and we can try again.
=> Revert "Check that the heartbeat is functioning before activating."

instance/models/mixins/openedx_config.py, instance/tests/models/test_openedx_instance.py
Disables New relic and RabbitMQ depends on: https://github.com/open-craft/configuration/pull/43/
=> Disable New Relic and RabbitMQ by default

circle.yml, instance/models/server.py, instance/tests/models/test_server.py
If there are errors while making the OpenStack delete API call,
mark the instance as 'unknown'. In case the server is not found,
mark it as 'terminated'.
* Launch an AppServer instance and wait till the OpenStack VM is up and running.
* Delete the VM from the OpenStack console bypassing OCIM.
* Try to terminate the VM from OCIM (I called the `terminate()` method on the instance from the shell)
* The OpenStack API should return a 'not found' status and the status of the AppServer should change to `terminated`.
* Launch an AppServer and wait till the OpenStack VM is up and running.
* Change the OpenStack API endpoint to gibberish. (I tested by disconnecting the network on my computer).
* Try to terminate the VM.
* Since the OpenStack API is unreachable, there will be a `NewConnectionError` …
=> Mark an instance as 'terminated' only on successful deletion

instance/models/mixins/openedx_config.py, instance/tests/models/test_openedx_appserver.py
Set the default value of `DISCOVERY_VERSION` to the openedx release
being installed to avoid the master branch of discovery
being used as the default value. The master version of discovery
doesn't work well with other `gingko`-based services.
1. Create an instance with a specific openedx release (for example, `open-release/ginkgo.2`)
1. Spawn an AppServer.
1. Once the AppServer has started spawning, check the configuration value used for `DISCOVERY_VERSION`. This can be checked from the `Configuration` section of the AppServer in the web UI from the value of `DISCOVERY_VERSION` in `Combined ansible vars:`
1. The value should match the openedx release with which the instance was created.
1. Create an instance with a specific openedx release and extra configuration overriding …
=> Set DISCOVERY_VERSION to a correct default value

instance/models/mixins/storage.py
S3 bucket creation is failing due to Amazon's delay on propagating the keys. I increased the retry delay to fix this.
IAM keys were not being saved when s3 bucket creation failed, fixed this too.
=> Fix s3 bucket creation wait more for IAM keys propagation, save IAM keys for instance

instance/models/mixins/openedx_database.py, instance/tests/models/test_openedx_database_mixins.py, instance/tests/test_factories.py, opencraft/settings.py
Allow our production Ginkgo instances to use the performance benefits of mongo replica sets.
**JIRA tickets**: OC-4868
**Dependencies**: https://github.com/open-craft/configuration/pull/51
**Sandbox URL**:
* LMS: https://oc4868.sandbox.stage.opencraft.hosting/
* Studio: https://studio-oc4868.sandbox.stage.opencraft.hosting/
Steps used to create the above sandbox:
1. Configure an MongoDB primary server, with one or more secondaries, and replica set in the Ocim Admin.
1. Use the Ocim shell to create a Ginkgo instance attached to that replicaset, using the configuration version from https://github.com/open-craft/configuration/pull/51.
```python
oc4868 = …
```
=> Support mongo replicasets backported into OpenCraft Ginkgo

README.md
This is to fix a typo in README.md file which leads to a 404 page when trying to access the [playbooks](https://github.com/open-craft/ansible-playbooks) repo.
=> Fix playbooks repo typo in README.md

circle.yml, instance/management/commands/update_metadata.py, instance/models/openedx_appserver.py, instance/models/openedx_instance.py, instance/models/utils.py, instance/tests/management/test_update_metadata.py, instance/tests/models/test_openedx_instance.py, instance/tests/models/test_openedx_storage_mixins.py, instance/tests/models/test_utils.py, instance/tests/utils.py, opencraft/settings.py, requirements.txt
This change will help us store and update instance information in Consul. It introduces a mixin that can be used in any model we desire to add this feature to.
=> Store instance information in Consul

instance/templates/instance/redis/redis.nomad
This adds a simple Redis jobspec, which is virtually identical to the Memcache jobspec.  The main differences are naming and a count of 1 instead of 3 – as discussed on the ticket, we won't be able to use a highly available Redis deployment in this iteration.
This PR is not meant to be merged.  We will add the ability to automatically launch the jobs to Ocim in a future PR, which will likely build on this jobspec, but put it in a Python dictionary rather than a separate file.
I started a job using this spec on the production Nomad cluster to verify the spec.  Given that it is virtually identical to the Memcache spec, I don't think this needs separate end-to-end testing – simply sanity-checking the jobspec should be enough for review.
=> Add example Nomad jobspec for a Redis process.

instance/models/mixins/openedx_config.py, instance/tests/models/test_openedx_instance.py
* Fixes typo from https://github.com/open-craft/opencraft/pull/317
* Adds tests to check for other disabled service settings
**JIRA tickets**: OC-5149
Simulating the effect of this change using this [hawthorn test instance](https://console.opencraft.com/instance/11250/edx-appserver/8178/).
1. Deploy a new appserver using this branch.
1. Ensure that the rabbitmq role is not run.
**Reviewers**
=> Disables RabbitMQ on Ocim instances

instance/models/mixins/openedx_config.py
Sets a `max_requests` limit for the CMS celery workers, which should result in a worker restart frequency of 1-2 days for an average instance.
This change was made in an attempt to relieve memory pressure on existing Ginkgo instances, and to anticipate the CMS worker memory leaks reported for Hawthorn.  cf [openedx-ops post](https://groups.google.com/d/msg/openedx-ops/q-9lZwy-_GM/8X3PIED1AwAJ).
1. Spawn a new appserver using this branch.
1. Note that `EDXAPP_CMS_MAX_REQ: 1000` is present in the configuration, which propagates to the `max_requests` value in `/edx/app/edxapp/cms_gunicorn.py`.
See [hawthorn-beta.opencraft.hosting](https://console.opencraft.com/instance/7850/) for an example.
**Reviewer**
=> [OC-5149] Adjust max requests handled by LMS/CMS gunicorn workers 

instance/models/mixins/openedx_theme.py, instance/tests/models/test_openedx_theme_mixins.py
This PR rebases https://github.com/open-craft/opencraft/pull/289/ on top of the latest changes in the master branch and retains ginkgo-specific changes removed in that PR, for backward compatibility.
=> Ginkgo-compatible simple_theme changes for Hawthorn

instance/tests/management/test_update_metadata.py
JIRA: [OC-4288](https://o/OC-4288)
This is to add the missing `skip_unless_consul_running` that makes the tests fail if the devstack doesn't contain Consul. This is not the ideal solution to continue with, but it's a work around until we have Consul up and running in the devstack.
Thanks @lgp171188 for pointing this out.
=> Add the missing Consul decorator to UpdateMetadataTestCase

instance/models/openedx_instance.py, instance/tests/models/test_openedx_instance.py
This change helps in creating a `/etc/haproxy/backend.map` and a `etc/haproxy/haproxy.cfg`. Both fields are missing and required in the templates we're generating for these files.
=> Add domain and domain slug to Consul Configurations

instance/factories.py, instance/tests/test_factories.py, opencraft/settings.py
Add a new configuration setting `OPENSTACK_PRODUCTION_FLAVOR`. Use it in the `production_instance_factory()` method to specify the
flavor to use for the production instances. Currently, all the
instances use the value of the `OPENSTACK_SANDBOX_FLAVOR` variable
by default. This change will facilitate using different flavors
for production and sandbox instances.
* Deploy the changes in the source branch of this PR.
* Deploy the updated `.env` file from https://github.com/open-craft/ansible-secrets/pull/80 and restart OCIM.
* Create a new production instance and verify that it uses the flavor specified in `OPENSTACK_PRODUCTION_FLAVOR`.
* Create a non-production instance and verify that it uses the flavor specified in `OPENSTACK_SANDBOX_FLAVOR`.
**Reviewer**
=> [OC-5177] Add a new configuration setting OPENSTACK_PRODUCTION_INSTANCE_FLAVOR

instance/models/server.py, opencraft/settings.py
TASK: [OC-5408](https://tasks.opencraft.com/browse/OC-5408)
This PR is made in an effort to make OCIM AppServer closes gracefully which was not the case. The approach followed here is to shut the AppServer off and then terminating it rather than doing a hard termination.
=> Shutdown a server before termination.

instance/models/instance.py, reports/urls.py
- accept dashes in organization slug in URL. The regexp comes from documentation like https://simpleisbetterthancomplex.com/references/2016/10/10/url-patterns.html
- fix typo (manage_all doesn't exist, now it's manage_own)
=> Minor fixes: organization regexp, documentation typo in "manage_own"

pr_watch/github.py
INFO messages are being logged to DB, and because `pr_watch` runs every minute, the DB is getting filled with responses that come from GitHub, each one can be around 15 Kb; this is making the logs take a lot of space and thus the backups too. This PR makes the responses not be logged to DB.
We still log the queries we do to GitHub (small line).
=> [SE-370] Avoid logging every minute the PRs list from GitHub, to reduce log size in DB

instance/models/mixins/domain_names.py
TASK: [SE-191](https://tasks.opencraft.com/browse/SE-191)
Removing the / from `lms_extended_heartbeat_url` to fix the NewRelic monitors.
=> Remove the redundant slash from heartbeat URL

Vagrantfile, instance/management/commands/instance_redeploy.py, instance/models/server.py, instance/tests/management/test_instance_redeploy.py, instance/tests/models/test_server.py
This should also remove the unnecessary delays during the unit test runs.
=> Fix the shutdown timeout infinite loop bug and also fix the unreliable ordering bug in the instance redeploy command

README.md, instance/models/instance.py, instance/models/mixins/database.py, instance/models/mixins/load_balanced.py, instance/models/mixins/rabbitmq.py, instance/models/mixins/storage.py, instance/models/openedx_instance.py, instance/tests/models/test_openedx_database_mixins.py, instance/tests/models/test_openedx_instance.py, requirements.txt
- Add flags to ignore errors when deleting an OpenEDX Instance.
- Add log messages to show what's going on when deleting an instance.
- Add unit test for deleting an instance ignoring errors.
- Fix some deprovision tests.
- Update responses library to mock response with 'reason' attribute.
When this task was created we thought the issue was that `OpenEDXInstance.delete()` was trying to deprovision resources that were already deprovisioned before.
This is partially true because the `delete()` method was trying to get rid of things that were not there anymore, but those resources were not "correctly" deprovisioned. Meaning, checking for `self.<resource>_provisioned` would not give us the correct state if the resource was deleted manually or using another method.
Also, the class methods …
=> BB-692 Fix errors when deprovisioning resources that has been already deprovisioned.

instance/management/commands/archive_instances.py, instance/tests/fixtures/management/archive_instances.txt, instance/tests/fixtures/management/archive_instances2.txt, instance/tests/management/test_archive_instances.py
See BB-635
Added a new `archive_instances` management command to archive multiple instances by their Internal LMS domains.
Example usage:
```
$ make manage 'archive_instances --domains=sandbox.example.com,test.example.com'
honcho run python3 manage.py archive_instances --domains=sandbox.example.com,test.example.com
Found 2 instances (from 2 domains) to be archived...
- sandbox.example.com
- test.example.com
Are you sure you want to continue? [yes/No]
yes
Archiving sandbox.example.com...
Archiving test.example.com...
Archived 2 instances (from 2 domains).
```
Can also accept a file of newline-separated domains.
```
$ make manage 'archive_instances --file=domains.txt'
```
Includes unittests for the command. Tests were based on existing tests for similar commands like `instance_redeploy`.
=> [BB-635] Add archive_instances command to archive OpenEdXInstances.

instance/tests/integration/integration_instance.py
The test tries to test the betatest application status and the actual
provisioning of the appserver is not needed at all, particularly since
it takes a long time.
=> [BB-783] Mock the appserver spawn in the betatest accepted integration test

bin/run-circleci-tests, circle.yml, cleanup_utils/aws_cleanup.py, cleanup_utils/dns_cleanup.py, cleanup_utils/integration_cleanup.py, cleanup_utils/openstack_cleanup.py, cleanup_utils/requirements.txt, requirements.txt
This PR add two main changes to the integration cleanup script:
1. Improved fault tolerance by catching untreated exceptions
2. Added CircleCI workflows configuration to run cleanup only after all tests are done.
1. Checkout this branch
2. `vagrant up && vagrant ssh` on Ocim's devstack
3. Export environment variables needed for cleanup:
```
export GANDI_API_KEY=
export AWS_ACCESS_KEY_ID=
export AWS_SECRET_ACCESS_KEY=
export GANDI_ZONE_ID=
export OPENSTACK_USER=
export OPENSTACK_TENANT=
export OPENSTACK_REGION=
export OPENSTACK_AUTH_URL=
export OPENSTACK_PASSWORD=
```
4. Run `PYTHONPATH=$PYTHONPATH:$(pwd) honcho -e .env.integration run python3 cleanup_utils/integration_cleanup.py --dry_run` and check that there were no errors on the output.
5. (OPTIONAL) Run `make test.integration_cleanup` …
=> BB-756 - Improve fault tolerance of cleanup script and run it only after all tests are done

Makefile, README.md, cleanup_utils/integration_cleanup.py, cleanup_utils/mysql_cleanup.py, cleanup_utils/requirements.txt
This PR adds an extra cleanup instance to the Integration Cleanup script, to remove MySQL databases that are older than three days.
You can test the cleanup function on a local OCIM instance:
$ vagrant ssh
(opencraft) vagrant@ubuntu-xenial:~$ cd opencraft
(opencraft) vagrant@ubuntu-xenial:~/opencraft$ mysql -u root -h localhost
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 20                                                                                                                      
Server version: 5.7.24-0ubuntu0.16.04.1 (Ubuntu)
Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.
Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners. …
=> BB-804 - Clean up old MySQL instances as part of CI cleanup

README.md, instance/models/mixins/openedx_config.py, opencraft/settings.py
This PR adds a default ansible variable to disable celery heartbeats on supported configurations.
1. Check out this branch on your Ocim devstack
2. Create a new OpenEdX instance on Django Shell:
```
make shell
> instance = OpenEdXInstance.objects.create(        
>     name='Test Sandbox',                                                               
>     sub_domain='test-heartbeats',
> )
```
3. Spawn a new appserver from the web interface (you might have to do this twice, the first time it'll fail with a load balancer error)
4. Check on the appserver configuration if the ansible variable was correctly set: 
**Combined ansible vars:**
```
worker_django_enable_heartbeats: false
```
This is just to check if the variable wa correctly set, no need to wait for the …
=> BB-209: Add setting to disable celery heartbeats

registration/approval.py, registration/tests/test_approval.py
This PR fixes a small bug while provisioning instances for beta testers:
If an automatic provisioning fails and a new AppServer is spawned manually, the automatic activation email is sent to the client but the AppServer is not marked as active.
This PR automatically marks the first instance of a beta tester instance as active, even if it's created manually after the automatic provisioning fails.
*Note: These changes are deployed on **stage**.*
1. Create an account on https://stage.console.opencraft.com/registration/ and confirm your email
2. Login with a admin account and find the instance that you just registered. On my case I registered [giovanni-test-manual-activation-email](https://stage.console.opencraft.com/instance/3220/).
3. Get the IP address of the …
=> [BB-853] Automatically activates first manually created AppServer for beta tester 

instance/models/openedx_instance.py
When we had an actual value at some key path in Consul, such as `[]` for `ocim/instances/<ID>/active_app_servers`, Ocim would bring it in and assume that because it's a falsy value that it shouldn't be updated. So if the instance had any new active appservers, nothing would get updated.
=> [BB-857] Falsy values stored in Consul are still values.

instance/management/commands/reprovision_buckets.py, instance/models/mixins/storage.py, instance/tests/integration/integration_instance.py, instance/tests/management/test_reprovision_buckets.py, instance/tests/models/test_openedx_storage_mixins.py, instance/tests/models/utils.py, opencraft/settings.py, requirements.txt
Description
------------
This PR upgrades the requirement from boto2 to boto3.
It also implements versioning and lifecycle management of s3 buckets
Related tickets: BB-719 BB-329
Testing
-------
1. Checkout the changes and load the shell using `make shell` (this can be done using the admin as well).
2. Create an instance using the shell as mentioned in the README:
```python
from instance.factories import instance_factory, production_instance_factory
instance = instance_factory(name="Sandbox instance", sub_domain="sandbox")
production_instance = production_instance_factory(name="Production instance", sub_domain="production")
```
3. Spawn an AppServer using on `stage.console.opencraft.com`
4. Use either the shell or `awscli` to query the bucket exists, CORS and lifecycle are correct, i.e: …
=> Upgrade to boto3

instance/models/mixins/storage.py
Seem AWS IAM slowness is preventing successful provisioning of S3 buckets in OCIM after the upgrade to `boto3`.
This PR increases the delay between retries during provisioning to account for propagation delays in IAM.
The integration tests are currently failing with:
```
28/Feb/2019 17:47:46 |     INFO | process=2307  | instance.models.instance  | instance=10 (Integration - t) | Provisioning S3 bucket...
28/Feb/2019 17:47:47 |     INFO | process=2307  | instance.models.instance  | instance=10 (Integration - t) | Retrying bucket creation due to "InvalidAccessKeyId", attempt 1 of 4.
28/Feb/2019 17:47:51 |     INFO | process=2307  | instance.models.instance  | instance=10 (Integration - t) | Retrying bucket creation due to "InvalidAccessKeyId", attempt 2 of 4.
28/Feb/2019 17:47:55 |     INFO …
```
=> Increase retry delay when creating and configuring S3 bucket

instance/management/commands/migrate_swift_to_s3.py
This PR adds a management code to migrate an instance from using SWIFT for files (attachments, forum uploads, exams, …) to using S3. It moves the files (with rclone) and then changes the instance's storage setting.
It includes Rocío's code.
It has already been used to migrate many trial instances.
It will be used very few more items and doesn't need fancy features. It doesn't have unit tests since it does so much remote communication that we would have to mock rclone and AWS, and it's not worth it for a few-times script. It has been tested with real servers and verified to work there.
The script fixes some of the filename bugs we found in servers (e.g. `{submissions_attachmentsuser_tasks/ ---> submissions_attachments/user_tasks`). There may be more edge cases but the current fixes cover …
=> [SE-122] Management command to migrate static data from SWIFT to S3

instance/models/mixins/openedx_theme.py, instance/tests/models/test_openedx_theme_mixins.py, opencraft/settings.py, requirements.txt
This PR fixes a lot of styling errors and improves readability for simple-theme deployments on Ocim.
Note: These changes are deployed to Ocim stage.
1. Use Ocim stage to deploy an instance using [the beta testing application form](https://stage.console.opencraft.com/registration/) and this [configuration branch](https://github.com/open-craft/configuration/pull/87).
2. Check if the theme is correctly deployed in the appserver.
I already done this with 2 sets of colors, so you can check the result at:
Light colors: https://stage.console.opencraft.com/instance/3230/edx-appserver/1022/
Darker colors: https://stage.console.opencraft.com/instance/3230/edx-appserver/1020/
**Reviewers:**
=> BB-834: Fix simple-theme deployments

instance/models/mixins/openedx_config.py
This will fix the Studio login issue caused by setting the session
cookie domain wrongly on Studio due to the usage of the ansible
variable 'EDXAPP_SESSION_COOKIE_DOMAIN' which is common to LMS and
Studio.
=> Limit the session cookie domain changes to LMS

instance/models/openedx_appserver.py, instance/tests/models/test_openedx_appserver.py
Our code to grant SSH access was mistakenly including user accounts that were deactivated. This is a small fix to exclude them. I have already updated accounts in the DB so that even without this fix, they aren't included.
Testing instructions: deactivate a user via the django admin, then use the django shell to query an appserver's `admin_users` list. Or just run the before + after versions of this ORM statement (`users = UserProfile.objects. ... .values_list('github_username', flat=True)`) in the django shell. Confirm that deactivated users aren't in the list.
=> Don't grant SSH privileges to inactive users [MNG-918]

circle.yml
The Jessie release repositories are now archived for many
architectures and the 'jessie-updates', 'jessie-backports' sections
do not exist any more and cause errors when running the command to
refresh the data from the apt repositories.
=> Remove the apt repositories that do not exist any more

instance/models/mixins/openedx_config.py
This PR disables the Studio login via SSO that was introduced by Ironwood but keeps the subdomain functionality.
1. Go to studio.
2. Check if the Sign In button lead to a login page inside Studio.
3. Check that the login on Studio works.
4. Check that the LMS login works.
5. Do the same steps for the external and internal domain names
**hawthorn.1**: https://stage.console.opencraft.com/instance/3550/
**ironwood.1**: https://stage.console.opencraft.com/instance/3560/
**master**: https://stage.console.opencraft.com/instance/3570/
=> BB-1081: Disable Studio SSO login

instance/management/commands/update_metadata.py, instance/models/openedx_instance.py, instance/models/utils.py, instance/tests/models/test_utils.py
We currently use [consul locks](https://github.com/open-craft/opencraft/blob/master/instance/models/utils.py#L468) to prevent race conditions between Ocim, cert-manager and other consul clients. However, the `ConsulAgent` class [here](https://github.com/open-craft/opencraft/blob/master/instance/models/utils.py#L447) is the only piece of code that writes instance/appserver configuration to Consul and all the other clients only read it. Due to the locking and the delays associated with locking and releasing the locks when there are multiple clients trying to acquire the lock, we often run into the `ConsulLockAcquisitionException` error due to one of the Ocim processes being unable to acquire the lock due to some reason - too much contention for the lock is a prime example.
By using [Consul …
=> [SE-943] Consul transactions

README.md, instance/api/openedx_appserver.py, instance/static/html/instance/appserver.html, instance/static/html/instance/index.html, instance/static/js/src/openedx_appserver.js, instance/tests/api/test_openedx_appserver.py
This change will allow for manual termination of app servers. This will be allowed for app servers that are not active and instances created from pull requests will be able to deactivate/terminate all app servers.
2. Create a test instance with an associated pull request and another one without it.
3. Manually add appservers in states such as `new`, `failed`, `running` and `configuring` to evaluate the UI behavior.
4. Check that only appservers in `running` state can be made active.
5. Make sure that only inactive appservers in `configuring`, `running` and `failed` can be terminated.
If it fails to mark an appserver active/inactive, make sure there's an associated server in the correct state:
```
In [25]: for apps in …
```
=> BB-1137 Add terminate button to app server UI

opencraft/settings.py
This is done in preparation for mass-upgrading the self-hosted Ocim
instances to Ironwood
=> [BB-1191] Update the default release to Ironwood

README.md, instance/models/mixins/openedx_config.py, instance/models/mixins/openedx_storage.py, instance/tests/models/test_openedx_storage_mixins.py
* Add the new ansible variable which enables installing the `aws` role in Ironwood. Retain the old one for backward compatibility till all the instances are upgraded to Ironwood.
* Add the new ansible variable for disabling celery heartbeats as merged upstream. Retain the old one for backward compatibility till all the instances are upgraded to Ironwood.
* Spawn an appserver with this PR and verify that it works correctly. There is [an instance]( https://ironwood-config.sandbox.stage.opencraft.hosting/) spawned for testing the configuration branch PR with this PR deployed on stage.
=> [BB-1216] Ironwood changes

circle.yml, cleanup_utils/aws_cleanup.py, cleanup_utils/integration_cleanup.py, cleanup_utils/mysql_cleanup.py, instance/ansible.py, instance/models/openedx_instance.py, instance/tests/integration/base.py, instance/tests/integration/factories/instance.py, instance/tests/integration/integration_instance.py, instance/utils.py, opencraft/settings.py
This PR updates the integration tests to use hawthorn edx and configuration branches.
While doing the update there was an issue with migrations taking too long. The reason was because the centralized MySQL server used to run integration tests had too many databses and users created. There's a cleanup script that runs on every CirlceCI pipeline that deletes databases older than 8 hours.
The cleanup script was updated. A new method was added to delete every database and user used in integration tests in case we eventually need to delete everything.
Also, the cleanup script (specifically the MySQL part) is using `information_schema.tables` (and there's no other way to do it). The issue is that if a database is created and no tables are added to the database then it will not appear in …
=> BB-839 update integration tests to use Hawthorn

instance/tests/integration/factories/instance.py
Updates the `edx-platform` and `configuration` branches in the CI tests to Ironwood.
=> [BB-936] Update integration tests to use the Ironwood branches

cleanup_utils/load_balancer_cleanup.py, instance/tests/integration/integration_instance.py, registration/tests/test_provision.py
* Verify that no integration test load balancer configuration fragments are skipped when the deletion task is run in the cleanup CI task.
* Verify that there are now no warnings about using a native datetime when timezone support is enabled.
=> Fix a bug causing the load balancer configuration fragments to not get cleaned up and a datetime warning

bin/install-supported-firefox, circle.yml, opencraft/settings.py
The corresponding changes to the `ansible-secrets` repository made [here](https://github.com/open-craft/ansible-secrets/commit/0fa7327953634bc3353bc2f90a1bd4c8e2d01ffb) - pushed directly to the branch by mistake instead of creating a PR.
=> [BB-1191] Update the default release to ironwood.2

instance/models/mixins/openedx_config.py, instance/models/utils.py, instance/tests/models/test_openedx_appserver.py, registration/tests/utils.py
Description
=========
This PR implements a check for the Github users before provisioning the servers to prevent failures when a user isn't found.
Testing
----------
1. Check out this branch in Stage and restart the server.
2. Replace a user's Github handle with one that does not exist.
3. Start provisioning a new App Server.
4. Make sure it does not fail when adding users, as the user that does not map to a Github user does not show the `github` key.
```
2019-06-25 10:29:07-0300 INFO
changed: [54.38.70.171] => (item={u'type': u'admin', u'name': u'viadannap'})
2019-06-25 10:29:07-0300 INFO
changed: [54.38.70.171] => (item={u'github': True, u'type': u'admin', u'name': u'viadanna'})
```
=> [BB-960] Don't fail when Github user does not exist

opencraft/settings.py
This is a small change that allows setting the email threshold on the .env file and changes the default value from `ERROR` to `CRITICAL`.
This change was made because the volume of spam daily sent to our ops email.
**Reviewers:**
=> BB-1300: Let email level be configured in env and set default to CRITICAL

instance/models/mixins/load_balanced.py, instance/tests/models/test_load_balanced_mixin.py, opencraft/settings.py
Related to https://github.com/open-craft/ansible-secrets/pull/128 and has to be tested along with the changes in it.
* Update Ocim to the source branch of this PR.
* Apply the changes in the related `ansible-secrets` PR to the Ocim `.env` file.
* Restart Ocim.
* Create a new instance and launch a new appserver.
* Wait for the DNS records to propagate and then visit https://<instance domain>. Alternatively, add an entry in `/etc/hosts` for the instance domain, ignore an SSL certificate error and navigate to the URL.
* Verify that a page with the text `The instance is being provisioned. Please come back in a little while...` is loaded. This should have the same content as http://default.opencraft.com.
* Also check that the preliminary page configuration for the …
=> [BB-1481] Changes for fixing the preliminary page issue

instance/tests/models/test_load_balanced_mixin.py
The unit test started failing after the `PRELIMINARY_PAGE_HOSTNAME` was
set in the CircleCI environment and the test expected it to not be
set. The fix explicitly makes the value `None` so that the test doesn't fail.
=> [BB-1481] Fix failing unit test

instance/models/load_balancer.py, instance/models/mixins/load_balanced.py, instance/models/openedx_instance.py, instance/tests/models/test_load_balanced_mixin.py, instance/tests/models/test_openedx_appserver.py, opencraft/settings.py
This PR adds a flag to gate load balancer reconfiguration on Ocim.
1. Checkout this branch on your Ocim devstack
2. Run tests related to this change and check that they pass.
```
make test.one instance.tests.models.test_openedx_appserver.OpenEdXAppServerTestCase.test_make_active_no_load_balancer_reconfiguration
make test.one instance.tests.models.test_openedx_appserver.OpenEdXAppServerTestCase.test_make_active
make test.one instance.tests.models.test_load_balanced_mixin
```
3. Configure Ocim with the `.env` used for development and add `DISABLE_LOAD_BALANCER_CONFIGURATION = True`.
4. Run Ocim Shell and check that the setting is correctly set.
5. Create a new instance:
``` …
```
=> BB-1576: Add variables required to gate playbook reconfiguration

instance/models/mixins/openedx_config.py
This PR [enables prereqeusite subsections feature](https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/enable_prerequisites.html#enable-course-prerequisites)
1. Checkout this branch on your Ocim devstack.
1. Configure Ocim with the `.env` used for development.
1. Run Ocim Shell and create a new instance:
```
production_instance_factory(name='123', sub_domain='bb1576-test')
```
1. Run Ocim with `make run.dev` and spawn a new appserver. Check that the `Configuration` section has these two lines under `EDXAPP_FEATURES`:
```
MILESTONES_APP: true
ENABLE_PREREQUISITE_COURSES: true
```
Make sure you clean up the instance afterwards.
=> [BB-1543] Enable prerequisite subsections feature

README.md, instance/management/commands/delete_archived.py, instance/tests/management/test_delete_archived.py
Description
=========
This pull requests adds a `delete_archived` management command.
The command will fetch all archived instances older than the given number of months, and after user confirmation, delete these instances.
Testing
----------
1. Create a couple instances in your devstack and archive them:
```
from instance.factories import instance_factory
instance = instance_factory(name="Sandbox instance", sub_domain="sandbox")
instance.ref.is_archived = True
instance.ref.save()
```
2. Modify the `modified` attribute of one of the instance references:
```
from datetime import timedelta as td
instance.ref.modified -= td(days=365)
instance.ref.save(update_modified=False)
```
3. Run the management command and check it finds the correct instances
```
$ honcho run python manage.py …
```
=> [BB-1604] Add delete_archived management command

instance/models/mixins/openedx_config.py
14 and 7 were way too high to use as safe defaults, resulting in small
instances locking up.
The changes that we're reverting were introduced in https://github.com/open-craft/opencraft/pull/437
**Reviewer**:
=> SE-1463 revert changes to EDXAPP_WORKERS

instance/management/commands/delete_archived.py, instance/tests/management/test_delete_archived.py
Description
=========
This is a followup to #458 due to the unexpected situation of an InstanceReference existing without being linked to an Instance.
This will remove the InstanceReference.
Testing
----------
1. In Stage, create an InstanceReference without an associated instance:
```
from dateutil.relativedelta import relativedelta
ref = InstanceReference.objects.create(name='instanceless', instance_id=9000000, instance_type_id=13)
ref.modified -= relativedelta(months=90)
ref.is_archived = True
ref.save(update_modified=False)
```
2. Run the command to remove the instanceless:
```
$ honcho run python manage.py delete_archived 80
```
3. Make sure the process succeeds and the InstanceReference is removed:
```
$ honcho run python manage.py delete_archived 80
(...) No archived instances …
```
=> [BB-1604] Handle InstanceReferences without a proper Instance

instance/models/mixins/storage.py, instance/tests/models/test_openedx_storage_mixins.py
This PR introduces a small change in configuration passed to the edX instance: passing the s3 regional endpoint instead of the generic ***.s3.amazonaws.com**.
Files aren't affected, and old links still work, this is mainly to future proof our deployment after some recent issues.
**Part 1:** checking url interoperability.
1. Use [this instance](https://stage.console.opencraft.com/instance/4220/).
- Appserver 1 has the old Ocim behaviour
- Appserver 4 has the new S3 bucket url set up
2. Check that images, reports and forum attachments can be correctly accessed by both appservers using the the and old appserver url.
3. Create an grade report and check that it can be download from the two appservers and check that on the newest appserver the regional endpoint is …
=> BB-1651: Pass S3 regional endpoint to instance instead of generic one

instance/management/commands/delete_archived.py, instance/models/instance.py, instance/models/mixins/load_balanced.py, instance/models/openedx_instance.py
Description
========
This PR makes it possible to ignore errors when removing dns entries from Gandi. This is required when archiving an OpenEdxInstance whenever the Gandi account does not contain the domain for the instance any longer.
The original behaviour was kept and it's possible to enable this by passing `ignore_errors` or `ignore_dns_errors` to both `.archive()` and `.delete()`.
Testing
-------
1. Create an instance in the Stage environment using the shell:
```
i = production_instance_factory(name="Deletion Test", sub_domain="deletiontest")
i.archive()
```
2. Make sure the instance has a DNS that isn't managed by Gandi:
```
i.internal_lms_domain = 'deletiontest.sandbox.com'
i.save()
```
3. Update it to be removed by the …
=> BB-1683 Allow ignoring Gandi error when deleting dns

instance/models/mixins/openedx_config.py
This prevents the djangoapps.heartbeats app from being added on master openedx
instances by default. Since https://github.com/edx/edx-platform/pull/21633 was
merged, djangoapps.heartbeats is installed by default. Attempting to add again
will result in an error from django about adding duplicate apps.
The only reason this isn't already causing master sandboxes to fail is because
https://github.com/edx/configuration/pull/5400 hasn't been merged yet (at time
of writing); currently the `EDXAPP_*_ENV_EXTRA` blocks aren't being picked up
by the configuration so our defaults aren't being applied on master anyway.
**Merge deadline**: ASAP - let's avoid more broken master sandboxes
1. deploy ocim with this branch
2. launch a master openedx sandbox …
=> SE-1577 Conditionally add djangoapps.heartbeat

Procfile, Procfile.dev, circle.yml, documentation/installation.md, instance/consumers.py, instance/logging.py, instance/models/instance.py, instance/models/openedx_appserver.py, instance/models/server.py, instance/routing.py, instance/static/html/instance/details.html, instance/static/js/src/instance.js, instance/static/js/src/openedx_appserver.js, instance/tests/js/instance_app_spec.js, instance/tests/models/test_log_entry.py, instance/tests/models/test_server.py, instance/tests/utils.py, instance/utils.py, opencraft/asgi.py, opencraft/routing.py, opencraft/settings.py, requirements.in, requirements.txt
Adds real-time updates to Ocim using Django channels.
The instructions given below are for testing in the vagrant environment and will require some changes to test in other environments.
* The `channels_redis` library used as the channel layer for `channels` requires Python 3.6 or above, but the version of Python available on Ubuntu 16.04 (used in production and on vagrant) only supports 3.5.x. So to test this PR, install `pyenv` and `pyenv-virtualenv` plugin. Install Python 3.6.9 (the latest Python 3.6 release), create a virtualenv using `pyenv-virtualenv`, activate it and install all the requirements in `requirements.txt.`,
* Setup the configuration in `.env` using the file in the private documentation repository. It is missing some configuration related to AWS …
=> [BB-1375] Re-add real-time updates to Ocim (with websockets through Django Channels)

.env.test, instance/models/openedx_instance.py, instance/tests/api/test_instance.py, instance/tests/api/test_openedx_appserver.py, instance/tests/api/test_openedx_instance.py, instance/tests/management/test_archive_instances.py, instance/tests/management/test_delete_archived.py, instance/tests/management/test_instance_redeploy.py, instance/tests/management/test_reprovision_buckets.py, instance/tests/models/test_load_balanced_mixin.py, instance/tests/models/test_load_balancer.py, instance/tests/models/test_log_entry.py, instance/tests/models/test_openedx_ansible_mixins.py, instance/tests/models/test_openedx_appserver.py, instance/tests/models/test_openedx_database_mixins.py, instance/tests/models/test_openedx_instance.py, instance/tests/models/test_openedx_monitoring_mixins.py, instance/tests/models/test_openedx_secret_key_mixins.py, instance/tests/models/test_openedx_storage_mixins.py, instance/tests/models/test_openedx_theme_mixins.py, instance/tests/test_factories.py, instance/tests/test_tasks.py, pr_watch/tests/test_api.py, pr_watch/tests/test_models.py, registration/tests/test_provision.py, registration/tests/test_views.py, reports/tests.py
Use this in `.env.test`:
```
CONSUL_SERVERS=fake-consul-dns.name
DEFAULT_LOAD_BALANCING_SERVER=ubuntu@fake-load-balancer
CONSUL_ENABLED=true
DISABLE_LOAD_BALANCER_CONFIGURATION=true
```
And run `make test.unit` inside the `opencraft` directory in a vagrant machine.
**Author's notes and concerns**
`pr_watch.tests.test_tasks.TasksTestCase` has failing tests for me locally, even on master, I suspect because I have something misconfigured.
=> [SE-1603] Mock Consul for unit tests

.env.test, circle.yml
A small change (which took a lot of work to get, thanks @clemente !) to not run the consul agent in dev mode but instead to connect it to the Consul server running on `haproxy-integration`.
This means that when integration tests run, they will write instance data to that consul, which will then request certs for them via the cert-manager.
To avoid test failures during DNS propagation, there is a wildcard in Gandi for `*.integration` which points to `haproxy-integration`.
The other change required is setting a few variables in CircleCI config (and updating the entry in Vault).
```
DEFAULT_LOAD_BALANCING_SERVER: ubuntu@haproxy-integration.net.opencraft.hosting
CONSUL_SERVERS: haproxy-integration.net.opencraft.hosting
CONSUL_ENABLED: true
DISABLE_LOAD_BALANCER_CONFIGURATION: true
``` …
=> Wire integration tests to their own load balancer

instance/tasks.py, periodic_builds/tasks.py, periodic_builds/tests/test_tasks.py
This deactivates old appservers on successful provisioning of a new appserver when launched from the periodic builds task.
1. Set up a sandbox for periodic builds
2. wait for at least two appservers to be launched by the periodic builder
3. verify that previous appservers are deactivated and the latest appserver is activated always
Note that this can currently be verified with the [master test](https://stage.console.opencraft.com/instance/4330/) instance on stage.
**Reviewers**
=> SE-1682 deactivate old appservers periodic builds

documentation/periodic_builds.md, mkdocs.yml
This adds documentation about the periodic builds system. The idea for this is to make the periodic builds functionality visible and have a readable reference document for the behaviour, technical information (where appropriate), and how it can be used.
- install `mkdocs`
- build the documentation with mkdocs
- view the new periodic builds page and check that it is rendered properly
- check for typos
- cross check with the actual periodic build behaviour and config to verify correctness
**Author notes**:
- this is subject to change pending resolution of https://github.com/open-craft/opencraft/pull/481 and https://github.com/open-craft/opencraft/pull/477
**Reviewer**:
=> SE-1608 Add periodic builds docs

instance/models/mixins/openedx_config.py, instance/models/mixins/secret_keys.py
This PR adds variables related to the retirement service that were renamed in the upstream PR.
1. Check that the following variables are set when spawning an appserver:
- `COMMON_RETIREMENT_SERVICE_SETUP`
- `RETIREMENT_SERVICE_SETUP`
-  `RETIREMENT_SERVICE_OAUTH_CLIENT_ID`
-  `RETIREMENT_SERVICE_OAUTH_CLIENT_SECRET`
-  `RETIREMENT_SERVICE_EDX_OAUTH2_KEY`
-  `RETIREMENT_SERVICE_EDX_OAUTH2_SECRET`
2. Check that `RETIREMENT_SERVICE_OAUTH_CLIENT_ID` is equal `RETIREMENT_SERVICE_EDX_OAUTH2_KEY`
3. Check that `RETIREMENT_SERVICE_OAUTH_CLIENT_SECRET` is equal `RETIREMENT_SERVICE_EDX_OAUTH2_SECRET`
**Reviewer:**
=> BB-987: Rename variables to keep upstream compatibility

instance/factories.py, instance/tests/test_factories.py, registration/provision.py, registration/tests/test_provision.py
This moves the auto-setting of proviosing failure notification emails from production instance factory to the provision instance function that is called when creating an instance for an end user. Doing this because we only want to auto set PROD_APPSERVER_FAIL_EMAILS for end user instances.
- deploy this branch to stage (no migrations and only small changes; easy to switch between this and master)
- register as an end user
- verify that the resulting instance has the settings.PROD_APPSERVER_FAIL_EMAILS address(es) set on provisioning_failure_notification_emails
- launch a new instance via production_instance_factory
- verify that no provisioning_failure_notification_emails are set
**Reviewer**:
=> SE-1832 Move auto provisioning failure email alerts to registration

circle.yml, frontend/.eslintrc.json, frontend/package-lock.json, frontend/package.json, frontend/src/registration/components/DomainInputPage/DomainInputPage.tsx, frontend/src/registration/components/DomainInputPage/__snapshots__/DomainInputPage.spec.tsx.snap, frontend/src/registration/components/InstanceSetupPage/__snapshots__/InstanceSetupPage.spec.tsx.snap, frontend/src/registration/components/RegistrationContainer/__snapshots__/RegistrationContainer.spec.tsx.snap, frontend/src/registration/components/RegistrationPage/__snapshots__/RegistrationPage.spec.tsx.snap, frontend/src/ui/components/App/__snapshots__/App.spec.tsx.snap, frontend/src/ui/components/Header/__snapshots__/Header.spec.tsx.snap, frontend/src/ui/components/StepBar/__snapshots__/StepBar.spec.tsx.snap
This PR set's up automatic deployment of the new Ocim static frontend. It does this:
1. Runs tests.
2. Builds static files.
3. Waits for user approval to run deployment.
4. Deploys to S3 and invalidates CloudFront.
1. Rerun the CI checks
2. Wait until the `allow-deployment` stage then click on the stage and **Approve** the deployment:
3. Watch the redeployment, check that the files were updated and a CloudFront invalidation was triggered. The AWS account is: [Ocim Stage](https://vault.opencraft.com:8200/ui/vault/secrets/secret/show/core/OpenCraft%20Tools%20:%20Resources%20:%20AWS%20:%20AWS%20S3%20Stage).
4. Check the live app: https://app.stage.console.opencraft.com/
**Reviewers:**
=> BB-1876: Add frontend automatic build and deployment WIP

registration/utils.py, templates/emails/account_info_email.html, templates/emails/account_info_email.txt
This PR fixes an issue where the email templates expected theme configuration, but this isn't set up during the registration form.
1. Create a new account through the registration form.
2. Activate the account using the email link.
**Reviewer:**
=> BB-1970: Fix registration emails

documentation/configuration.md, instance/gandi.py, instance/tests/test_gandi.py, opencraft/settings.py
This will be needed when the 'DEFAULT_INSTANCE_BASE_DOMAIN' is not
set to the base domain present in the Gandi account.
* In the stage environment, set the `GANDI_DEFAULT_BASE_DOMAIN` environment variable and verify that the DNS records for an instance are created properly as subdomains of the stage subdomain and not directly as the subdomains of the production domain.
=> [BB-2006] Use a separate variable for the default fallback domain in Gandi account

instance/models/server.py, instance/tests/models/factories/server.py, instance/tests/models/test_server.py
This PR is a follow-up to #495. It removes SSH key from `~/.ssh/known_hosts` before we terminate the sever. This way we won't encounter SSH key conflict when we get the server with the same IP we've used before.
1. Log into stage.
1. Create new AppServer for any existing instance.
1. Log to stage via SSH and switch to the proper user.
1. Run `ssh-keygen -F $IP` to check that the key has been added to `~/.ssh/known_hosts`. If the response is empty, try again in a minute.
1. Use `Terminate` button in Ocim.
1. Run `ssh-keygen -F $IP` to confirm that the key has been deleted.
Note: integration tests are failing, but they're not related to this change.
=> [BB-1913] Delete SSH key upon terminating the AppServer

api/auth.py, api/urls.py, frontend/packages/api_client/src/apis/V2Api.ts, frontend/packages/api_client/src/models/Token.ts, frontend/packages/api_client/src/models/TokenError.ts, frontend/packages/api_client/src/models/index.ts
This PR adds refresh and verify endpoints and update frontend API client.
2. Run Ocim using `make run.dev`.
3. Go to the Swagger API docs (http://localhost:5000/api/swagger/) and check that the following endpoints exist and are correctly specified:
- /v2/auth/verify/
- /v2/auth/refresh/
4. Test the endpoints using the browser client.
5. Go into the frontend folder and update the API client using the following command:
```
./scripts/build-api-client.sh
```
6. Run the frontend: `npm run start`
7. Access the page and open the browser console. Test the API client from there.
**Reviewer:**
=> BB-2026: Add new authentication endpoints

documentation/installation.md, mkdocs.yml
Per https://github.com/mkdocs/mkdocs/blob/master/docs/user-guide/configuration.md#edit_uri,
we can set the `edit_uri` configuration parameter to correctly link the
"edit on GitHub" text.
This is not associated with any Jira task and was merely an onboarding exercise.
=> doc: set edit_uri path for mkdocs

instance/gandi.py, instance/models/mixins/utilities.py, instance/tests/models/test_openedx_appserver.py, instance/tests/models/test_openedx_instance.py
This PR doesn't change the e-mails that we currently send to ops@ after each deployment failure.
This PR adds a new type of e-mail which would go to the address we have in PagerDuty. The e-mail is triggered when *all* deployment attempts have been used. Only for betatest instances.
**Fine details**
- the urgent e-mail actually goes to `instance.provisioning_failure_notification_emails`, whatever that is in each instance. It's mainly our PagerDuty e-mail. We'll assume that that value was already set in all important instances in production (this comes from a previous development)
- the urgent e-mail is only sent if the instance has a beta test application, i.e. if they got the instance after filling in a form. This excludes test instances that we have created manually, and also big client …
=> [SE-1968] Send an urgent e-mail after all deployment attempts fail

circle.yml, cleanup_utils/dns_cleanup.py, cleanup_utils/integration_cleanup.py, instance/gandi.py
The DNS cleanup operation has been failing for the past few days and we are unable to reproduce the issue due to an issue with the current cleanup code. This PR fixes the issue in the DNS cleanup code and also prevents the suppression of the failures on future runs by doing the DNS cleanup first (as it relies on the hashes from the other cleanup operations) before all the other cleanup operations. It also fixes a bug in the Gandi library code where an exception is suppressed when it happens for unknown reasons.
* Rerun an instance of the failed cleanup job with SSH.
* Log in to the container where the tests are run.* Log in to the container where the tests are run.
* Rerun an instance of the build-and-test job and cancel it once the ansible provisioning of the VM …
=> Fix DNS cleanup failures

registration/tests/test_views.py
This PR reverts the instance type override made in the previous commit for the failing unit test case.
=> Revert s3 override for failing test

cleanup_utils/openstack_cleanup.py, instance/management/commands/migrate_swift_to_s3.py, instance/models/mixins/openedx_storage.py, instance/openstack_utils.py, instance/tests/test_openstack_utils.py
Update keystone (OpenStack Identity Service) API v2.0 to v3. See [deprecation notice](http://travaux.ovh.net/?do=details&id=42179)
The API change affects the way Ocim authenticates with OpenStack.
I don't think it affects other cases (e.g. the SWIFT usage done from an edxapp instance), though I didn't particularly test it since we've deprecated it. Likewise for the `migrate_swift_to_s3` command: it passes some parameters to `rclone` to create a configuration. This call may need some update if we ever use the script again and it doesn't work.
- This PR changes the authorization part. It doesn't change other OpenStack APIs. For instance, this mustn't change from 2 to 3: `def get_nova_client(region_name, api_version=2):`. It's a different setting, it's the client version, not the …
=> [SE-2273] Update keystone calls (OpenStack Identity API) from v2 to v3

opencraft/settings.py, registration/tests/test_api.py, registration/utils.py, registration/validators.py, templates/emails/welcome_email.html
This PR introduces 2 changes:
1. Fixes broken link on welcome email and add support for empty link.
2. Add custom password validators.
2. Set up some email configuration in `.env`.
```
EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST=smtp.gmail.com
EMAIL_USE_TLS=True
EMAIL_PORT=587
EMAIL_HOST_USER=your_email@opencraft.com
EMAIL_HOST_PASSWORD=
```
3. Run Ocim and create a betatest instance (no need to activate emails).
4. Run `make shell` and then the following commands:
```
from registration.utils import send_welcome_email
from registration.models import BetaTestApplication
x = BetaTestApplication.objects.all()[0] 
send_welcome_email(x)                                                                            
``` …
=> BB-2179: Registration form and welcome email fixes.

instance/management/commands/archive_instances.py, instance/models/openedx_instance.py, instance/tests/models/test_openedx_instance.py
This PR implements the following changes to fix a problem when metadata for archived instances would remain present in consul:
- Deprovision RabbitMQ when `instance.archive()`.
- Remove explicit call to deprovision RabbitMQ from the `archive_instances` management command.
- Make sure that consul metadata does not get written if instance is archived.
For these to work the Ocim installation where you are testing needs to have Consul enabled. I suggest testing on Ocim stage where I have deployed the changes from this PR.
1. Create a new instance and spawn at least one appserver.
2. In the django shell, verify that consul contains metadata for this instance: `from instance.models.utils import ConsulAgent`, then `ConsulAgent(prefix=instance.consul_prefix).get('')`.
3. …
=> [SE-2216] Deprovision RabbitMQ when archiving instance.

Makefile, documentation/howtos.md
Fixes some formatting issues with the `mkdocs` rendered markdown for the "How To" documentation page, cf https://ocim.opencraft.com/en/latest/howtos/
Changes made:
* established standard line length of 200 characters.
* added yaml/bash code rendering hints to code blocks
* code blocks cannot be indented in mkdocs markdown
* code blocks mess with ordered list numbering, so converted to unordered lists.
* comments in pasted shell commands mess with the backslash line continuation character, so have moved them into the main content.
* changed heading levels, added more headings.
* moved all extra configuration changes to the top instance configuration section.
1. Run `make docs` to build the documentation.
1. Run `make docs-serve` to check the rendered documentation …
=> SE-2413 Fixes formatting on the rendered documentation How To page

instance/models/mixins/openedx_config.py
The feature flag which disables Studio login via SSO from the LMS is removed in Juniper.
This PR disables that feature flag to enable Studio SSO, and to make the behaviour standard across all our deployments.  We also set the default session cookie name to `.<lms domain>` to allow sharing of cookies between Studio, LMS, and other service subdomains.
This reverts the changes made by https://github.com/open-craft/opencraft/pull/422, but is deemed safe because we are now using `studio.<lms domain>` subdomains for all our hosts.
Suggest that this is tested on stage.console.opencraft.com
Create instances of the following types, and ensure that logging into Studio works, via the LMS.
* production instance
* PR sandbox instance
* juniper.alpha1 instance
**Reviewer**
=> SE-2318 Enables Studio login SSO from the LMS

opencraft/settings.py, registration/views.py
This PR adds a simple redirection mechanism to direct users to the new frontend until we do the domain migration.
2. Run Ocim.
3. Go to http://localhost:5000/registration and check that the form is displaying as usual.
4. Add these to your `.env` file:
```
USER_CONSOLE_FRONTEND_URL="https://app.console.opencraft.com"
NEW_USER_CONSOLE_REGISTRATION_ENABLED=True
```
5. Open your browser inspetion tool.
6. Restart Ocim, check that http://localhost:5000/registration redirects to the new frontend.
7. Check that the redirect was a `302 Found` and not a permanent redirect. 
**Reviewer:**
**Notes:**
This is just a temporary change, until Ocim gets migrated to the new domain (manage.opencraft.com). It will be removed soon, so that's why I didn't …
=> BB-2328: Add new frontend redirects

frontend/packages/api_client/src/models/OpenEdXInstanceConfig.ts, frontend/packages/api_client/src/models/OpenEdXInstanceConfigUpdate.ts, frontend/src/registration/components/AccountSetupPage/AccountSetupPage.tsx, frontend/src/registration/components/CongratulationsPage/__snapshots__/CongratulationsPage.spec.tsx.snap, frontend/src/registration/components/CongratulationsPage/displayMessages.ts, frontend/src/registration/components/InstanceSetupPage/InstanceSetupPage.tsx, frontend/src/registration/components/InstanceSetupPage/__snapshots__/InstanceSetupPage.spec.tsx.snap, frontend/src/registration/components/InstanceSetupPage/displayMessages.ts, frontend/src/registration/components/InstanceSetupPage/styles.scss, frontend/src/registration/models.ts, frontend/src/ui/components/ErrorPage/__snapshots__/ErrorPage.spec.tsx.snap, frontend/src/ui/components/ErrorPage/displayMessages.ts, registration/api/v2/serializers.py, registration/api/v2/views.py, registration/tests/test_api.py
**Issue**: [BB-2444](https://tasks.opencraft.com/browse/BB-2444)
**Screenshots**(Updated):
* Go through the registration process by creating a new instance, check it works perfectly or not
* At the congratulation page, the message should be right.
* Go through by signing in and checking that the first time the public contact email should be similar to the user email you set when creating the instance.
**Reviewers**:
=> [BB-2444] Remove public contact email from registration

frontend/src/console/components/RedeploymentToolbar/RedeploymentToolbar.tsx, frontend/src/ui/components/CustomStatusPill/CustomStatusPill.tsx
This PR fixes a small bug in the status pill that shows the wrong deployment message in the first deployment.
1. Use the `master` branch.
2. Go to the registration form (http://localhost:3000) and create a new account (don't forget to activate the email).
3. Apply this diff to make testing easier:
```
diff --git a/registration/api/v2/views.py b/registration/api/v2/views.py
index 81fc8c2d..d36e54ed 100644
--- a/registration/api/v2/views.py
+++ b/registration/api/v2/views.py
@@ -547,7 +547,7 @@ class OpenEdxInstanceDeploymentViewSet(CreateAPIView, RetrieveDestroyAPIView, Ge
data = {
'undeployed_changes': undeployed_changes,
'deployed_changes': deployed_changes,
-            'status': deployment_status.name,
+            'status': DeploymentState.provisioning.name, …
```
=> BB-1848: Fix bug on status pill in the first deployment

instance/management/commands/kill_zombies.py
Implements a `kill_zombies` management command to find and terminate servers in a given OpenStack region that were recorded as having been terminated, but for some reason remain standing.
=> [SE-2590] Management command to terminate zombies

instance/models/utils.py, instance/tests/models/test_utils.py
This PR fixes the issue of consul purging all keys containing a prefix thus leading to unexpected deletions. 
**Issue:** [SE-2666](https://tasks.opencraft.com/browse/SE-2666)
**Testing Instructions:**
1. Checkout this branch and create an ocim instance such that it's id can be a prefix to already existing instance (use a non-critical instance)
2. Archive the instance and verify that only the consul data of the archived instance is removed and not the prefixed instance.
**Reviewers**
=> [SE-2666] Fix unexpected prefix purge

instance/models/utils.py, instance/tests/integration/integration_instance.py, instance/tests/models/test_utils.py
This PR increases the retries for spawning new OpenedX appservers by 2, to avoid some integration test failures in CircleCI.
**JIRA tickets**: [SE-2599](https://tasks.opencraft.com/browse/SE-2599)
1. This is the first approach to solve this issue given by @lgp171188.
2. Not sure how to test it given the flaky nature of the failures. Maybe leave it open for a month or something like that to see if it happens again?
**Reviewers**
=> [SE-2599] Fix flaky integration tests

instance/models/mixins/openedx_config.py
This PR adds the ansible variables that allow configuring the course visibility from Studio. See [here](https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/defaults/main.yml#L728-L729) for the defaults and see the assignment to the corresponding environment variables [here](https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/defaults/main.yml#L1244-L1245).
* Add the following to `lms.env.json`
```javascript
{
...
"COURSE_CATALOG_VISIBILITY_PERMISSION": "see_in_catalog",
"COURSE_ABOUT_VISIBILITY_PERMISSION": "see_about_page"
...
}
```
or `lms.yml`
```yaml
COURSE_CATALOG_VISIBILITY_PERMISSION: see_in_catalog
COURSE_ABOUT_VISIBILITY_PERMISSION: see_about_page
```
* Restart LMS and Studio.
* Configure the course visibility …
=> [BB-2696] Allow configuring course visibility from Studio

circle.yml, instance/models/openedx_appserver.py, instance/tests/integration/integration_instance.py, instance/tests/integration/utils.py, instance/tests/models/test_openedx_appserver.py, playbooks/manage_services/manage_services.yml
This PR
* Adds changes to only start/stop the celery workers on appserver activation/deactivation. This prevents the unit tests related to Consul from being skipped. This has to be tested and verified on stage.
* Fixes the consul configuration which was breaking unit and integration tests - enables consul encryption for the integration tests and the cleanup job and runs consul in dev mode for everything else.
* Increases the retries and the delay between retries when checking whether the integration test instance is up or not. Also adds logging to show the retries.
=> Fix Ocim integration test failures

instance/api/instance.py, instance/serializers/instance.py, instance/static/html/instance/details.html, instance/static/js/src/instance.js, instance/tests/api/test_instance.py
This PR adds filter to instance `notes` field to display them only for `staff` and `superuser` users only.
**JIRA ticket**: [SE-2729](https://tasks.opencraft.com/browse/SE-2729)
**Reviewers**
=> [SE-2729] OCIM add instance description field

frontend/packages/api_client/src/apis/V2Api.ts, frontend/scripts/update-api-client.sh, frontend/src/console/actions.ts, frontend/src/console/components/ConsolePage/ConsolePage.tsx, frontend/src/console/components/ConsolePage/displayMessages.ts, frontend/src/console/models.ts, frontend/src/console/reducers.ts, frontend/src/ui/components/ErrorPage/ErrorPage.spec.tsx, frontend/src/ui/components/ErrorPage/ErrorPage.tsx, frontend/src/ui/components/ErrorPage/__snapshots__/ErrorPage.spec.tsx.snap, frontend/src/ui/components/ErrorPage/styles.scss, registration/api/v2/views.py
This PR disables the new OCIM console for staff users
**JIRA tickets**: [SE-2865](https://tasks.opencraft.com/browse/SE-2865)
- Checkout this branch.
- Enter new frontend subdirectory: `cd frontend`
- Build Ocim API client: `./scripts/build-api-client.sh`
- Reinstall dependencies: `npm install`
- Run tests - `npm test`
- Run frontend - `npm start`
- Go to `http://localhost:3000/` and login as a staff user
- You should see the above error page.
- Logout and login as a normal user - you should be able to see the OCIM console as usual.
**Reviewers**
=> SE-2865 Disable the new OCIM console for staff users

frontend/src/console/components/ConsolePage/ConsolePage.tsx
See #602 for complete details
**JIRA tickets**: [SE-2865](https://tasks.opencraft.com/browse/SE-2865)
This is a follow-up to that PR, where the URL has been updated from `/` to `/instance`, as the former one redirects back to the new console on stage
**Reviewers**: @mtyaka
=> [SE-2865] Update URL for old OCIM

instance/models/mixins/load_balanced.py, instance/tests/models/test_load_balanced_mixin.py, instance/tests/models/test_openedx_instance.py
When no appservers are active, instance LMS and Studio URLs should not redirect the user, but just display contents of default.opencraft.com. Have applied the patch manually to the below instance on stage too, for testing purposes.
**JIRA tickets**: [SE-2948](https://tasks.opencraft.com/browse/SE-2948)
**Sandbox URL**: https://sid-test-2.stage.opencraft.hosting (The DNS has 3 IP addresses, so you might see the old deployment on IPs other than 54.36.101.120)
1. Run `curl --insecure -v --header "Host:se-2870-test.opencraft.hosting" https://54.36.101.120` and verify 301 Moved Permanently response.
2. Run `curl --insecure -v --header "Host:sid-test-2.stage.opencraft.hosting" https://54.36.101.120` and verify 200 OK is returned, with content of default.opencraft.com …
=> [SE-2948] Remove redirect to preliminary page

frontend/packages/api_client/src/models/ThemeSchema.ts, frontend/src/console/components/RedeploymentToolbar/styles.scss, instance/schemas/theming.py
Rename logistration-action-btn to logistration-btn as console expects all identifiers to be deterministic.
**JIRA Ticket:** [SE-2955](https://tasks.opencraft.com/browse/SE-2955)
1. Setup OCIM with [this branch](https://github.com/open-craft/edx-simple-theme/tree/mavidser/se-2955-fix-ui-toggle) of edx-simple-theme.
2. Make changes to logistration button via console, verify the UI on the deployed appserver.
(Verified on stage - Instance 5290)
**Reviewers:**
[ ] @mtyaka
=> [SE-2955] Fix logistration toggle issue in the new console

frontend/src/console/components/NoticeBoard/NoticeBoard.spec.tsx, frontend/src/console/components/NoticeBoard/NoticeBoard.tsx, frontend/src/console/components/NoticeBoard/__snapshots__/NoticeBoard.spec.tsx.snap, frontend/src/console/components/NoticeBoard/displayMessages.ts, frontend/src/utils/testing.tsx, registration/api/v2/views.py, registration/tests/test_api.py
This is a follow-up PR with fix for https://github.com/open-craft/opencraft/pull/591. It adds fix for notifications endpoint and message for `Status & Notification` page when user has no instance.
- [BB-2450](https://tasks.opencraft.com/browse/BB-2450)
1. Register, but don't verify email.
2. Go to `Status & Notifications` page.
3. You should see message like on screenshot.
**Reviewers**
=> [BB-2450] Fix server error

frontend/src/global/constants.ts, frontend/src/ui/components/Header/Header.tsx
Adds a FAQ page based on the document mentioned in the ticket, and adds a link to the said page on the header.
**JIRA ticket**: SE-2211
Homepage with link to the page:
~The FAQ page:~ This page has been removed, and instead the link would be to a opencraft.com page
- Checkout this branch.
- Enter new frontend subdirectory: cd frontend
- Build Ocim API client: `./scripts/build-api-client.sh`
- Reinstall dependencies: `npm install`
- Run frontend, npm start.
- Go to http://localhost:3000/
- You should see the link to FAQ on the header, which takes you to the FAQ page.
**Reviewers:**
=> SE-2211 Add FAQ page

documentation/howtos.md
Removes deprecated `nginx_discovery_gunicorn_hosts`  from *Configuring Ecommerce and Course Discovery* documentation. 
That variable has been last seen in gingko, [sneak a peek here](https://github.com/open-craft/configuration/blob/opencraft-release/ginkgo.1/playbooks/roles/nginx/templates/edx/app/nginx/sites-available/discovery.j2#L12-L16).
**JIRA tickets**: SE-2878
1. Build the documentation for Ocim.
1. Make sure the changes done to the markdown file appear online.
**Reviewers**
=> [SE-2878] Removes Deprecated nginx_discovery_gunicorn_hosts Variable from Docs

opencraft/settings.py, pr_watch/tasks.py, pr_watch/tests/test_tasks.py
[SE-2743](https://tasks.opencraft.com/browse/SE-2743)
This change allows for the PR watch task to be disabled in environments where it is not needed.
NOTE: Stage will need a new environment variable to use this feature, `WATCH_PRS=false`
=> SE-2743: Create a setting to disable monitoring of PRs.

documentation/monitoring.md, instance/models/mixins/openedx_monitoring.py, instance/newrelic.py, instance/tests/models/test_openedx_monitoring_mixins.py, instance/tests/test_newrelic.py, opencraft/settings.py
NRQL makes alerting much more flexible.
The main change for now is that alerts are triggered only after any of the Synthetic monitors fails three times in a row to avoid alerts due to temporary networks blips.
1. If you don't already have `ADMINS` setting set in your local `.env` file, set it to your email (ie. `ADMINS='[["Matjaz Admin", "matjaz@opencraft.com"]]'`.
1. Set `NEWRELIC_ADMIN_USER_API_KEY` and `NEWRELIC_LICENSE_KEY` in your local `.env` file. You can find them on the production Ocim VM's `.env` file.
1. Start the django shell (`make shell`).
1. Get a reference to an `OpenEdXInstace` (or create a new one if you don't have an existing instance in your devstack).
1. Run `instance.enable_monitoring()`. Make sure that there are no errors.
1. Log into NewRelic …
=> Use NRQL conditions instead of Synthetics.

instance/admin.py
The `get_inline_instances` method should return a list of
admin classes to inline.
Previously, it was modifying `self.inlines`, which is a
static class variable, causing weird behaviour. Sometimes,
the inline admin was not included for existing instances.
- visit `/admin/instance/openedxinstance/`
- click 'add open edx instance'
- verify that the instance reference inline form is **not** included at the bottom of the page
- find an existing instance and edit it
- verify that the instance reference inline form **is** included at the bottom of the page
**Reviewers**:
=> SE-3079 bugfix: conditional instance ref inline admin

documentation/howtos.md, instance/models/mixins/openedx_config.py, opencraft/settings.py
Updated default settings to use Juniper release and also fixed an issue with the forum heartbeat on Juniper.
- [BB-2801](https://tasks.opencraft.com/browse/BB-2801)
**Dependencies**:
This PR depends on:
2. https://github.com/open-craft/ansible-secrets/pull/196
1. Deploy the changes and verify that a working Juniper instance is spawned.
**Reviewers**
=> [BB-2801] Update default Open EdX release to Juniper

instance/models/mixins/openedx_config.py
Configuration changes to address issues noted during Juniper upgrades.
**Use secure cookies with default SameSite=None policy**
7401806 Updates the default instance configuration to set:
```yaml
EDXAPP_CSRF_COOKIE_SECURE: true
EDXAPP_SESSION_COOKIE_SECURE: true
```
**Forum dependencies build error**
Loss of a pinned dependency in cs_comments_service requires using our custom branch until the issue is merged upstream.
679dd78 Applies this for juniper and ironwood deployments.
**Sandbox**
* LMS: https://se3154.sandbox.stage.opencraft.hosting/
* Studio: https://studio.se3154.sandbox.stage.opencraft.hosting/
Deployed to Ocim stage, see sandbox links above.  Since we don't have LetsEncrypt certificates set up for stage instances, you'll have to accept the self-signed …
=> SE-3154 + SE-3175 Updates for Juniper auth and forum issues

instance/models/mixins/openedx_config.py, instance/models/mixins/openedx_site_configuration.py, instance/tests/models/test_openedx_appserver.py, instance/tests/models/test_openedx_instance.py, instance/tests/models/test_openedx_site_configuration_mixin.py
This PR is about updating marketing links for edx instances.
It is enough to update ENV variable `MKTG_URL_OVERRIDES` to have empty 'BLOG' key.
It require to add such value `"CONTACT_US_CUSTOM_LINK":"/contact"` to the `SiteConfiguration` ([related edx-platform code here](https://github.com/edx/edx-platform/blob/master/lms/djangoapps/branding/api.py#L285)) 
When OpenEdXInstance create full configuration object, it use ansible.dit_merge function to merge all configs. 
[This function ignore list and just replace it](https://github.com/open-craft/opencraft/blob/master/instance/ansible.py#L78) without going through list items and copying one by one.
So if instance.configuration_extra_settings doesn't have  `EDXAPP_SITE_CONFIGURATION` [hardcoded …
=> SE-3056 Update marketing links

opencraft/tests/test_views.py, opencraft/urls.py, opencraft/views.py
Adds a health check endpoint to OCIM which verifies the postgres, redis and consul connections.
**JIRA tickets**: [SE-3021](https://tasks.opencraft.com/browse/SE-3021)
- Run `make test.unit`
- Make sure postgres, redis and consul are running, then visit `/health_check` URL on ocim. Now take down services one by one and verify the non-200 response from the health check page.
**Author notes**:
- If postgres is unavailable then the view isn't even called as ocim fails at trying to log the request in the database. I've still added the verification code to the view in case the logging behaviour ever changes in the future.
**Reviewers**
=> Add a health check endpoint to ocim

instance/management/commands/instance_statistics_csv.py, instance/tests/management/test_instance_statistics_csv.py, opencraft/settings.py, playbooks/collect_activity/collect_activity.yml, playbooks/collect_activity/stats.py, playbooks/collect_instance_statistics/collect_elasticsearch_data.yml, playbooks/collect_instance_statistics/query_elasticsearch.py, reports/tasks.py
Modifies the `instance_statistics_csv` command to allow for multiple domains. Also uses this new version in a new task to send a trial instances report to emails set in `settings.TRIAL_INSTANCES_REPORT_RECIPIENTS`
[BB-2883](https://tasks.opencraft.com/browse/BB-2883)
Test on functionality on staging:
1. Generate the public SSH key for `www-data@stage.manage.opencraft.com`  using `ssh-keygen -y -f ~/.ssh/id_rsa`
2. Add public key to `authorized_keys` file on `logs.opencraft.com`
3. Set `INSTANCE_LOGS_SERVER_HOST` to `logs.opencraft.com` in `.env` file on `stage.manage.opencraft.com`
4. Run
```
make manage -- instance_statistics_csv --domains daniel.stage.opencraft.hosting,piotr.stage.opencraft.hosting,gabrieltesting.stage.opencraf …
```
=> BB-2883 Allow instantce_statistics_csv to receive multiple domains; Create trial_instances_report on cronjob

frontend/packages/api_client/src/models/ThemeSchema.ts, frontend/src/console/components/ButtonCustomizationPage/ButtonCustomizationPage.tsx, instance/schemas/theming.py
Reverts #12 changes and adds special handling for logistration toggle name to preserve compatibility with forked themes.
**JIRA Ticket:** [SE-2955](https://tasks.opencraft.com/browse/SE-2955)
1. Add this branch to OCIM's settings while using this [PR branch](https://github.com/open-craft/opencraft/tree/mavidser/se-2955-fix-ui-toggle).
2. Make changes to logistration button via console, verify the UI on the deployed appserver.
**Sandbox**: https://mavidser.stage.opencraft.hosting/
**Reviewers:**
[ ] @mtyaka
=> [SE-2955] Undo rename of logistration toggle button

instance/models/mixins/openedx_monitoring.py, instance/tests/models/test_openedx_monitoring_mixins.py
This PR is adding client instance name to New Relic monitoring condition name to be able to find root cause of incidents faster and improve the investigation experience. In case the name is too long, it will be truncated due to limitations.
1. If you don't already have `ADMINS` setting set in your local `.env` file, set it to your email (ie. `ADMINS='[["Gabor Admin", "gabor@opencraft.com"]]'`.
2. Set `NEWRELIC_ADMIN_USER_API_KEY` and `NEWRELIC_LICENSE_KEY` in your local `.env` file. You can find them on the production Ocim VM's `.env` file.
3. Start the django shell (`make shell`).
4. Get a reference to an `OpenEdXInstace` (or create a new one if you don't have an existing instance in your …
=> [SE-3136] Add client instance name to New Relic monitoring condition name

frontend/package-lock.json, frontend/package.json, frontend/src/console/components/RedeploymentToolbar/RedeploymentToolbar.tsx, frontend/src/global/constants.ts, frontend/src/index.tsx, frontend/src/registration/actions.ts, frontend/src/registration/components/CongratulationsPage/CongratulationsPage.tsx, frontend/src/ui/components/App/App.tsx, frontend/src/utils/MatomoTracker.tsx
This PR implements Matomo tracking in the Ocim frontend. The tracking data will be sent to the Matomo instance configured at build-time using the `REACT_APP_MATOMO_BASE_URL` environment variable. If it is not configured, the frontend will not perform any tracking using Matomo at all.
* Check out the source branch of this PR.
* Install the JavaScript library dependencies by running `npm install` from the `frontend/` directory.
* Build the Ocim API client by running the `build-api-client.sh` script inside the `scripts` directory.
* Start the Ocim backend application inside the devstack vagrant VM by running `make dev.up`.
* Set up a local Matomo instance by using `docker-compose` and the below contents in a `docker-compose.yml` file.
```yaml
---
version: "2" …
```
=> [BB-2859] Implement Matomo tracking in Ocim

instance/models/mixins/openedx_database.py
We upgraded MongoDB authentication method to [SCRAM](https://docs.mongodb.com/manual/core/security-scram/), so we can revert the temporary hack introduced in #626.
Merging this as a trivial PR.
=> Revert "[BB-2558] Temporarily set default `FORUM_MONGO_AUTH_MECH` to `MONGODB-CR`"

instance/tasks.py, instance/tests/test_tasks.py, opencraft/settings.py
This PR introduces a new periodic task, that deletes old beta test users.
**JIRA tickets**: https://tasks.opencraft.com/browse/BB-2164
~~**Discussions**:~~
~~**Screenshots**:~~
~~**Sandbox URL**:~~
**Merge deadline**: "None"
1. Create couple of beta test instances
2. Set ``INACTIVE_OLD_BETATEST_USER_DAYS = 1``
3. Set ``DELETE_OLD_BETATEST_USER_DAYS = 1`` 
4. Manually change ``BetaTestApplication.created`` to an old date
5. Manually change corresponding user's ``last_login`` to an old date
6. Delete deployed instances, keep ``BetaTestApplication`` model instance
7. Run Huey 
8. Users should be inactive now.
9. Change ``UserProfile.modified`` to an old date
10. Run Huey
11. Users will be deleted, also all data with ``on_delete=CASCADE`` will …
=> [BB-2164] Erase Ocim trial user data after X months

instance/models/openedx_appserver.py, instance/tests/models/test_openedx_site_configuration_mixin.py
This PR introduce new merge function for `EDXAPP_SITE_CONFIGURATION` settings. 
This instruction is meant to be run locally:
1. Create a new OpenEDXInstance
2. Open OCIM django shell `make shell`
3. Get created instance: 
```python
>>> instance = OpenEdXInstance.objects.last()
```
4. Create new appserver (without spawning actual deployment, we are care only about app server final configuration)
```python
>>> instance._create_owned_appserver()
```
5. Open UI, check that `Combined ansible vars -> EDXAPP_SITE_CONFIGURATION` looks like this:
```yaml
EDXAPP_SITE_CONFIGURATION:
- values:
CONTACT_US_CUSTOM_LINK: /contact
```
6. Open instance settings (django admin page `http://localhost:5000/admin/instance/openedxinstance/`)
7. Update `Configuration extra settings`: …
=> SE-3222 Extend EDXAPP_SITE_CONFIGURATION with default values

circle.yml
This PR pins the Circle CI NodeJS executor image for the builds. More information: https://app.circleci.com/pipelines/github/open-craft/opencraft/2458/workflows/16b471ff-14fb-423f-9827-456afdea68d8/jobs/22889
**JIRA tickets**: N/A
**Screenshots**: N/A
**Sandbox URL**: N/A
N/A
NA
**Reviewers**
=> ci: pin circleci nodejs executors

instance/models/mixins/utilities.py, instance/tests/models/test_mixin_utilities.py, instance/tests/models/test_openedx_instance.py
Fix the most relevant log collection and attach all the Ansible produced logs to the email. Also, make sure that the configuration is sent as an attachment instead of a plain text within the email.
**Structure of the email**
```
Subject: Deployment failed at instance: {instance_name}
Body:
The periodic deployment of {edx_platform_release} failed. Please see the details below.
 
Ansible task name: {ansible_task_name}
Relevant log lines:
{relevant_log_entry}
 
AppServer ID:                     {appserver_id}
Latest successful provision date: {latest_successful_provision_date}
Configuration source repo:        {configuration_source_repo_url}
Configuration version:            {configuration_version}
OpenEdX platform source repo:     {edx_platform_repository_url}
OpenEdX platform release: …
```
=> [SE-3470] Adjust periodic build failure email content

instance/models/mixins/openedx_config.py
On October 23, 2020, edX dropped python 2.7 support for the `ecommerce-worker`, [cf commit](https://github.com/edx/ecommerce-worker/commit/20538c829cd3e2068f29e449496c0df3244640cf)
After further investigation, we noticed that the `ecommerce-worker` is tagged similarly to how other releases for other edX repositories are tagged (ie `open-release/juniper.3`)
Ocim sets a default `ECOMMERCE_VERISON`; however, it does not set a default `ECOMMERCE_WORKER_VERSION`. This PR adds `ECOMMERCE_WORKER_VERSION` to the default configuration.
**JIRA tickets**: SE-3585
**Discussions**: [EdX Ecommerce Worker Drops Support for Python 2.7](https://forum.opencraft.com/t/edx-ecommerce-worker-drops-support-for-python-2-7/704?u=nizar)
1. Attempt to provision an …
=> [SE-3585] Specifies ecommerce worker version to openedx release

instance/models/mixins/utilities.py, instance/tests/models/test_mixin_utilities.py, instance/tests/models/test_openedx_instance.py
This PR makes sure that we send more verbose logs to be able to provide more context.
Also, I found an additional issue with getting the previous app server, which is fixed by this PR too.
**Screenshots**: NA
**Sandbox URL**: N/A
1. Checkout this code on stage environment
2. Create an instance
3. Enable periodic builds on the instance
4. Add your email address to the Periodic build notification emails text field
5. Set 00:05:00 as build interval (5 minutes)
6. Misconfigure it to no be able to provision (for example change a database password or similar to have build logs and not fail immediately)
7. Wait for the email (check your spam folder as well) - It should arrive in 5-10 minutes based on the delay in the queue
8. Check the email has no sensitive data and …
=> [SE-3619] improve notification emails

instance/models/openedx_deployment.py, instance/tests/models/test_openedx_deployment.py, registration/api/v2/views.py, registration/tests/test_api.py
This fixes a bug where deployments where the first deployments allowed to be cancelled. This PR also adds a is_successfully_deployed flag which is used to prevent user deployments if the first deployment never succeeded.
**JIRA tickets**: [SE-3517](https://tasks.opencraft.com/browse/SE-3517)
1. Register as a new P&T user on OCIM
2. Verify the email to start provisioning
3. Verify that you are not allowed to make new changes while the instance is being provisioned (neither before the appserver was created, nor after the appserver was created as there's a few mins of gap between the two depending on the queue size).
4. Terminate the first appserver being created - and make sure that the UI still doesn't allow the user to deploy changes (we wat a staff member to fix …
=> Prevent new deployments until first P&T instance is provisioned

requirements/base.in, requirements/base.txt, requirements/dev.in, requirements/dev.txt, requirements/test.in, requirements/test.txt
Address security flaw by updating cryptography dependency in base.in, dev.in, and test.in then running pip-compile.
~~I checked for accessibility issues~~
~~Includes documentation~~
=> Update cryptography dependency

instance/models/mixins/openedx_config.py, instance/models/mixins/openedx_database.py, instance/tests/models/test_openedx_database_mixins.py, instance/tests/models/test_openedx_instance.py
This updates instance settings so that instances continue to work correctly using RabbitMQ as the Celery backend. This change is required since https://github.com/edx/configuration/pull/6147 switched to local Redis for native install.
We will switch to Redis in Ocim when we implement support for a Redis backend with ACLs, but for now this makes it possible to keep using RabbitMQ.
I spawned two servers on Ocim stage:
- Juniper: https://stage.manage.opencraft.com/instance/6540/
- master: https://stage.manage.opencraft.com/instance/6530/
Check the instances to make sure they work correctly and the configuration looks good. You can use the default `staff@example.com` account.
Note: Celery tasks don't seem to be working on the master sandbox, but I think that's related …
=> Update Celery configuration to keep using RabbitMQ as the backend

.readthedocs.yml, documentation/requirements.in, documentation/requirements.txt
This PR fixes the failing Read the docs build for Ocim documentation (hosted at https://ocim.opencraft.com) by adding a `.readthedocs.yml` configuration file which explicitly configures the build.
Without this PR, RTD was trying to install the requirements from the top-level requirements file and failing because the MySQL client library required a MySQL client package to be installed. This is now fixed by configuring RTD to install only the requirements file under the `documentation` directory,
1. Check and verify that https://ocim.opencraft.com/en/guruprasad-bb-3528-fix-readthedocs-builds/ has all the documentation present in the `documentation/` directory of this repository.
2. Compare with the documentation at https://ocim.opencraft.com/ which has some of the …
=> Add .readthedocs.yml for configuring Read the docs build

instance/models/mixins/openedx_config.py, registration/tests/test_api.py
This merge request is about resolving an issue with MKTG_URL_LINK_MAP override.
**Testing instructions**  
- Create a new instance
- Create new appserver
- Verify that key `EDXAPP_MKTG_URL_LINK_MAP` in `Combined ansible vars:` exists
- This key should contain all default pages
- Set yaml to the `configuration_extra_settings`
```yaml
EDXAPP_MKTG_URL_LINK_MAP:
HONOR: !!null
BLOG: !!null
DONATE: !!null
```
- Create new appserver
- Check that key `EDXAPP_MKTG_URL_LINK_MAP` in `Combined ansible vars:` was updated in regards to `configuration_extra_settings`
**Author's notes and concerns**  
- These changes will work for already existed instances
**Reviewers**
=> SE-3629 Store MKTG_URL_LINK_MAP in EDXAPP_MKTG_URL_LINK_MAP

instance/models/mixins/openedx_config.py
It is required to be able to set up custom certificate templates.
1. Spawn a new appserver.
2. Verify that the `ORGANIZATIONS_APP` flag is enabled in `EDXAPP_FEATURES`.
You can check [the appserver](https://stage.manage.opencraft.com/instance/6700/edx-appserver/3005/) I created on stage after deploying this update.
=> [FAL-23] Enable ORGANIZATIONS_APP feature flag by default.

instance/models/mixins/openedx_config.py, registration/tests/test_api.py
Reverts open-craft/opencraft#675
The reason we're reverting this change can be found in [this mattermost discussion](https://chat.opencraft.com/opencraft/pl/hfbbprnk6iyf8n53oqx1tk87cy)
This will result in breaking the integration tests again, so we'll need to include them again in the next change cc @s0b0lev
=> Revert "SE-3629 Store MKTG_URL_LINK_MAP in EDXAPP_MKTG_URL_LINK_MAP"

instance/models/mixins/openedx_config.py
Enabling the organizations app means that users have to go to django admin and create organizations before they can start creating new courses in the Studio. We don't want users to have to fiddle with django admin before being able to use the Studio.
This reverts commit 9bd5fe47177d87af54889e0b3b63e52df585a8fe.
=> Revert "[FAL-23] Enable ORGANIZATIONS_APP feature flag by default."

instance/newrelic.py, instance/tests/test_newrelic.py, opencraft/settings.py
This check checks for failure instead of success.
This check also makes sure that ~3~ 2 consecutive failures happened before creating an alert/violation.
Once ~3~ 2 alerts happen in the matter of ~16~ 11 minutes, a violation will be opened. In order to guarantee the alert is closed, we use the 'loss of signal' or 'signal expiration'. If we don't have any signal for a duration of ~16~ 11 mins, ie no failed request for ~16~ 11 mins, it means that all issues were resolved, so close the violation.
**JIRA tickets**: SE-3953
**Screenshots**: 
* Opening Alert:
* Closing Alert:
**Sandbox Instance**: [Sandbox Instance](https://manage.opencraft.com/instance/22310/)
1. Open [NewRelic Synthetic Summary](https://one.newrelic.com/launcher/nr1-core.explorer?pane=eyJuZXJkbGV0SWQi …
=> [SE-3953] Updates NewRelic policy to check for failure instead

frontend/src/global/constants.ts, frontend/src/ui/components/App/__snapshots__/App.spec.tsx.snap, frontend/src/ui/components/Footer/Footer.tsx, frontend/src/ui/components/Footer/__snapshots__/Footer.spec.tsx.snap, frontend/src/ui/components/Footer/displayMessages.ts, frontend/src/ui/components/Footer/styles.scss
The footer is updated and following links are added
- How we work (OpenCraft website)
- Support (help page)
- Contact (contact link)
- Privacy Policy (Privacy policy link)
**JIRA tickets**: BB-3499
**Merge Deadline**: None
**Screenshots**
Footer before:
Footer after:
1. Checkout this PR
2. Set environment variable `PRIVACY_POLICY_LINK` to https://opencraft.com/privacy-policy/
3. Set environment variable `OPENCRAFT_WEBSITE_LINK` to https://opencraft.com/
3. Open the OCIM frontend and check that clicking Privacy Policy in footer takes you to https://opencraft.com/privacy-policy/
4. Check that clicking "How we work" in footer takes you to https://opencraft.com/
4. Check that the frontend design matches the wireframe in ticket BB-3499 and …
=> [BB-3499] Update footer

instance/models/mixins/utilities.py, instance/tests/models/test_openedx_instance.py
Changes the build success/fail email subject as requested by Ned [here](https://discuss.openedx.org/t/how-do-we-build-continuous-integration-for-the-supported-installation/3065/30?u=0x29a)
**JIRA Tickets**: BB-3517
**Discussions**: https://discuss.openedx.org/t/how-do-we-build-continuous-integration-for-the-supported-installation/3065/30?u=0x29a
**Testing Instructions**:
1. Checkout to this PR
2. ssh to the vagrant box
3. run `make test.one instance.tests.models.test_openedx_instance.OpenEdXInstanceTestCase` and check all the tests pass
4. In file instance/models/mixins/utilities.py check that the email subjects are according to [this comment](https://discuss.openedx.org/t/how-do-we-build-continuous-integration-for-the-supported-installation/3065/30?u=0x29a) …
=> BB-3517 Change build success/fail email subject

instance/models/mixins/rabbitmq.py, instance/tests/models/test_openedx_database_mixins.py
This PR changes the RabbitMQ provisioning for instances by adding all permissions to 'admin' on every vhost created.
**JIRA tickets**: BB-3501
1. Check out this branch in OCIM Stage.
2. Spin a new instance and start provisioning a new AppServer.
3. Go to the Stage RabbitMQ management console (or SSH) and check the 'admin' user has permissions to access the vhost created for that instance.
=> BB-3501 Add permissions to rabbitmq vhost for admin

frontend/src/console/components/ConsolePage/ConsolePage.tsx, frontend/src/console/components/ConsolePage/__snapshots__/ConsolePage.spec.tsx.snap, frontend/src/console/components/ConsolePage/displayMessages.ts, frontend/src/console/components/Hero/__snapshots__/Hero.spec.tsx.snap, frontend/src/console/components/InstanceSettings/__snapshots__/InstanceSettings.spec.tsx.snap, frontend/src/console/components/Logos/__snapshots__/Logos.spec.tsx.snap, frontend/src/console/components/NoticeBoard/__snapshots__/NoticeBoard.spec.tsx.snap, frontend/src/console/components/ThemeButtons/__snapshots__/ThemeButtons.spec.tsx.snap, frontend/src/console/components/ThemeFooter/__snapshots__/ThemeFooter.spec.tsx.snap, frontend/src/console/components/ThemeNavigation/__snapshots__/ThemeNavigation.spec.tsx.snap, frontend/src/console/components/ThemePreviewAndColors/__snapshots__/ThemePreviewAndColors.spec.tsx.snap, frontend/src/ui/components/App/__snapshots__/App.spec.tsx.snap, frontend/src/ui/components/CustomStatusPill/CustomStatusPill.tsx, frontend/src/ui/components/CustomStatusPill/DeploymentIndicator.spec.tsx, frontend/src/ui/components/CustomStatusPill/DeploymentIndicator.tsx, frontend/src/ui/components/CustomStatusPill/__snapshots__/DeploymentIndicator.spec.tsx.snap, frontend/src/ui/components/CustomStatusPill/index.ts, frontend/src/ui/components/CustomStatusPill/util.ts, frontend/src/ui/components/Header/Header.tsx, frontend/src/ui/components/Header/__snapshots__/Header.spec.tsx.snap, frontend/src/ui/components/Header/displayMessages.ts, frontend/src/ui/components/Header/styles.scss
This PR improves the Console UI header by re-organizing menu items for better usability.
**JIRA tickets**: https://tasks.opencraft.com/browse/BB-3498
**Discussions**: None
**Screenshots**: 
**Sandbox URL**: N/A
1. Checkout this PR
2. Run Ocim - if vagrant stack, login to VirtualBox via - ``vagrant ssh`` and run ``make run.dev``
3. Run frontend from frontend folder - ``npm install && npm start``
4. Log in to the Ocim console.
5. On Desktop - the header should contain the ``Customize``, ``My site(LMS)`` link, and an accounts dropdown menu with a user icon.
6. ``My site(LMS)`` shows a link icon on the right.
7. ``My site(LMS)`` shows a deployment status indicator on left.
8. On Mobile / Smaller screens - A hamburger …
=> [BB-3498] Implement user menu and rework page header

circle.yml, instance/tests/integration/factories/instance.py, playbooks/collect_activity/collect_activity.yml, playbooks/collect_activity/stats.py
This reverts commit https://github.com/open-craft/opencraft/commit/853f9953ca2abe8c7be3726663f26b19ad6377ca. This is causing integration tests to fail as the default release of OCIM is still Juniper.
=> Revert "Fix Koa integration tests (#682)"

instance/models/mixins/openedx_config.py
Description
------------
This PR changes the forum repository and branch used to deploy new instances.
It replaces the upstream `open-release/juniper.master` with our own `opencraft-release/juniper.3` repo/branch.
Testing
--------
1. Check out this branch on a Stage or Dev environment.
1. Create an [instance](https://bb3387-forum-juniper-3.stage.opencraft.hosting/).
1. Spawn a new AppServer for the new instance.
1. Wait for provisioning to check out the forum code and check the correct repo/branch have been used.
=> [BB-3387] Use forum common branch for Juniper

frontend/src/ui/components/App/__snapshots__/App.spec.tsx.snap, frontend/src/ui/components/Header/Header.tsx, frontend/src/ui/components/Header/__snapshots__/Header.spec.tsx.snap, frontend/src/ui/components/Header/displayMessages.ts
We're fulfilling the following user story:
> "As a OCIM developer, I want to make the page be aware of logged in status of user so that I can help the user to go to console"
In the Congratulations page, the user is actually logged in, but the page header shows the Login button. Make it aware that the user is logged in and change the text to “go to console”.
**JIRA tickets**: [BB-3594](https://tasks.opencraft.com/browse/BB-3594)
**Screenshots**: See Jira ticket
**Merge deadline**: "None" 
1. Pull this branch to your local OCIM environment.
2. Make the suggested change below on `src/registration/components/CongratulationsPage/CongratulationsPage.tsx`, line 37, and test logging in, out and changing the suggested `true` to `false`: 
```
{true && ( …
```
=> [BB-3594] Header Login button is aware of auth token

frontend/src/global/constants.ts, frontend/src/ui/components/App/__snapshots__/App.spec.tsx.snap, frontend/src/ui/components/Footer/Footer.tsx, frontend/src/ui/components/Footer/__snapshots__/Footer.spec.tsx.snap
Currently both the Contact Us link on the frontend home page and the Support Request link in the frontend console point to the same destination. We separate the two so that the Support Request link can instead go to OpenCraft's Contact Us form instead.
**JIRA tickets**: BB-3516
1. Checkout this PR
2. Set the environment variable `REACT_APP_SUPPORT_LINK` to 'https://opencraft.com/contact-us/'
3. Login to OCIM frontend and check that clicking Support Request now takes you to 'https://opencraft.com/contact-us/'
4. Make sure the Contact Us button on the homepage is unaffected and does not take you to 'https://opencraft.com/contact-us/'
**Reviewers**
=> [BB-3516] Change link for Support Request button in Ocim console

frontend/src/console/components/Logos/Logos.tsx, frontend/src/console/components/Logos/styles.scss, frontend/src/ui/components/ImageUploadField/ImageUploadField.tsx, frontend/src/ui/components/ImageUploadField/styles.scss
Because class names collided on different PRs, we see a bug in the Tooltips styles:
We're fixing it to:
=> [BB-3701] Bugfix: Colliding className from Logo and CustomStatusPill components

instance/management/commands/kill_zombies.py, instance/tasks.py, instance/tests/management/test_kill_zombies.py, opencraft/settings.py
We want to set up a periodic task for the `kill_zombies` command.
Requirements summarized after discussion:
- Frequency configurable via ~environment variables~ django settings (opencraft/settings.py)
- Defaults to once a day
- Call the kill_zombies management command using call_command
- Have a reasonable threshold (that is configurable) and if the number of VMs to be deleted exceeds that we should alert by sending an email to the ops@opencraft.com
- Have a settings toggle (configurable via environment variables) to disable the job
`kill_zombies` has no tests, so we convened on testing the following for the periodic task:
- Picks up and applies all the proposed ~env variables~ settings
- Sends email if we're over the threshold
- Sends email on failure
- Invokes the management command to …
=> [BB-3775] Setup periodic task to kill zombie app servers

instance/models/mixins/openedx_config.py, instance/models/mixins/openedx_static_content_overrides.py, instance/models/openedx_appserver.py, registration/api/v2/serializers.py, registration/models.py, registration/tests/test_api.py
This PR is about resolving conflicts for the **MKTG_URL_LINK_MAP** configuration.
The issue with the previous implementation happens for juniper.3 release. 
- https://github.com/open-craft/edx-platform/blob/opencraft-release/juniper.3/common/djangoapps/edxmako/shortcuts.py#L93
For testing master branch was used. 
- https://github.com/edx/edx-platform/blob/master/common/djangoapps/edxmako/shortcuts.py#L96
This PR was tested on both environments and work fine for master and juniper.3 .
**Testing instruction:**
- Follow testing instruction in the ticket details 
**Authors notes:**
- Included API client updates 
- Instead of injecting the full list into MKTG_URL_LINK_MAP - this code will add only disabled pages
=> FAL-78 Fix the MKTG_URL_LINK_MAP override 

instance/ansible.py, instance/ansible_callbacks/prettify.py, instance/static/html/instance/appserver.html, instance/static/js/src/openedx_appserver.js, instance/static/scss/instance.scss, instance/tests/integration/ansible/requirements.txt, instance/tests/js/instance_app_spec.js, instance/tests/test_ansible.py
**Description**
This tweaks ansible output to make it valid JSON in more cases than the defaults.
It then uses some JS on the frontend to identify and pretty-print JSON fragments in ansible output.
**Screenshot**
**Testing**
This was deployed to stage, so you can check the logs of appservers that were spawned when the code was active on stage. You can use these two:
- https://stage.manage.opencraft.com/instance/7420/edx-appserver/3170/
- https://stage.manage.opencraft.com/instance/7400/edx-appserver/3171/
**Reviewers**
=> [FAL-873] Prettify ansible output

instance/models/mixins/openedx_database.py, instance/tests/models/test_openedx_instance.py
Set `DEFAULT CHARACTER SET` to `utf-8` for `openedx_database` creating command, because default character set on the server is `latin1`, not `utf-8`
According to review:
https://github.com/open-craft/opencraft/pull/672#discussion_r598963816
**JIRA Ticket** [SE-4282](https://tasks.opencraft.com/browse/SE-4282)
1. Pull this branch
2. Run command in terminal to recreate db: `honcho run python3 manage.py recreate_db   --domain=artem.stage.opencraft.hosting    --admin="Your Name"    --reason="Testing latest changes in pull request"`
None
@nizarmah Sorry for this, but I renamed this branch to include my name, so #751 was automatically closed.
=> SE-4282 add db DEFAULT CHARACTER SET

frontend/src/utils/setup_tinymce.ts
This pull request is about importing TinyMCE icons in `setup_tinymce.ts` so that the `icons.js` file is also compiled by `react-scripts` (`webpack`).
**Jira tickets**
- [FAL-1742](https://tasks.opencraft.com/browse/FAL-1742)
TBA
**Reviewers**
- @mtyaka
=> [FAL-1742] Import TinyMCE icons to compile them

frontend/src/newConsole/components/ThemeNavigationPage/ThemeNavigationPage.spec.tsx, frontend/src/newConsole/components/ThemeNavigationPage/ThemeNavigationPage.tsx, frontend/src/newConsole/components/ThemeNavigationPage/__snapshots__/ThemeNavigationPage.spec.tsx.snap, frontend/src/newConsole/components/ThemeNavigationPage/displayMessages.ts, frontend/src/newConsole/components/ThemeNavigationPage/index.ts, frontend/src/newConsole/components/ThemeNavigationPage/styles.scss, frontend/src/newConsole/components/index.ts, frontend/src/routes/console.tsx
Adds new ThemeNavigationPage for newConsole and
move the Color Picker components to the sidebar
**JIRA Tickets** [BB-3870](https://tasks.opencraft.com/browse/BB-3870) [Gitlab#722](https://gitlab.com/opencraft/dev/opencraft/-/issues/722)
2. Run OCIM frontend and backend dev servers.
3. Make sure that a test instance is created in OCIM admin.
4. Visit http://localhost:3000/console/theming/navigation
5. Make sure that all the elements are present in Sidebar.
6. Verify that changing `ColorInputField` values changes the theme data in `BetaTestApplication`
**Author Notes**
1. This PR is dependent on #719 for Static Page previews.
**Screenshot**
Version 1
Update:
Version 2 (updated titles)
Version 3 (with tooltips)
=> BB-3870 Add ThemeNavigationPage for newConsole

frontend/src/console/components/CoursesManage/__snapshots__/CoursesManage.spec.tsx.snap, frontend/src/console/components/CustomizationSideMenu/displayMessages.ts, frontend/src/console/components/ThemeColors/styles.scss, frontend/src/newConsole/components/ColorsComponent/ColorsComponent.spec.tsx, frontend/src/newConsole/components/ColorsComponent/ColorsComponent.tsx, frontend/src/newConsole/components/ColorsComponent/__snapshots__/ColorsComponent.spec.tsx.snap, frontend/src/newConsole/components/ColorsComponent/displayMessages.ts, frontend/src/newConsole/components/ColorsComponent/index.ts, frontend/src/newConsole/components/ConsoleHome/__snapshots__/ConsoleHome.spec.tsx.snap, frontend/src/newConsole/components/PreviewBox/style.scss, frontend/src/newConsole/components/ThemeNavigationPage/__snapshots__/ThemeNavigationPage.spec.tsx.snap, frontend/src/newConsole/components/index.ts, frontend/src/newConsole/components/newConsolePage/ConsolePage.tsx, frontend/src/newConsole/components/newConsolePage/__snapshots__/ConsolePage.spec.tsx.snap, frontend/src/newConsole/components/newConsolePage/styles.scss, frontend/src/newConsole/components/newCustomizationSideMenu/CustomizationSideMenu.tsx, frontend/src/newConsole/components/newCustomizationSideMenu/__snapshots__/CustomizationSideMenu.spec.tsx.snap, frontend/src/routes/console.tsx, frontend/src/ui/components/App/styles.scss, frontend/src/ui/components/Main/styles.scss
Implements Colors Edit page with ThemeColors component moved to the Sidebar.
**Related Tickets** [BB-3787](https://tasks.opencraft.com/browse/BB-3787) [Gitlab#715](https://gitlab.com/opencraft/dev/opencraft/-/issues/715)
**Testing Instructions**:
2. Run the frontend server using `npm run start`
3. Visit http://localhost:3000/newconsole/theming/colors/edit
4. Verify that the page looks according to the [design](https://app.zeplin.io/project/5ea850e04326be273e4bcf5a/screen/6040a3f3e3a09417c18ff8bb) in general.
**Screenshots**
Updated Screenshot after outline page
**Author Notes**
1. The Save button is left out of this implementation. See [this comment](https://tasks.opencraft.com/browse/BB-3787?focusedCommentId=192903&page=com.atlassian.jira.plugin.system.issuetabp …
=> [BB-3787] [NewConsole] Move color component to sidebar

documentation/howtos.md
The configuration example now only updates the currency in the default mode (audit)
and doesn't mix it with changing the default mode to honor as it can be
confusing for those who don't want to do that.
Since I didn't want to use `honor` mode as the default mode for the client instance I set up for [BB-3806](https://tasks.opencraft.com/browse/BB-3806), I assumed that the configuration can be skipped and that lead to an outage of sorts :)
=> [BB-3801] Fix the course mode defaults in the ecommerce alternative currency howto

instance/tests/integration/ansible/playbooks/failignore.yml, instance/tests/integration/ansible/playbooks/failure.yml
We started using Ubuntu 20.04 image for integration tests. It doesn't have `python-minimal` package.
Test instructions:
1. Verify that all CI checks passed.
=> Remove installing of Xenial-specific packages

e2e_tests/tests/test_password_reset.py, instance/models/openedx_appserver.py, playbooks/enable_bulk_emails/enable_bulk_emails.yml
This PR fixes deprecated in recent `edx-platform` way to import LMS application. Also, it adds gating flag to `enable_bulk_emails.yml`, so we can disable this playbook for new instances on older releases, which don't support new import style.
Also, second commit fixes typo because of which `e2e-tests` CI step was flaky.
- [FAL-51](https://tasks.opencraft.com/browse/FAL-51)
**Discussions**:
- [MatterMost thread](https://chat.opencraft.com/opencraft/pl/cazshxzz7b8j7jg7gtb5k4r4me).
1. Check extra configuration of [this instance](https://stage.manage.opencraft.com/instance/7700/) and ensure that it has `ENABLE_BULK_EMAILS` equal to `false`.
2. Open Ansible logs for the app server and check that task with `Create BulkEmailFlag object with enabled …
=> Allow disabling of bulk emails 

frontend/src/console/components/Hero/Hero.spec.tsx, frontend/src/console/components/Hero/Hero.tsx, frontend/src/console/components/Hero/__snapshots__/Hero.spec.tsx.snap, frontend/src/console/components/Hero/styles.scss, frontend/src/console/components/ThemePreview/ThemePreview.tsx, frontend/src/console/components/ThemePreview/__snapshots__/ThemePreview.spec.tsx.snap, frontend/src/newConsole/components/ButtonsCustomizationPage/__snapshots__/ButtonsCustomizationPage.spec.tsx.snap, frontend/src/newConsole/components/ColorsComponent/__snapshots__/ColorsComponent.spec.tsx.snap, frontend/src/newConsole/components/PreviewBox/PreviewBox.tsx, frontend/src/newConsole/components/PreviewBox/__snapshots__/PreviewBox.spec.tsx.snap, frontend/src/newConsole/components/ThemeNavigationPage/__snapshots__/ThemeNavigationPage.spec.tsx.snap, frontend/src/newConsole/components/newConsolePage/ConsolePage.tsx, frontend/src/newConsole/components/newConsolePage/__snapshots__/ConsolePage.spec.tsx.snap, frontend/src/newConsole/components/newFooter/__snapshots__/ThemeFooterSideBar.spec.tsx.snap, frontend/src/newConsole/components/newLogos/__snapshots__/LogoSidebar.spec.tsx.snap
Updates hero page to conform to the new UI
**Related Tickets** [BB-3869](https://tasks.opencraft.com/browse/BB-3869) [Gitlab#721](https://gitlab.com/opencraft/dev/opencraft/-/issues/721)
2. Visit http://localhost:3000/console/theming/hero
3. Verify that the UI looks correct and matches [this mock](https://app.zeplin.io/project/5ea850e04326be273e4bcf5a/screen/5ffea861fa26d61b53abb3b9)
3. Verify that all the components from old Hero page are moved to sidebar.
4. Verify that updating values in sidebar gets reflected in `BetaTestApplication`
**Screenshots**
Hero Edit screen
=> [BB-3869] Update Hero page

documentation/howtos.md, instance/models/mixins/openedx_config.py, instance/tests/integration/factories/instance.py, opencraft/settings.py
This PR updates Ocim to use `opencraft-release/koa.3` branch for new instances and `integration-koa.3` branch for integration tests.
- [BB-4096](https://tasks.opencraft.com/browse/BB-4096)
**Dependencies**:
- https://github.com/open-craft/ansible-secrets/pull/264
Ensure that PR passed all CI pipeline checks.
**Reviewers**
=> [BB-4096] koa.2a -> koa.3

frontend/src/registration/components/RegistrationContainer/styles.scss
Fix the registration styling in the page
**JIRA tickets**: [BB-3786](https://tasks.opencraft.com/browse/BB-3786)
**Discussions**: [Mattermost](https://chat.opencraft.com/opencraft/pl/aeq3b9x8i7noxqsugnqd8mj58o)
**Screenshots**: 
Before:
After:
**Sandbox URL**: TBD - sandbox is being provisioned.
1. Set up the Devstack
2. Go to the registration page it should have the background image
This is a way to fix the current UI
**Reviewers**
=> fix: fixed the style for registration page

templates/emails/account_info_email.html, templates/emails/account_info_email.txt, templates/emails/welcome_email.html, templates/emails/welcome_email.txt
This pull request improves the contents of the automated emails that OCIM sends for marketing purposes, including links that can be tracked by Matomo and information more relevant to persons evaluating our offerings.
**JIRA tickets**: https://tasks.opencraft.com/browse/BIZ-1761
**Discussions**:  https://docs.google.com/document/d/1euEpAOcbRFfxgu280onYaV-7f4tCFvRFPivbUt6iHxI/edit?ts=607d5eba
1. Register for an account and take a look at the emails.
2. Verify the info isn't jumbled in your email client.
The original ticket mentions a third email which doesn't exist but was posited to. It's worth asking if this should be added, but it should probably be added by a dedicated developer task rather than by BizDev. …
=> [BIZ-1751] Improvements to email wording.

instance/factories.py, instance/tests/test_factories.py
Add extra asserts for when calling the instance factory methods
from the Django shell and there's no previous validation step involved.
This prevents domain names that are duplicates and only differ in case,
or domains with invalid characters in them which will cause problems
later in provisioning.
=> Check subdomain name validity for instance factories.

instance/models/mixins/openedx_config.py
[MNG-1938](https://tasks.opencraft.com/browse/MNG-1938)
This PR changes the default config for all our instances so that:
* Users stay logged in for a full year, not the default of two weeks
* Database-backed sessions ensure that users don't get logged out every time we deploy a new app server
The motivation for this is that I find it annoying to have to log in again every time I visit courses.opencraft.com.
This configuration has already been tested on the **courses.opencraft.com** Ocim instance, and it works: I stayed logged in for over two weeks and across app server deploys.
Some history:
> In OC-2096, the `SESSION_ENGINE` was changed (#258) but was later reverted (#271 ) due to possibly misplaced concerns about our (A) MySQL server (which at the time was a single server using …
=> Stay logged in to our instances [MNG-1938]

frontend/src/registration/components/RegistrationContainer/styles.scss, frontend/src/styles/_theme.scss, frontend/src/ui/components/ContentPage/styles.scss
Reused the style for background image
**JIRA tickets**: [BB-4143](https://tasks.opencraft.com/browse/BB-4143)
**Discussions**: [PR](https://github.com/open-craft/opencraft/pull/784#pullrequestreview-648083241)
~~**Dependencies**: None~~
~~**Sandbox URL**: TBD - sandbox is being provisioned.~~
~~**Merge deadline**: "None" if there's no rush, "ASAP" if it's critical, or provide a specific date if there is one.~~
1. Get the devstack running 
2. Check http://localhost:3000/registration/domain
3. Check the congratulation page as well
1. Instead of using the same class I went with mixin approach
**Reviewers**
=> fix: [BB-4143] Reused style in registration

playbooks/enable_bulk_emails/enable_bulk_emails.yml, registration/provision.py, registration/tests/test_provision.py
Copy draft static overrides when provisioning a new betatest instance.
We were already copying other configuration from the betatest app, but forgot about static overrides.
Copying everything ensures that the UI doesn't show any pending changes while the first appserver is being provisioned.
Ticket: [FAL-960](https://tasks.opencraft.com/browse/FAL-960)
1. Register a new account on Ocim stage and validate your email.
2. Your instance should start being provisioned.
3. Verify that the deployment toolbar says "Publishing" and that there are no pending changes.
4. Make some changes to your instance configuration.
5. Verify that the deployment toolbar now shows the number of pending changes.
**Reviewers**
=> [FAL-960] Copy static overrides to instance on creation

instance/models/openedx_appserver.py, instance/tests/models/test_openedx_appserver.py
If Ansible process exited with non-zero code, we want to stop celery workers, because they are stealing tasks from other, healthy app servers.
- [BB-4059](https://tasks.opencraft.com/browse/BB-4059)
**Sandbox URL**:
- https://stage.manage.opencraft.com/instance/7920/edx-appserver/3309/
What I did:
1. Created a [branch](https://github.com/open-craft/configuration/tree/0x29a/bb4059/stop_services_if_provision_failed) in `open-craft/configuration` repo with change that makes main playbook fail early.
2. Created [instance](https://stage.manage.opencraft.com/instance/7920) and configured it to use this branch.
3. Then I switched staging Ocim to `0x29a/bb4059/stop_services_if_provision_failed` branch and created …
=> [BB-4059] Stop all workers on appservers that failed provisioning

instance/models/mixins/openedx_config.py, opencraft/settings.py
Adds setting OPENEDX_ORACLEJDK_URL which is used
in appserver configuration variables as `oraclejdk_url`
**JIRA Ticket** [BB-4097](https://tasks.opencraft.com/browse/BB-4097)
TBD
=> BB-4097: Add setting OPENEDX_ORACLEJDK_URL

instance/tasks.py
This will prevent the cleanup task from aborting due to any exceptions
and missing the cleanup of all the remaining instances.
=> [BB-4226] fix: handle the exceptions when deleting the obsolete appservers

instance/tests/test_tasks.py
Makes the same adjustment that was created in https://github.com/open-craft/opencraft/pull/797 to the unit test which was failing because the mock logger wasn't being called with the updated string
=> [BB-4226] test: fixes test when terminating obsolete appservers

instance/api/openedx_appserver.py, instance/models/server.py, instance/tasks.py, instance/tests/models/test_server.py, instance/tests/test_tasks.py
Fixes two issues:
1. From Openstack package upgrade: an exception class was removed in favor of a more generic one.
2. Bug found while testing: Terminate VM is not a background task, which makes the web worker halt if the VM takes too long to shutdown (moved to a huey task).
This is currently deployed to stage.
**Reviewers:**
=> BB-4198: Fix issues with package upgrades.

instance/utils.py, opencraft/settings.py
This PR adds a fix for `Can't upgrade a READER transaction to a WRITER mid-transaction` issue during integration testing. This issue happens due to random failure thrown by OVH OpenStack API.
The solution provided is to retry on such failures. For example, the error mentioned above throws a 400 bad request error. We can retry all these errors with `Retry` provided in the `urllib3` package that `requests` uses. 
But the error mentioned above is thrown from a `POST` request and by default `Retry` doesn't retry on `POST` requests, to avoid multiple insertions. For our use case, we needed to override that by setting `method_whitelist`. 
- https://tasks.opencraft.com/browse/BB-4306
- Check there is no `Can't upgrade a READER transaction to a WRITER mid-transaction` error in integration test …
=> [BB-4306] Fix Can't upgrade a READER transaction to a WRITER mid-transaction issue

instance/management/commands/instance_statistics_csv.py, instance/tests/management/test_instance_statistics_csv.py, playbooks/collect_activity/stats.py, reports/tasks.py, reports/tests.py
This adds a task similar to the existing monthly report. It sends an email with the number of logged in users for the past month for each instance.
BB-4015
I have yet to test this on stage.
The management script can be run manually and it will generate a CSV.
The Huey task can be tested by setting it to run more frequently (on stage?) and check whether the results are ok.
It may make sense to refactor this, as the new periodic task is very similar of the existing one.
The crontab setting may need to be different so it does not reuse the exact same ones as the other report task.
=> [BB-4015] Monitor active users WIP

instance/management/commands/instance_statistics_csv.py
This will fix the syntax error when the 'instance_statistics_csv'
management command is invoked from the periodic tasks.
* Checkout the source branch of this PR in the production environment or on stage after setting the `INSTANCE_LOGS_SERVER_HOST` environment variable in the `.env` file.
* Run the `instance_statistics_csv` management command with one or more instance domains and the `--start-date`, `--end-date` parameters specified.
* Verify that the `collect_activity.py` script runs on the appservers of the given instances without any errors and returns proper values for the fields like `Total users`, `Total active users`, `Total courses`, etc.
=> [BB-4015] fix: add the missing space between the command flags

.dockerignore, .gitignore, Dockerfile.ocim, Makefile, docker-compose.yml, documentation/development/docker.md, documentation/installation.md, frontend/.dockerignore, frontend/Dockerfile, mkdocs.yml, requirements/dev.txt
This adds some basic infrastructure for developing OCIM inside docker containers.
It already makes it possible to run some of the dev workflow (e.g. tests and OCIM) in Docker and could be used as a starting point for running a dockerized OCIM in production.
Kudos to @janimo for the prior work on #740 
Follow the instructions in [docker.md](https://github.com/open-craft/opencraft/blob/joaocabrita/ocim_in_docker/documentation/development/docker.md)
=> feature: Added ability to run OCIM in a container.

instance/tests/models/factories/__init__.py, instance/tests/models/factories/rabbitmq_server.py, instance/tests/models/test_openedx_instance.py
This adds tests that verify new `OpenEdXInstance` instances are correctly assigned RabbitMQ instances that have `accepts_new_clients=True`.
* [BB-3729](https://tasks.opencraft.com/browse/BB-3729)
```sh
make test.one make test.one instance.tests.models.test_openedx_instance.OpenEDXInstanceRabbitMQTestCase
```
=> [BB-3729] Bug: OCIM allots a RabbitMQServer randomly and ignores the accepts_new_clients flag

documentation/operations/management-tasks.md, instance/management/commands/find_orphan_dbs.py, instance/models/mixins/openedx_database.py, mkdocs.yml
This adds a `find_orphan_dbs` management command that searches for databases that exist in a datastore but are not registered in the OCIM database.
I suspect this may happen because of some failure while deprovisioning databases (by either archiving or deleting the respective instances).
1. Create a MySQL database (`create database DB_NAME`)
2. `./manage.py find_orphan_dbs mysql --host MYSQL_HOST -u MYSQL_USER -p` (will be prompted for password)
3. Verify that `DB_NAME` is identified as orphan in `stderr`
4. Verify that correct SQL for dropping the database is generated to `stdout`
1. Create a MongoDB database (`use DB_NAME; db.insert({})`)
2. `./manage.py find_orphan_dbs mongo --host MONGO_HOST -u MONGO_HOST -p` (will be prompted for password)
3. Verify that `DB_NAME` is identified as …
=> feature: Added management command to find orphaned databases

instance/migrations/0141_features_to_features_extras.py
This fixes the migration introduced in #806 
I think the bug was missed in tests because `EDXAPP_FEATURES` is never used, so the code path in question is never exercised...
1. Apply all previous migrations `./manage.py migrate instance 0140`;
2. Create an `OpenEdXInstance` with `configuration_extra_settings = 'EDXAPP_FEATURES: { TEST_FLAG: true }'`;
Alternatively, use any environment that contains instances where `configuration_extra_settings` contains `EDXAPP_FEATURES`;
3. Apply migration: `./manage.py migrate instance`;
4. Verify that:
* before the fix it fails with `AttributeError: module 'yaml' has no attribute 'yaml'`
* after the fix it succeeds
* [BB-4230](https://tasks.opencraft.com/browse/BB-4230)
=> fix: Fixed usage of yaml.safe_load in migration

instance/models/mixins/openedx_site_configuration.py, instance/tests/models/test_openedx_appserver.py, instance/tests/models/test_openedx_site_configuration_mixin.py
[FAL-1937](https://tasks.opencraft.com/browse/FAL-1937)
OCIM doesn't set up the credentials service by default,
and learner records depends on the credentials service.
So, we need to also disable learner records by default.
**Sandbox**:
- LMS: https://fal-1937.stage.opencraft.hosting/
- Studio: https://studio.fal-1937.stage.opencraft.hosting/
- ocim: https://stage.manage.opencraft.com/instance/8070/
- launch a new instance with default config
- verify that the 'view my records' button is hidden on your profile page after logging in to the instance
**Reviewers**:
=> FAL-1937 Disable learner records by default

instance/migrations/0141_features_to_features_extras.py
* [BB-4230](https://tasks.opencraft.com/browse/BB-4230)
1. Create a OpenEdXInstance where `configuration_extra_settings = '   '` (or any other string with only whitespace);
2. Apply migration `manage.py migrate instance`
3. Rollback migration `manage.py migrate instance 0140`
This has already been done with [this staging instance](https://stage.manage.opencraft.com/instance/8150/)
=> fix: Fix migration when configuration_extra_settings is all whitespace

instance/ansible.py, instance/tests/test_ansible.py, opencraft/settings.py
This changes the default value of `ANSIBLE_PYTHON_PATH`
to "python", making it pick up whatever binary is in the
PATH.
For security reasons, this is not usually what you want
for production environments, so a check was created.
Related stories:
* [BB-3900](https://tasks.opencraft.com/browse/BB-3900)
h1. Testing
1. `./manage.py check --deploy` issues a warning if `ANSIBLE_PYTHON_PATH` is not set
=> feature: Change default `ANSIBLE_PYTHON_PATH` [BB-3900]

instance/models/server.py, instance/ssh.py, instance/tests/models/factories/server.py, instance/tests/models/test_server.py
This fixes the case where instance archival fails because the VM was already deleted from OpenStack.
Although the code in question already seemed to handle this, deleting the SSH key "covertly" queries the OpenStack API for IP addresses, which fails.
* [BB-4245](https://tasks.opencraft.com/browse/BB-4245)
This includes a new test that verifies the behavior:
```sh
./manage.py test --parallel 4 instance.tests.models.test_server.OpenStackServerTestCase.test_ignores_failure_to_delete_ssh_key
```
=> fix: Server archival no longer fails when delete SSH keys

instance/models/mixins/openedx_config.py
With koa, the tos and honor link in footer
are combined to one. To separate them TOS and HONOR
is set in EDXAPP_MKTG_URL_LINK_MAP to use static templates
[BB-4145](https://tasks.opencraft.com/browse/BB-4145)
1. Visit https://stage.manage.opencraft.com/instance/7770/edx-appserver/3310/
2. Verify that following configuration is present in appserver
```
EDXAPP_MKTG_URL_LINK_MAP:
HONOR: honor
TOS: tos
```
3. Verify that the instance runs on `koa`
4. Visit https://bb-4097.stage.opencraft.hosting/
5. Verify that the `ToS` and `Honor` links are separate
=> fix: Separate tos and honor mktg links

marketing/admin.py, marketing/utils.py
Adds extra context base_url, signature_name and
signature_title to the context of email templates.
- [BB-4368](https://tasks.opencraft.com/browse/BB-4368)
Including the testing instructions relative to stage OCIM server for easier testing.
1. Redeploy this branch to stage if not already deployed.
2. Visit [templates admin page](https://stage.manage.opencraft.com/admin/marketing/emailtemplate/)
3. Select template with id 2 ( `BB-4368 Test template` )
4. Select `Send sample` option and click `Go`.
5. Check you email inbox for received email and verify that the email does not have broken images.
=> fix: add extra context to template in marketing app

instance/models/appserver.py, instance/models/openedx_appserver.py, instance/tests/models/test_openedx_appserver.py
This fixes an issue where, if something failed while checking security group definitions on OpenStack, the machine state would be left in New; the user would only be able to tell the process failed in the UI by looking through the logs.
Now, the machine state is set to error.
* [BB-4387 (OpenCraft Private JIRA)](https://tasks.opencraft.com/browse/BB-4387)
```sh
./manage.py test instance.tests.models.test_openedx_appserver.OpenEdXAppServerTestCase.test_provision_security_group_check_failed
```
=> [BB-4387] When provisioning an App Server and security group checks fail, state is left in New

circle.yml, cleanup_utils/aws_cleanup.py, cleanup_utils/dns_cleanup.py, cleanup_utils/integration_cleanup.py, cleanup_utils/load_balancer_cleanup.py, cleanup_utils/mysql_cleanup.py, cleanup_utils/openstack_cleanup.py, documentation/development/ci.md, mkdocs.yml
This PR fixes the issues that were preventing the cleanup of some unused CI resources like MySQL databases, Gandi DNS records, etc.
It also changes the CircleCI workflow definitions to allow pushing to the `ci-cleanup` branch for running cleanup on-demand (similar to how `stage` is used for the frontend).
1. Push this branch to `ci-cleanup`
2. Verify the output of the `cleanup` job
* [BB-4378 (OpenCraft Private JIRA)](https://tasks.opencraft.com/browse/BB-4378)
=> [BB-4378] Fix CI cleanup issues

instance/models/mixins/openedx_theme.py, requirements/base.txt, requirements/dev.txt, requirements/test.txt
The [simple theme package](https://github.com/open-craft/edx-simple-theme/) now supports being installed as a theme package for MFEs. This change adds configuration to deploy it as an npm theme package by default.
=> feat: Adds an global NPM override to install the simple theme for any MFEs configured for an instance

periodic_builds/tasks.py, periodic_builds/tests/test_tasks.py
"Is archived" filter added in launch_periodic_builds function
**Jira ticket:** [FAL-2137](https://tasks.opencraft.com/browse/FAL-2137)
- On test_tasks.py of periodic_build, I added a filter to avoid get the archived instances
- Test updated to demonstrate that change in the function behavior
**How to test:**
- Create a test instance with the periodic build enabled.
- Test if the periodic build works normally.
- Archive the instance.
- Test if the periodic build is no longer performed.
=> [FAL-2137] Ocim: don't run periodic builds for archived instances

instance/management/commands/find_orphan_dbs.py
Apparently it was attempting to drop database `db` due to a missing interpolated variable.
* [BB-4255 (OpenCraft Internal)](https://tasks.opencraft.com/browse/BB-4255)
1. Run `./manage.py prune_orphan_dbs --rm mysql`
2. Confirm database deletion
=> fix: Dropping orphaned MySQL databases uses actual db name

documentation/development/console.md, frontend/src/console/actions.ts, frontend/src/console/components/Hero/Hero.tsx, frontend/src/console/components/Logos/Logos.tsx, frontend/src/newConsole/components/newLogos/LogoSidebar.tsx, mkdocs.yml
This adds handling for 413 Entity Too Large responses when uploading images.
* [BB-4447](https://tasks.opencraft.com/browse/BB-4447)
1. Apply the following configuration to NGINX (required to avoid CORS errors):
```
<html><head></head><body>
--
error_page 413 = @entity_too_large;
 
location @entity_too_large {
add_header 'Access-Control-Allow-Origin' $http_origin always;
add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS' always;
add_header 'Access-Control-Allow-Headers' 'Authorization,DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;
add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;
return 413;
}
 
</body></html>
```
2. Upload a large image (> 1 MB) using any of the console's configuration forms (e.g. …
=> [BB-4447] Handle 413 Entity Too Large responses when uploading images

frontend/.eslintrc.json, frontend/src/newConsole/components/newLogos/LogoSidebar.tsx, frontend/src/newConsole/components/newLogos/styles.scss, frontend/src/ui/components/ImageUploadField/ImageUploadField.tsx, frontend/src/ui/components/ImageUploadField/styles.scss, frontend/src/ui/components/TextInputField/TextInputField.tsx
This adds pruned down versions of `ImageUploadField` and `TextInputField` that are easier to style.
It also makes some style tweaks to make things more consistent.
* [BB-4446 (OpenCraft Internal)](https://tasks.opencraft.com/browse/BB-4446)
1. Go to "Logo" section in console;
2. Verify that all input heading are consistent.
=> [BB-446] fix: Make form field labels consistent in Logos page

instance/management/commands/instance_statistics_csv.py, opencraft/settings.py
This PR adds a new column to the report generated by instance_statistics_csv, which is called by `send_all_instances_report` to generate a report on all instances and then send it to the recipients defined by
`settings.TRIAL_INSTANCES_REPORT_RECIPIENTS`.
Also this PR changes the default recipient for this report  to `contact@opencraft.com`
https://tasks.opencraft.com/browse/BB-4532
- Deploy this branch on stage
- Set external_lms_domain in some instances
- Run `instance_statistics_csv` command, and check that the values in the generated `csv` are correct
=> feat: [BB-4532] Add new column to report containing external lms domain, and change default report recipient

instance/newrelic.py, instance/tests/test_newrelic.py
- See https://discuss.newrelic.com/t/422-client-error-unprocessable-entity-when-creating-nrql-conditions-for-existing-policies/165928
- We saw: `422 Client Error: Unprocessable Entity`
- I ran `curl -X POST 'https://api.newrelic.com/v2/alerts_nrql_conditions/policies/1677272.json' -H 'X-Api-Key: …' -i -H 'Content-Type: application/json' -d @~/data.json` with that payload, and saw: `terms[].time_function must be 'any' if value is set to 'sum'`
- `any` means „at least once“, according to [the documentation](https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/rest-api-alerts/alerts-conditions-api-field-names/). In the UI, while checking other monitors ([e.g.](https://onenr.io/0LZQWBogkjW)) I see they mention „at least once“ (e.g. `Sum of SyntheticCheck …
=> [FAL-2545] [WIP] Use 'any' instead of 'all' in NewRelic monitoring conditions

instance/models/mixins/storage.py, instance/tests/management/test_reprovision_buckets.py, instance/tests/models/test_openedx_storage_mixins.py, instance/tests/models/utils.py
PR for https://tasks.opencraft.com/browse/SE-4911
Behavioral specifications
"When the user provisions a new app server, if S3 is already provisioned and the bucket already exists, the logs should indicate that the bucket already exists instead and Ocim shouldn't provision a new bucket."
N/A
N/A
N/A
* checkout the changes on stage
* create a new instance
* start a new app server
* check the output to see the logs are containing the bucket creation
* after the bucket creation, terminate the app server
* start a new app server
* check the output to see the logs are containing "Bucket <bucket name> already exists"
ASAP
N/A
=> [SE-4911] Test bucket existence before creation

instance/management/commands/deprovision_buckets.py, instance/tests/management/test_deprovision_buckets.py
When deprovisioning S3 bucket for an instance, we need to check for both
the instance and bucket names. In case of any of them meet the
conditions, we must deprovision the related bucket.
Related PRs:
* https://github.com/open-craft/opencraft/pull/848
N/A
* Run the command on stage and prod using the `--dry-run` flag
* Check for the output for any suspicious instance name
* Run the commands without the `--dry-run` flag
* Check that the AWS buckets are removed
ASAP
A new `--dry-run` option is added beside the fix to ensure we can run the command without any harm.
=> [SE-5006] fix: deprovision s3 buckets with better filtering

marketing/signals.py, marketing/tests/test_register_subscriber.py, registration/approval.py, registration/signals.py, registration/tests/test_approval.py, registration/tests/utils.py
This PR is fix for a bug identified in OCIM application, where a paying client would get an end of trial reminder email after they launched a new appserver
[BB-5077](https://tasks.opencraft.com/browse/BB-5077)
1. Register a new trial instance in OCIM
2. Once the first app server is ready, delete the corresponding entry created in Subscribers table from the Django admin page
3. Launch a new appserver from console
4. After the new appserver is up and ready, check that there should be no new entry in the Subscribers table
"None"
=> [BB-5077] fix: End of trial email sent to paying customer

instance/gandi.py
We use a global lock to ensure that only one process at a time is modifying DNS records.
By default the lock never expires, which means that if Ocim crashes before being able to release the lock, DNS operations contiinue being locked indefinitely even when Ocim comes back up.
We need to put a timeout on the DNS operation to avoid this from happening.
**Notes**:
I did not bother adding a test for this change since I don't think it's worth the trouble.
Properly testing this would be very hard -- you'd have to kill Ocim while it was performing a DNS operation and then verify that the lock gets released eventually. I don't think it's worth going through that kind of trouble for such a small change.
It should be sufficient to verify that spawning new instances and …
=> [SE-5121] Set an expiry time on the DNS operation lock.

instance/models/openedx_appserver.py, instance/newrelic.py, instance/tests/test_newrelic.py
This PR implements the monitoring changes introduced by NewRelic and causes provisioning issues.
* check out the branch on Ocim stage
* run `OpenEdXInstance.objects.get(id=965).enable_monitoring()` in shell
* validate the monitoring items are set correctly in NewRelic
* validate that no critical or warning messages shown
=> [SE-5391] refactor: activate app servers before setting dns

documentation/operations/archival-process.md
This change add the archival process documentation into `Operations > Archival Process`.
You can follow the documentation in order to archive some instance in Ocim.
None
=> [BB-5517] Added documentation for archival process

instance/newrelic.py, instance/tests/test_newrelic.py, opencraft/settings.py
The current monitoring is set for the legacy NewRelic infrastructure, though NewRelic improved its event aggregation and monitoring. As part of this patch, the aggregation method, window and delay has been changed in order to provide more reliable alerting and reduce the number of false positive alerts.
The default values of settings are updated, since we didn't set the desired behaviour previously. We wanted to be alerted if an issue exists for 10 minutes but calculate with some event delays, so the alert time was set to 11 minutes. At that time, we had no better option as the `aggregation_delay` and `event_flow` aggregation type did not exist. Now that we have these extra settings, we can be alerted if the issue persists for 10 minutes plus we wait for some time (20% of the …
=> [SE-5426] reconfigure NewRelic monitoring

instance/models/mixins/openedx_database.py, instance/models/mixins/redis.py
This PR fixes redis key prefix composition issues which put a `_` at the end of the single beat identifier, which shouldn't happen.
* [How identifier is composed](https://github.com/akachanov/single-beat/blob/master/singlebeat/beat.py#L21)
N/A
* Check that https://temp-lilac.opencraft.hosting/admin/instructor_task/instructortask/  is produced 1 minute tasks until March 31, 2022, 9:14 a.m.
ASAP
=> fix: ensure singlebeat identifier set correctly
