Makefile
Procfile
Procfile.dev
README.md
Vagrantfile
debian_db_packages.lst

Rebase and squash of https://github.com/open-craft/opencraft/pull/12

Changes to help run under Vagrant on Windows

---

instance/github.py
instance/migrations/0036_auto_20151112_1122.py
instance/models/instance.py
instance/tasks.py
instance/tests/test_tasks.py
opencraft/settings.py
pylintrc

This commit sets the Ansible configuration repo and fork from the extra settings given in the PR body, and falls back to a default configured in the Django settings if none is given.

Refactor settings for the fork and branch of the Ansible configuration repo.

---

.env.test
Makefile
README.md
bin/bootstrap
circle.yml
debian_db_packages.lst
debian_packages.lst
instance/github.py
instance/migrations/0036_external_databases.py
instance/migrations/0037_merge.py
instance/migrations/0038_merge.py
instance/models/instance.py
instance/tasks.py
instance/templates/instance/ansible/mongo.yml
instance/templates/instance/ansible/mysql.yml
instance/tests/factories/pr.py
instance/tests/integration/factories/instance.py
instance/tests/integration/integration_instance.py
instance/tests/models/test_instance.py
instance/tests/test_github.py
instance/tests/test_tasks.py
opencraft/settings.py
opencraft/tests/utils.py
requirements.txt

This is an updated version of #11.

External databases

---

instance/gandi.py
instance/models/instance.py
instance/static/html/instance/index.html
instance/static/scss/instance.scss
instance/tests/test_gandi.py

Fix a few display and spelling bugs.  For testing, follow the instructions in the [README file](https://github.com/open-craft/opencraft/blob/master/README.md) and create an instance – either via the Django admin, or using the Python shell (run `make shell` in the Vagrant box):
```
>>> from instance.tests.models.factories.instance import OpenEdXInstanceFactory
>>> OpenEdXInstanceFactory()
```

Correct position of status icons and fix typo.

---

README.md

You have to use `OpenEdxInstance.objects.create`, you can't instatiate the instance first and save it later.

Fix shell instructions

---

instance/models/instance.py
instance/tests/models/test_instance.py

This ensures that we don't end up with zombie VMs when provisioning fails because of a bug in the Instance Manager.

Terminate servers on unhandled exception during provisioning

---

instance/migrations/0042_add_instance_status.py

Follows up on #57.
With the previous version of the migration, instance states were getting updated multiple times and ended up being set to `Terminated` if an instance had one or more servers with status `Terminated` associated with them.
Actual results when running migrations were:
```
Instance 66: Running, Server: Ready
Instance 71: Terminated, Server: Ready
Instance 79: Running, Server: Ready
Instance 90: Terminated, Server: Ready
Instance 104: Running, Server: Ready
Instance 126: Terminated, Server: Ready
Instance 127: Terminated, Server: Ready
Instance 146: Configuration failed, Server: Ready
Instance 170: Terminated, Server: Ready
Instance 172: Terminated, Server: Ready
Instance 176: Terminated, Server: Ready
Instance 177: Terminated, Server: Ready
Instance 178: Configuration …
```

Fix migration that introduces instance states.

---

deploy/.gitignore
deploy/README.md
deploy/requirements.yml

Only thing to review here is 22a6d0f882760878d0aee3528e6481f986341ea4 . Rest was reviewed by me as part in #68

Force SSL on deployed IM

---

instance/models/server.py
instance/static/html/instance/appserver.html
instance/static/html/instance/details.html
instance/static/html/instance/index.html
instance/static/js/src/openedx_appserver.js
instance/static/scss/instance.scss

This PR contains several UI tweaks.

Minor UI tweaks

---

deploy/requirements.yml

Adds SSL support. See https://github.com/open-craft/ansible-opencraft/pull/3 and https://github.com/open-craft/ansible-opencraft/pull/5.

Update opencraft ansible role

---

README.md

I forgot to do this in https://github.com/open-craft/opencraft/pull/99.

Document new relic settings in README

---

instance/newrelic.py
instance/tests/models/test_openedx_instance.py
instance/tests/models/test_openedx_monitoring_mixins.py
instance/tests/test_newrelic.py

Follow-up to #143.
Makes sure that the process for shutting down an instance does not fail if the New Relic monitors associated with the instance no longer exist.
1. Temporarily set `NEWRELIC_LICENSE_KEY` and `NEWRELIC_ADMIN_USER_API_KEY` in your `.env` (check OC IM prod config for appropriate values). This is to make sure that the `DELETE` request performed by `delete_synthetics_monitor` does not fail with authentication errors.
2. Start the shell via `make shell`.
3. Create a new instance:
```python
from instance.factories import instance_factory
instance = instance_factory(name="Instance with fake monitors", sub_domain="instance-fake-monitors")
```
4. Associate a single running app server with the instance. This is to make sure that `is_shut_down` does not …

When deleting New Relic monitors, don't fail if monitor can't be found.

---

instance/tests/integration/ansible/playbooks/failignore.yml
instance/tests/integration/ansible/playbooks/failure.yml
instance/tests/integration/factories/instance.py
playbooks/collect_activity/collect_activity.yml

This pull request updates our integration tests to use Ficus, rather than Eucalyptus, which no longer works due to missing dependencies.

Update integration tests to use Ficus

---

instance/templates/instance/ansible/vars.yml

Companion PR for https://github.com/open-craft/configuration/pull/20
@smarnach @bradenmacdonald

Added fallback DNS servers

---

README.md

Adds details about github access token scopes and user membership requirements to README
**JIRA tickets**: OC-2983
**Reviewers**

Adds details about github access tokens to README

---

README.md
circle.yml
instance/admin.py
instance/management/commands/instance_redeploy.py
instance/models/mixins/openedx_database.py
instance/templates/instance/ansible/mysql.yml
instance/tests/integration/factories/instance.py
instance/tests/management/test_instance_redeploy.py
opencraft/settings.py
requirements.txt

Adds a management task for redeploying Open edX Instances in bulk.
**JIRA issue**: OC-2834, OC-2838
See the README changes in this PR for usage instructions.
**Reviewers**

Adds the instance_redeploy management task

---

instance/api/instance.py

This avoids loading all unneeded columns of OpenEdXAppServer models.
Before using `only`:
After using `only`:

Use .only() to reduce the amount of information read from DB in the instances list API

---

instance/models/load_balancer.py

As noted in [this comment](https://github.com/open-craft/opencraft/pull/240#pullrequestreview-73602130), we currently don't honour the lock to prevent concurrent LB configurations.  We try to grab it, but run the LB reconfiguration regardless of whether we succeeded.  This patch fixes this bug.

Actually skip LB reconfiguration if we can't grab the lock.

---

README.md

Super tiny change, noticed it as reading through `README.md`.

Fix broken link to OpenStack docs.

---

README.md

Setting up ecommerce/discovery sandbox for a client, and so this PR fixes some formatting issues and broken links in the existing documentation, and updates it to provide some more information.
However, even though this was just a README change, the CircleCI tests weren't passing.  So subsequent commits were dedicated to fixing the incompatibilities between the latest firefox and selenium, and adding a geckodriver dependency.
**Reviewer**

WIP: Updates the docs for how to set up ecommerce and discovery

---

README.md

@UmanShahzad This is a small documentation fix I made while addressing review comments on #304, but it somehow didn't make it into the repo – I must have messed up with amending commits and pushing.  Could you please take a quick look?

Document Ansible installation for Vagrant.

---

instance/models/mixins/storage.py
instance/tests/models/test_openedx_storage_mixins.py

I've added retries to the s3 bucket creation, IAM keys may take a bit to be propagated across amazon servers after they are created.
Testing
-------
1- Create a new instance with AWS enabled and a spawn a new app server, check that bucket is created (check the number of attempts that were done, there should be logs about this).

Add retries to S3 bucket creation

---

instance/tests/js/spec/javascripts/support/jasmine.yml

Experiment with a delay before running failing tests

Fix flaky Jasmine tests in CircleCI

---

instance/management/commands/migrate_ephemeral.py
instance/tests/management/test_migrate_ephemeral.py

@itsjeyd 
I decided to extract the management command to a separate branch to make it easier to run the tests.
This PR is just for code reviewing, as I have moved from synchronous to async provisioning.

Add migrate_ephemeral management command

---

instance/templates/instance/memcached/memcached.nomad

This PR contains the changes I needed to make the Memcache deployment work with Consul Connect.
Currently Consul Connect isn't well integrated with Nomad, so it's necessary to run the proxy manually.  This proved a bit tricky, since we want the memcached process to only listen on the loopback device, while the Consul Connect proxy of course needs to listen on the public network interface.  I did not find any way to convince Nomad to use different IP addresses for different tasks, and [this issue](https://github.com/hashicorp/nomad/issues/646) suggests that this is currently outright impossible.  This made it impossible for me to register a correct Consul health check for the memcached process, which we need to make sure the process is operational and gets rescheduled if it is down.  For …

Update memcached jobspec to include Consul Connect proxy.

---

instance/tests/models/factories/openedx_appserver.py
instance/tests/models/test_openedx_instance.py
opencraft/settings.py
opencraft/urls.py
reports/apps.py
reports/helpers.py
reports/templates/report.html
reports/tests.py
reports/urls.py
reports/views.py
userprofile/admin.py

TASK: [SE-125](https://tasks.opencraft.com/browse/SE-125)
In this PR you need to test the following:
Description | Developed | Tested
:---|:---:|:---:
New Django app and URLs for issuing reports. | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
Custom links for users in the Admin panel to view their reports. | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> |
Filtering data for an organization, and for a particular month (URL only in this task). | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> 
Generate invoices, by computing the number of days to bill. | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul> 
Show only relevant AppServers (The ones that were active in the period). | <ul><li>- [x] </li></ul> | <ul><li>- [ ] </li></ul>
Simple HTML report, that can be …

(SE-125) Sandbox billing: basic report

---

README.md

Fixes: https://github.com/open-craft/opencraft/issues/393
(re-opening of https://github.com/open-craft/opencraft/issues/394)

hint about where to run the python lines to create instances

---

email_verification/__init__.py
email_verification/templates/email_verification/email.txt
email_verification/templates/email_verification/verify.html
opencraft/settings.py
registration/templates/registration/registration.html
registration/templates/registration/welcome_email.txt
registration/tests/test_views.py
static/scss/pages/_page.scss

This PR updates the text in various places as specified in the ticket description and the attached document.
Testing this PR on stage will also require the changes in the ansible-secrets PR linked to the ticket to be done.
* Deploy the changes in this branch and update the `.env` file based on the changes in the `ansible-secrets` PR.
* Test the whole registration workflow by registering as a new user for a sandbox and verify that the text matches the text specified in the requirements document.

[BB-1384] Update Ocim user registration confirmation text strings

---

instance/models/utils.py
instance/tests/models/test_utils.py

This PR removes code related to the old K/V format and operations that used Consul transactions.
Since we don't usually have Consul set up locally, this testing should be performed on stage.
1. Deploy this branch on Ocim Stage.
2. Go into Ocim shell and pick one active instance and run (don't forget to change `some-instance` to an instance with active appservers):
```
x = OpenEdXInstance.objects.get(internal_lms_domain__contains='some-instance')
```
3. Check the consul key related to that instance on [Consul web interface](https://haproxy-stage-1.net.opencraft.hosting:18500/ui/dc1/kv/ocim/instances/148/edit) (username: consul, password: [here](https://github.com/open-craft/ansible-secrets/blob/master/host_vars/haproxy-stage-1.net.opencraft.hosting.yml#L24)).
4. …

BB-1542: Remove old K/V format support

---

instance/models/mixins/openedx_config.py

- forum heartbeat path changed in  https://github.com/edx/edx-platform/commit/2839851bde247a3d33db1133048e0442341204f2
- need to add default celery heartbeat check here too since we're
overriding it from the default HEARTBEAT_EXTENDED_CHECKS.
**JIRA tickets**: 
**Sandbox URL**: TBD
1. run ocim from this branch
2. launch a new open edx instance
- default extra settings
- (openedx revision newer than https://github.com/edx/edx-platform/commit/2839851bde247a3d33db1133048e0442341204f2 )
- configuration branch https://github.com/edx/configuration/pull/5400
3. visit /heartbeat?extended=true on the new instance and verify that both the
forum and celery heartbeat checks are present and successful.
**Author notes and …

SE-1463 Update default extended /heartbeat checks

---

instance/ansible.py
instance/factories.py
instance/models/openedx_appserver.py
instance/tests/models/test_openedx_appserver.py
instance/tests/models/test_openedx_database_mixins.py
instance/tests/models/test_openedx_instance.py
instance/tests/models/test_openedx_secret_key_mixins.py
instance/tests/models/test_openedx_storage_mixins.py
instance/tests/models/test_openedx_theme_mixins.py
instance/tests/test_ansible.py
instance/tests/test_factories.py
pr_watch/github.py
pr_watch/tests/test_models.py
pr_watch/tests/test_tasks.py

See https://msg.pyyaml.org/load for why this change is happening.
This is a drive-by PR not related to any ticket.

Use Loader=SafeLoader for PyYAML

---

documentation/installation.md

- Add missing information
- Minor punctuation fixes

Update OCIM installation documentation

---

frontend/src/auth/actions.ts
frontend/src/console/components/ConsolePage/ConsolePage.tsx
frontend/src/global/api.ts
frontend/src/registration/actions.ts
frontend/src/registration/components/AccountSetupPage/displayMessages.ts
frontend/src/registration/components/CongratulationsPage/displayMessages.ts
frontend/src/registration/components/RedirectToCorrectStep/displayMessages.ts
frontend/src/registration/components/RegistrationPage/displayMessages.ts
frontend/src/ui/components/StepBar/displayMessages.ts
frontend/src/ui/components/TextInputField/TextInputField.spec.tsx
frontend/templates/component/displayMessages.ts
registration/provision.py
registration/tests/test_provision.py

This PR fixes multiple bugs and addresses a few review comments.
**To make the review easier, review the changes by commit, and not all at the same time.**
**Setup instructions:**
2. Run Ocim as usual.
3. Navigate to `frontend/` in a new console window.
4. Run `npm install`, then `./scripts/build-api-client.sh`.
5. Run `npm start` to run the frontend.
**(REMOVED) Testing instructions:** 
https://github.com/open-craft/opencraft/commit/9255d9b61e6485b655de78410b62019a25057636:
1. Create a betatest account and instance.
2. Manually change the appserver status to provisioned.
3. Make some changes to variables.
4. Click on the `Deploy` button in the user toolbar.
5. Check that the status was update just after the request finished.
This was removed from this PR, too …

BB-2179: Multiple bug fixes & addressing implementation review comments

---

documentation/monitoring.md

Fix a trivial spelling mistake in the monitoring doc.

SE2116: Fix spelling mistake in monitoring doc

---

frontend/src/auth/components/LoginPage/LoginPage.tsx
frontend/src/auth/components/LoginPage/__snapshots__/LoginPage.spec.tsx.snap
frontend/src/console/components/InstanceSettings/InstanceSettings.tsx

This PR adds a usability enhancement and a bug fix.
For 00353b7:
1. Run this branch.
2. Go to the login page (http://localhost:3000/login).
3. Type in username and password, then press `Enter`.
For 1a93649:
1. First, checkout `new-console` branch to see the issue.
2. Run Ocim + frontend.
3. Make sure you have a betatest instance set up.
4. Login to the new console (http://localhost:3000/login).
5. You'll be redirected to the `Instance settings` page, check that the fields are filled in.
6. Go to the `Theme preview and colors` page, and then back to the `Instance settings` page again.
7. Check that the fields are empty.
8. Switch to this branch, repeat 5-6 and check that the fields are properly filled.
**Reviewer:**

BB-2179: Fixes and improvements

---

requirements.in
requirements.txt

[BB-2288] Upgrade requirements

---

frontend/src/console/components/ConsolePage/styles.scss
frontend/src/console/components/FooterPreview/FooterPreview.tsx
frontend/src/console/components/FooterPreview/__snapshots__/FooterPreview.spec.tsx.snap
frontend/src/console/components/FooterPreview/styles.scss
frontend/src/console/components/Hero/Hero.tsx
frontend/src/console/components/Hero/__snapshots__/Hero.spec.tsx.snap
frontend/src/console/components/Logos/Logos.tsx
frontend/src/console/components/Logos/__snapshots__/Logos.spec.tsx.snap
frontend/src/console/components/PreviewComponent/__snapshots__/PreviewComponent.spec.tsx.snap
frontend/src/console/components/RedeploymentToolbar/RedeploymentToolbar.spec.tsx
frontend/src/console/components/RedeploymentToolbar/RedeploymentToolbar.tsx
frontend/src/console/components/RedeploymentToolbar/__snapshots__/RedeploymentToolbar.spec.tsx.snap
frontend/src/console/components/ThemePreviewAndColors/__snapshots__/ThemePreviewAndColors.spec.tsx.snap
frontend/src/console/models.ts
frontend/src/global/api.ts
frontend/src/routes/console.tsx
frontend/src/styles/_theme.scss
frontend/src/ui/components/CustomStatusPill/CustomStatusPill.tsx

This PR fixes a few bugs and inconsistencies in theming in one of multiple pages and also a bug which caused a infinite loop.
bfaa87a:
1. Log in the console.
2. Open Chrome tools, edit the access and refresh token (put invalid values, not empty ones).
3. Check that there's no infinite loop and you're redirected to the login page.
6936715:
1. Log in the new console, check that you are redirected to the theme preview and colors page.
2. Click through all pages in the side menu, and check that there's no weird resizing or changes in scale happening.
3. Check that the header image covers the entire header.
3b027a9:
1. Check that the footer preview component is correctly displayed.
d909aeb:
1. Log in the console.
2. Hijack the backend code to test the multiple …

BB-1848: Fix styling consistency and expired token issue.

---

instance/newrelic.py
instance/tests/test_newrelic.py

**Issue**: [BB-2387](https://tasks.opencraft.com/browse/BB-2387)
**Testing Instructions**:
* Try getting the details of any monitor
* Try creating a new monitor and checking the SSL flag is marked in the monitor
* Try deleting a monitor
**Reviewers**:

[BB-2387] Changed version for Synthetics API to support SSL options.

---

instance/tests/api/test_openedx_appserver.py

This fixes a bug in which the unit tests try to access S3, unavailable when running unit tests.

Add missing service mocks

---

documentation/howtos.md
instance/tests/integration/factories/instance.py
instance/tests/integration/integration_instance.py
playbooks/collect_activity/collect_activity.yml
playbooks/collect_activity/stats.py

This PR fixes four issues that I've encountered during running CI using Juniper instances.
- [BB-2801](https://tasks.opencraft.com/browse/BB-2801)
**Dependencies**:
https://github.com/open-craft/configuration/tree/integration-juniper
Passing of all CI checks is enough.
**Reviewers**

[BB-2801] Fix integration tests for Juniper

---

documentation/howtos.md
instance/tests/integration/factories/instance.py
opencraft/settings.py

This pull request is about updating the default branch to `juniper.3`.
**Jira ticket**
- [SE-3333](https://tasks.opencraft.com/browse/SE-3333)
**Dependencies**
This PR depends on: open-craft/ansible-secrets#209
1. Deploy the changes and verify that a working Juniper (`juniper.3`) instance is spawned.
**Author notes and concerns**
n/a
**Reviewers**

[SE-3333] Update default branch to juniper.3

---

instance/static/scss/instance.scss

Change z-index for notification class

---

circle.yml
instance/tests/integration/factories/instance.py
playbooks/collect_activity/collect_activity.yml
playbooks/collect_activity/stats.py

This PR fixes koa integration tests.
**JIRA tickets**: https://tasks.opencraft.com/browse/BB-3314
~~**Discussions**: ~~
**Dependencies**: https://github.com/open-craft/configuration/pull/146
~~**Screenshots**: ~~
~~**Sandbox URL**:~~
~~**Testing instructions**:~~
~~**Author notes and concerns**:~~
**Reviewers**

[BB-3314] Fix koa integration tests

---

instance/models/mixins/storage.py
instance/tests/models/test_openedx_storage_mixins.py

When deprovisioning S3 and the instance's S3 bucket does not exist, we should treat the 404 error the same way as a successful delete and clear the bucket name.
This also fixes a bug where if deleting the bucket fails for whatever reason, Ocim no longer goes on to delete the IAM user, policy, and access key, because that makes it impossible to automatically delete the bucket on a retry.
1. Create some test instances on Ocim stage. Archived them. You can use the management command: `make manage -- archive_instances --domains <mysubdomain>.stage.opencraft.hosting`. Note: Feel free to use "Delete Test 1" through "Delete Test 4" that I already created in Ocim stage for testing purposes.
2. Log into the Ocim Stage S3 AWS account (find info on how to log in in vault under …

Clear s3_bucket_name when bucket doesn't exist.

---

registration/signals.py
registration/tests/test_api.py
registration/utils.py
templates/emails/redeployment_success_email.html
templates/emails/redeployment_success_email.txt

Sends email to the BetaTestApplication user on successful instance redeployment of changes made by user.
**JIRA Tickets** : [BB-3592](https://tasks.opencraft.com/browse/BB-3592)
1. Checkout to this PR
2. ssh to the vagrant box
3. run `make test.one 'registration.tests.test_api.InstanceDeploymentAPITestCase.test_send_email_on_application_redeployment'`and check all the tests pass
**Reviewers**

BB-3592 Send email on successful instance update

---

frontend/src/console/components/ThemeColors/ThemeColors.spec.tsx
frontend/src/console/components/ThemeColors/ThemeColors.tsx
frontend/src/console/components/ThemeColors/__snapshots__/ThemeColors.spec.tsx.snap
frontend/src/console/components/ThemeColors/displayMessages.ts
frontend/src/console/components/ThemeColors/index.ts
frontend/src/console/components/ThemeColors/styles.scss
frontend/src/console/components/ThemePreviewAndColors/ThemePreviewAndColors.tsx
frontend/src/console/components/ThemePreviewAndColors/__snapshots__/ThemePreviewAndColors.spec.tsx.snap
frontend/src/console/components/ThemePreviewAndColors/styles.scss
frontend/src/console/components/index.ts

Extracts the color pickers to a separate component.
**JIRA Tickets** [BB-3704](https://tasks.opencraft.com/browse/BB-3704)
2. Start OCIM backend in vagrant using `make run.dev`
3. Start frontend using `npm run start --prefix=frontend`
4. Make sure you have a `BetaTestApplication` with a test user already created. If not visit admin and create appropriate records. Without these the Frontend will not be fully functional.
5. Visit http://localhost:3000/console/theming/preview-and-colors
6. In react devtools, check that `ThemeColor` component is used to display the color components
7. Update color values and check Preview is updated.
8. Check in django admin that theming changes are reflected in the `BetaTestApplication`

[BB-3704] Separate ThemeColor Component

---

frontend/src/console/components/NoticeBoard/NoticeBoard.tsx
frontend/src/console/components/NoticeBoard/__snapshots__/NoticeBoard.spec.tsx.snap
frontend/src/console/components/NoticeBoard/displayMessages.ts
frontend/src/console/components/NoticeBoard/styles.scss

**Description**
We're fulfilling the following user story:
> "As a OCIM user, I want to know why deployment is taking so much time and information regarding that so that I am aware of the complexities"
**Supporting information**
- [Jira ticket](https://tasks.opencraft.com/browse/BB-3584)
- [Blogpost draft](https://docs.google.com/document/d/11hlSn40RKN82ePtxs0e5j0CwgM5POhFHwdopoXalMFA/edit?usp=sharing)
1. Set up a local OCIM environment using this branch
2. Make the necessary changes (most likely on `ui/components/Header`) to bypass the login logic. 
3. Head to `http://localhost:3000/console/notice`
**Snapshots:**
Also, check Jira ticket.
**Further considerations:**
- Seeing that I'm not fully aware of the roadmap, I could use some feedback on the blogpost
- At …

[BB-3584] Add explanation to deployment page 

---

frontend/package-lock.json
frontend/src/console/components/ButtonCustomizationPage/ButtonCustomizationPage.tsx
frontend/src/console/components/ButtonCustomizationPage/__snapshots__/ButtonCustomizationPage.spec.tsx.snap
frontend/src/console/components/ButtonStyles/ButtonStyles.spec.tsx
frontend/src/console/components/ButtonStyles/ButtonStyles.tsx
frontend/src/console/components/ButtonStyles/__snapshots__/ButtonStyles.spec.tsx.snap
frontend/src/console/components/ButtonStyles/displayMessages.ts
frontend/src/console/components/ButtonStyles/index.ts
frontend/src/console/components/ButtonStyles/styles.scss
frontend/src/console/components/ThemeButtons/styles.scss
frontend/src/console/components/index.ts

Adds a ButtonStyles component extracted out of ButtonCustomizationPage component.
**Tickets** [BB-3777](https://tasks.opencraft.com/browse/BB-3777) [Gitlab#710](https://gitlab.com/opencraft/dev/opencraft/-/issues/710)
**Screenshots**: See Gitlab issues
2. Start OCIM backend in vagrant using make run.dev
3. Start frontend using npm run start --prefix=frontend
4. Make sure you have a BetaTestApplication with a test user already created. If not visit admin and create appropriate records. Without these the Frontend will not be fully functional.
5. Visit http://localhost:3000/console/theming/buttons
6. In react devtools, check that `ButtonStyles` component is used to display the color pickers collapsible
7. Update color values and check …

BB-3777 Add ButtonStyles component

---

circle.yml

No testing required. If CI checks passed — everything works as expected.

Change simple theme version back to master

---

documentation/requirements.in
documentation/requirements.txt
requirements/base.in
requirements/base.txt
requirements/dev.in
requirements/dev.txt
requirements/test.txt

This addresses the following vulnerabilities in this repository:
* [CVE-2020-1747](https://github.com/advisories/GHSA-6757-jp84-gxfx): Improper Input Validation in PyYAML
* [CVE-2021-20270](https://github.com/advisories/GHSA-9w8r-397f-prfh): Infinite Loop in Pygments

[SE-4386] Address vulnerabilities

---

cleanup_utils/openstack_cleanup.py

* [BB-4378 (OpenCraft Internal)](https://tasks.opencraft.com/browse/BB-4378)
I've already pushed this to the `ci-cleanup` branch, see [CI results](https://app.circleci.com/pipelines/github/open-craft/opencraft/4121/workflows/35c5152b-f885-4916-9fad-5edb896df98c/jobs/37066)

fix: Skip empty hashes when cleaning up OpenStack servers created by CI

---

registration/tests/test_domain_utils.py
registration/utils.py

This PR ensures that users registered with CloudFlare (and using DNS proxying) can still set custom domain names without assistance.
Ocim is validating domain/subdomain setup by looking into the DNS records of the given domain. This probably works for most of the domain names (as we experience it), though in some cases (like CF proxied domains) it fails and will never work.
What are proxied domains? Basically a DoT (DNS over TLS) setup for the given DNS record (in this case a CNAME) that gives possibility for the end users to be saved from DDOS attacks as the attack would hit CF name servers instead of the server the record pointing to (a.k.a OpenCraft edX app server).
Couldn't the users simply turn of proxying? They could and the DNS resolution should start working almost immediately. Do …

[SE-5070] fix: apply workaround for CloudFlare proxied domain check
